import { PermissionKey } from "@prisma/client";

import { requirePermission } from "@/lib/permissions";
import { prisma } from "@/lib/prisma";
import { getCurrentUserTenant } from "@/lib/tenant";
import { buildFieldworkAnalytics } from "@/modules/research/research-fieldwork-analytics";
import { buildInterviewerQuality } from "@/modules/research/research-fieldwork-assurance";
import {
  chartElements,
  createResearchPresentation,
  type SlideElement,
} from "@/modules/research/research-presentation";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

export async function GET(
  _request: Request,
  { params }: { params: Promise<{ executionId: string }> },
) {
  await requirePermission(PermissionKey.EXPORT_RESEARCH_OUTPUTS);
  const [{ executionId }, { organizationId }] = await Promise.all([
    params,
    getCurrentUserTenant(),
  ]);
  const execution = await prisma.researchSamplingExecution.findFirst({
    where: { id: executionId, organizationId },
    include: {
      project: { include: { client: true } },
      samplingDesign: true,
      samplingFrame: true,
      generatedBy: { select: { name: true } },
      approvedBy: { select: { name: true } },
      units: { include: { assignedTo: { select: { name: true } }, fieldworkResponse: { include: { enumerator: { select: { name: true } } } } } },
    },
  });
  if (!execution)
    return new Response("Sampling execution not found.", { status: 404 });
  const analytics = buildFieldworkAnalytics(execution.units);
  const interviewerQuality = buildInterviewerQuality(execution.units.flatMap((unit) => unit.fieldworkResponse ? [unit.fieldworkResponse] : []));
  const slides: SlideElement[][] = [
    [
      item(
        0.7,
        0.7,
        11,
        0.4,
        "SENZILYTICS FIELDWORK COMMAND BRIEFING",
        14,
        true,
        "67E8F9",
      ),
      item(0.7, 1.55, 11.4, 0.8, execution.project.title, 30, true),
      item(
        0.7,
        2.7,
        11,
        0.4,
        `${execution.project.reference} · Execution v${execution.version} · ${execution.status}`,
        16,
        false,
        "94A3B8",
      ),
      item(
        0.7,
        3.55,
        11,
        0.4,
        execution.project.client?.name ?? "Internal research",
        16,
        false,
        "CBD5E1",
      ),
    ],
    [
      item(0.7, 0.5, 11, 0.5, "Operational Performance", 26, true),
      ...metrics([
        ["Selected", analytics.selected],
        ["Assigned", analytics.assigned],
        ["Completed", analytics.completed],
        ["Response rate", `${analytics.responseRate.toFixed(1)}%`],
        ["Cooperation", `${analytics.cooperationRate.toFixed(1)}%`],
        ["Overdue", analytics.overdue],
        ["Unassigned", analytics.unassigned],
        ["Avg. attempts", analytics.averageAttempts.toFixed(1)],
      ]),
    ],
    [
      item(0.7, 0.5, 11, 0.5, "Disposition Mix", 26, true),
      ...chartElements(analytics.dispositions),
    ],
    [
      item(0.7, 0.5, 11, 0.5, "Researcher Completion Rates", 26, true),
      ...chartElements(analytics.researchers),
    ],
    [
      item(0.7, 0.5, 11, 0.5, "Strata Completion Rates", 26, true),
      ...chartElements(analytics.strata),
    ],
    [
      item(0.7, 0.5, 11, 0.5, "Interviewer Quality Review Indicators", 26, true),
      item(0.7, 1.05, 11, 0.35, "Transparent response-level indicators for human review; not automated performance scores.", 11, false, "94A3B8"),
      ...chartElements(interviewerQuality.map((entry) => ({ name: entry.name, value: entry.reviewPriority }))),
    ],
    [
      item(0.7, 0.5, 11, 0.5, "Governance Record", 26, true),
      item(
        0.8,
        1.5,
        11,
        0.4,
        `Sampling method: ${execution.samplingDesign.type.replaceAll("_", " ")}`,
        15,
        false,
        "CBD5E1",
      ),
      item(
        0.8,
        2.2,
        11,
        0.4,
        `Validated frame: ${execution.samplingFrame.name} (${execution.samplingFrame.rowCount} units)`,
        15,
        false,
        "CBD5E1",
      ),
      item(
        0.8,
        2.9,
        11,
        0.4,
        `Generated by: ${execution.generatedBy.name}`,
        15,
        false,
        "CBD5E1",
      ),
      item(
        0.8,
        3.6,
        11,
        0.4,
        `Approved by: ${execution.approvedBy?.name ?? "Pending"}`,
        15,
        false,
        "CBD5E1",
      ),
      item(
        0.8,
        4.3,
        11,
        0.4,
        `Generated: ${new Date().toISOString()}`,
        12,
        false,
        "94A3B8",
      ),
    ],
  ];
  const output = await createResearchPresentation(slides);
  return new Response(new Uint8Array(output), {
    headers: {
      "Content-Type":
        "application/vnd.openxmlformats-officedocument.presentationml.presentation",
      "Content-Disposition": `attachment; filename="${execution.project.reference}-fieldwork-v${execution.version}.pptx"`,
      "Cache-Control": "private, no-store",
    },
  });
}
function item(
  x: number,
  y: number,
  w: number,
  h: number,
  text: string,
  size: number,
  bold = false,
  color?: string,
): SlideElement {
  return { x, y, w, h, text, size, bold, color };
}
function metrics(values: Array<[string, string | number]>): SlideElement[] {
  return values.map(([label, value], index) =>
    item(
      0.8 + (index % 4) * 3,
      1.55 + Math.floor(index / 4) * 1.65,
      2.65,
      0.75,
      `${label}\n${value}`,
      18,
      true,
      index === 5 && Number(value) > 0 ? "FCA5A5" : "FFFFFF",
    ),
  );
}
