import { ApproveManagementReviewForm, CertificationReviewCapaForm, CompleteManagementReviewForm } from "@/features/assurance/certification-forms";
import { PrintManagementReviewButton } from "@/features/assurance/print-management-review-button";
import { EntityCustomFormSubmissions } from "@/features/forms/entity-custom-form-submissions";
import { getCurrentUserPermissions, requirePermission } from "@/lib/permissions";
import { prisma } from "@/lib/prisma";
import { hasSubscriptionFeature } from "@/lib/subscription";
import { getCurrentUserTenant } from "@/lib/tenant";
import { getCertificationReadinessService } from "@/modules/assurance/certification-readiness.service";
import { getPublishedRuntimeForms } from "@/modules/forms/runtime-form.service";
import { CertificationManagementReviewStatus, ConfigurableFormModule, DocumentEntityType, PermissionKey } from "@prisma/client";
import { ArrowLeft, CheckCircle2, ClipboardCheck } from "lucide-react";
import Link from "next/link";
import { notFound } from "next/navigation";

export default async function CertificationManagementReviewPage({params}:{params:Promise<{id:string}>}){
  await requirePermission(PermissionKey.VIEW_CERTIFICATION_READINESS);const[{id},{organizationId,user},permissions]=await Promise.all([params,getCurrentUserTenant(),getCurrentUserPermissions()]);const canManage=permissions.includes(PermissionKey.MANAGE_CERTIFICATION_READINESS),canCreateCapa=permissions.includes(PermissionKey.CREATE_CAPA);const review=await prisma.certificationManagementReview.findFirst({where:{id,organizationId},include:{program:true,chair:true,createdBy:true,completedBy:true,approvedBy:true,actions:{include:{correctiveAction:{include:{assignedTo:true}}},orderBy:{createdAt:"desc"}}}});if(!review)notFound();const[overview,users,forms,uploadEnabled]=await Promise.all([getCertificationReadinessService(organizationId,review.programId),canManage?prisma.user.findMany({where:{organizationId,isActive:true},select:{id:true,name:true},orderBy:{name:"asc"}}):[],getPublishedRuntimeForms(organizationId,ConfigurableFormModule.CERTIFICATION_READINESS),hasSubscriptionFeature(organizationId,"DOCUMENT_UPLOAD")]);const planned=review.status===CertificationManagementReviewStatus.PLANNED||review.status===CertificationManagementReviewStatus.IN_PROGRESS,recorded=review.status===CertificationManagementReviewStatus.COMPLETED||review.status===CertificationManagementReviewStatus.APPROVED;
  const defaults={audit:`${overview.evidence.auditedSites}/${overview.evidence.scopedSites} scoped sites have a completed program audit. ${overview.evidence.openFindings} findings remain open.`,compliance:`${overview.evidence.overdueCompliance} scoped compliance obligations and ${overview.evidence.overdueCapas} program CAPAs are overdue.`,objectives:`Current internal certification-readiness indicator: ${overview.readiness.total}% (${overview.readiness.band.replaceAll("_"," ")}).`,risks:`${overview.evidence.highRisks} elevated risks and ${overview.evidence.failedCriticalControls} deficient or overdue critical controls are visible in scope.`};
  return <div><Link href={`/assurance/certification/${review.programId}`} className="inline-flex items-center gap-2 text-sm text-slate-400 print:hidden"><ArrowLeft size={16}/>{review.program.name}</Link><div className="mt-6 flex flex-wrap justify-between gap-4"><div><p className="flex items-center gap-2 text-sm text-cyan-300"><ClipboardCheck size={17}/>{review.reference}</p><h1 className="mt-2 text-4xl font-bold">{review.title}</h1><p className="mt-2 text-slate-400">Review period {review.periodStart.toLocaleDateString()}–{review.periodEnd.toLocaleDateString()} · Scheduled {review.scheduledAt.toLocaleDateString()} · Chair {review.chair.name}</p></div><div className="flex items-start gap-3">{recorded&&<PrintManagementReviewButton/>}<span className="h-fit rounded-full bg-cyan-400/10 px-4 py-2 text-sm text-cyan-300">{review.status.replaceAll("_"," ")}</span></div></div>
    {planned&&canManage&&<div className="mt-8"><CompleteManagementReviewForm reviewId={review.id} programId={review.programId} forms={forms} defaults={defaults}/></div>}
    {recorded&&<section className="mt-8 rounded-3xl border border-white/10 bg-white/5 p-6"><div className="flex items-center gap-2"><CheckCircle2 className="text-emerald-300"/><h2 className="text-xl font-semibold">Recorded management-review outputs</h2></div><div className="mt-5 grid gap-5 md:grid-cols-2"><Text label="Audit results" value={review.auditResultsSummary}/><Text label="Compliance status" value={review.complianceStatusSummary}/><Text label="Objectives and performance" value={review.objectivesPerformance}/><Text label="Stakeholder feedback" value={review.stakeholderFeedback}/><Text label="Changes in context" value={review.changesInContext}/><Text label="Risks and opportunities" value={review.risksAndOpportunities}/><Text label="Resource adequacy" value={review.resourceAdequacy}/><Text label="Leadership decisions" value={review.decisions}/><Text label="Improvement opportunities" value={review.improvementOpportunities}/><Text label="Conclusion" value={review.conclusion?.replaceAll("_"," ")}/></div><p className="mt-5 text-sm text-slate-400">Readiness snapshot: <strong className="text-white">{review.readinessScore}%</strong> · Next review {review.nextReviewAt?.toLocaleDateString()||"not recorded"}</p></section>}
    {recorded&&<EntityCustomFormSubmissions organizationId={organizationId} userId={user.id} module={ConfigurableFormModule.CERTIFICATION_READINESS} entityType={DocumentEntityType.CERTIFICATION_READINESS} entityId={review.id} canUpload={canManage&&uploadEnabled} className="mt-8 space-y-6"/>}
    {review.status===CertificationManagementReviewStatus.COMPLETED&&canManage&&<div className="mt-8"><ApproveManagementReviewForm reviewId={review.id} programId={review.programId}/></div>}
    {recorded&&canManage&&canCreateCapa&&<div className="mt-8"><CertificationReviewCapaForm reviewId={review.id} reference={review.reference} users={users}/></div>}
    <section className="mt-8 rounded-3xl border border-white/10 bg-white/5 p-6"><h2 className="text-xl font-semibold">Decision actions</h2><div className="mt-5 space-y-3">{review.actions.map(link=><Link key={link.id} href={`/actions/${link.correctiveActionId}`} className="block rounded-2xl border border-white/10 bg-slate-950/40 p-5 hover:border-cyan-400/30"><div className="flex flex-wrap justify-between gap-3"><div><p className="font-medium">{link.correctiveAction.title}</p><p className="mt-1 text-xs text-slate-500">{link.agendaTopic||"Management-review decision"} · Owner {link.correctiveAction.assignedTo.name}</p></div><span className="text-sm text-cyan-300">{link.correctiveAction.status.replaceAll("_"," ")} · due {link.correctiveAction.dueDate.toLocaleDateString()}</span></div><p className="mt-2 text-sm text-slate-400">{link.decision}</p></Link>)}{!review.actions.length&&<p className="text-sm text-slate-500">No corrective actions have been created from this review.</p>}</div></section>
  </div>;
}
function Text({label,value}:{label:string;value:string|null|undefined}){return <div><p className="text-xs uppercase text-slate-500">{label}</p><p className="mt-1 whitespace-pre-wrap text-sm text-slate-200">{value||"Not recorded"}</p></div>}
