ALTER TYPE "ConfigurableFormModule" ADD VALUE IF NOT EXISTS 'CHEMICAL';
ALTER TYPE "ConfigurableFormModule" ADD VALUE IF NOT EXISTS 'ENVIRONMENTAL';
ALTER TYPE "ConfigurableFormModule" ADD VALUE IF NOT EXISTS 'ESG';
