import { ContractorSiteForm, ContractorStatusForm, ContractorWorkerForm } from "@/features/contractors/contractor-management-forms";
import { completeContractorForms } from "@/features/contractors/actions";
import { EntityCustomFormSubmissions } from "@/features/forms/entity-custom-form-submissions";
import { RuntimeFormCompletion } from "@/features/forms/runtime-form-completion";
import { getCurrentUserPermissions, requirePermission } from "@/lib/permissions";
import { prisma } from "@/lib/prisma";
import { hasSubscriptionFeature } from "@/lib/subscription";
import { getCurrentUserTenant } from "@/lib/tenant";
import { getPublishedRuntimeForms } from "@/modules/forms/runtime-form.service";
import { ConfigurableFormModule, DocumentEntityType, PermissionKey } from "@prisma/client";
import { ArrowLeft, Building2, ShieldCheck, Users } from "lucide-react";
import Link from "next/link";
import { notFound } from "next/navigation";

export default async function ContractorDetailPage({ params }: { params: Promise<{ id: string }> }) {
  await requirePermission(PermissionKey.VIEW_CONTRACTORS);
  const [{ id }, { organizationId, user }, permissions] = await Promise.all([params, getCurrentUserTenant(), getCurrentUserPermissions()]);
  const canManage = permissions.includes(PermissionKey.MANAGE_CONTRACTORS);
  const [contractor, allSites, forms, capturedForms, uploadEnabled] = await Promise.all([
    prisma.contractor.findFirst({ where: { id, organizationId }, include: { approvedBy: true, sites: { include: { site: true }, orderBy: { site: { name: "asc" } } }, workers: { orderBy: [{ status: "asc" }, { lastName: "asc" }] }, permitsToWork: { include: { site: true }, orderBy: { plannedStartAt: "desc" }, take: 20 } } }),
    prisma.site.findMany({ where: { organizationId }, select: { id: true, name: true }, orderBy: { name: "asc" } }),
    getPublishedRuntimeForms(organizationId, ConfigurableFormModule.CONTRACTOR),
    prisma.configurableFormSubmission.findMany({ where: { organizationId, entityType: ConfigurableFormModule.CONTRACTOR, entityId: id }, select: { definitionId: true } }),
    hasSubscriptionFeature(organizationId, "DOCUMENT_UPLOAD"),
  ]);
  if (!contractor) notFound();
  const capturedIds = new Set(capturedForms.map(item => item.definitionId)); const missingForms = forms.filter(form => !capturedIds.has(form.id));
  const availableSites = allSites.filter(site => !contractor.sites.some(scope => scope.siteId === site.id));
  return <div><Link href="/contractors" className="inline-flex items-center gap-2 text-sm text-slate-400 hover:text-white"><ArrowLeft size={16}/>Back to contractors</Link>
    <div className="mt-6 flex flex-wrap items-start justify-between gap-5"><div><p className="flex items-center gap-2 text-sm text-cyan-300"><Building2 size={17}/>{contractor.registrationNumber || "CONTRACTOR"}</p><h1 className="mt-2 text-4xl font-bold">{contractor.name}</h1><p className="mt-3 max-w-4xl whitespace-pre-wrap text-slate-400">{contractor.services || "Services have not been recorded."}</p></div><div className="flex gap-3"><span className="h-fit rounded-full border border-cyan-400/20 bg-cyan-400/10 px-4 py-2 text-sm text-cyan-200">{contractor.status.replaceAll("_", " ")}</span>{canManage && contractor.status === "APPROVED" && <Link href={`/permits-to-work/new?contractorId=${contractor.id}`} className="rounded-xl bg-cyan-300 px-4 py-2 text-sm font-semibold text-slate-950">Create Permit</Link>}</div></div>
    {canManage && <RuntimeFormCompletion action={completeContractorForms} entityId={contractor.id} entityIdName="contractorId" forms={missingForms} submitLabel="Save Contractor Forms"/>}
    <EntityCustomFormSubmissions organizationId={organizationId} userId={user.id} module={ConfigurableFormModule.CONTRACTOR} entityType={DocumentEntityType.CONTRACTOR} entityId={contractor.id} canUpload={canManage && uploadEnabled} className="mt-8 space-y-6"/>
    <div className="mt-8 grid gap-6 lg:grid-cols-2"><section className="rounded-3xl border border-white/10 bg-white/5 p-6"><h2 className="flex items-center gap-2 text-xl font-semibold"><ShieldCheck size={20} className="text-cyan-300"/>Qualification profile</h2><dl className="mt-5 grid gap-4 sm:grid-cols-2"><Detail label="Legal name" value={contractor.legalName}/><Detail label="Primary contact" value={contractor.primaryContactName}/><Detail label="Email" value={contractor.primaryContactEmail}/><Detail label="Phone" value={contractor.primaryContactPhone}/><Detail label="Insurance provider" value={contractor.insuranceProvider}/><Detail label="Policy" value={contractor.insurancePolicyNumber}/><Detail label="Insurance expires" value={contractor.insuranceExpiresAt?.toLocaleDateString()}/><Detail label="Safety rating" value={contractor.safetyRating === null ? null : `${contractor.safetyRating}/100`}/><Detail label="Approved by" value={contractor.approvedBy?.name}/><Detail label="Approved at" value={contractor.approvedAt?.toLocaleString()}/></dl>{contractor.safetyProgramSummary && <p className="mt-5 whitespace-pre-wrap rounded-xl bg-slate-950/50 p-4 text-sm text-slate-300">{contractor.safetyProgramSummary}</p>}{contractor.suspensionReason && <p className="mt-4 rounded-xl border border-red-400/20 bg-red-400/10 p-4 text-sm text-red-300">Suspension: {contractor.suspensionReason}</p>}</section>{canManage ? <ContractorStatusForm contractorId={contractor.id} currentStatus={contractor.status}/> : <section className="h-fit rounded-3xl border border-white/10 bg-white/5 p-6"><h2 className="text-xl font-semibold">Governance access</h2><p className="mt-2 text-sm text-slate-400">You can review contractor qualification records. A contractor manager must approve or change status.</p></section>}</div>
    <div className="mt-6 grid gap-6 lg:grid-cols-2"><section className="rounded-3xl border border-white/10 bg-white/5 p-6"><h2 className="text-xl font-semibold">Authorized sites</h2><div className="mt-4 space-y-3">{contractor.sites.map(scope => <div key={scope.id} className="rounded-xl bg-slate-950/50 p-4"><p className="font-medium">{scope.site.name}</p><p className="mt-1 text-xs text-slate-500">Approved {scope.approvedAt.toLocaleDateString()} · Expires {scope.expiresAt?.toLocaleDateString() || "not set"}</p>{scope.notes && <p className="mt-2 text-sm text-slate-400">{scope.notes}</p>}</div>)}{!contractor.sites.length && <p className="text-sm text-slate-500">No site authorizations.</p>}</div></section>{canManage && <ContractorSiteForm contractorId={contractor.id} sites={availableSites}/>}</div>
    <section className="mt-6 rounded-3xl border border-white/10 bg-white/5 p-6"><h2 className="flex items-center gap-2 text-xl font-semibold"><Users size={20} className="text-cyan-300"/>Contractor workers</h2><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead className="text-xs uppercase text-slate-500"><tr><th className="p-3">Worker</th><th className="p-3">Role</th><th className="p-3">Status</th><th className="p-3">Induction expires</th><th className="p-3">Medical expires</th></tr></thead><tbody>{contractor.workers.map(worker => <tr key={worker.id} className="border-t border-white/5"><td className="p-3"><p className="font-medium">{worker.firstName} {worker.lastName}</p><p className="text-xs text-slate-500">{worker.employeeNumber || worker.email || "No identifier"}</p></td><td className="p-3 text-slate-400">{worker.jobTitle || "Not recorded"}</td><td className="p-3">{worker.status}</td><td className="p-3">{worker.inductionExpiresAt?.toLocaleDateString() || "Not set"}</td><td className="p-3">{worker.medicalExpiresAt?.toLocaleDateString() || "Not set"}</td></tr>)}</tbody></table></div>{!contractor.workers.length && <p className="mt-4 text-sm text-slate-500">No workers have been registered.</p>}</section>
    {canManage && <div className="mt-6 grid gap-6 lg:grid-cols-2"><ContractorWorkerForm contractorId={contractor.id}/></div>}
    <section className="mt-6 rounded-3xl border border-white/10 bg-white/5 p-6"><h2 className="text-xl font-semibold">Permit-to-work history</h2><div className="mt-4 space-y-3">{contractor.permitsToWork.map(permit => <Link key={permit.id} href={`/permits-to-work/${permit.id}`} className="flex flex-wrap items-center justify-between gap-3 rounded-xl bg-slate-950/50 p-4"><span><strong>{permit.reference}</strong> — {permit.title}<span className="mt-1 block text-xs text-slate-500">{permit.site.name} · {permit.plannedStartAt.toLocaleString()}</span></span><span className="text-xs text-cyan-300">{permit.status.replaceAll("_", " ")}</span></Link>)}{!contractor.permitsToWork.length && <p className="text-sm text-slate-500">No permits have been linked.</p>}</div></section>
  </div>;
}
function Detail({ label, value }: { label: string; value: string | null | undefined }) { return <div><dt className="text-xs uppercase tracking-wide text-slate-500">{label}</dt><dd className="mt-1 text-slate-200">{value || "Not recorded"}</dd></div>; }
