"use client";

import { initialFormActionState } from "@/core/actions/action-state";
import { createCompetency, createCompetencyRequirement, decideCompetencyAssessment, linkCourseCompetency, submitCompetencyAssessment } from "@/features/training/competency.actions";
import { CompetencyCategory, CompetencyEvidenceType, CompetencyProficiency, UserRole } from "@prisma/client";
import { useActionState } from "react";

const input="mt-2 w-full rounded-xl border border-white/10 bg-slate-950/70 px-4 py-3";
function Feedback({state}:{state:{status:string;message:string|null}}){return state.message?<p role={state.status==="ERROR"?"alert":"status"} className={`mt-4 rounded-xl border p-3 text-sm ${state.status==="ERROR"?"border-red-400/20 bg-red-400/10 text-red-300":"border-emerald-400/20 bg-emerald-400/10 text-emerald-200"}`}>{state.message}</p>:null}
function Field({name,label,type="text",required=false,defaultValue}:{name:string;label:string;type?:string;required?:boolean;defaultValue?:string}){return <label className="text-sm">{label}<input name={name} type={type} required={required} defaultValue={defaultValue} min={type==="number"?0:undefined} step={type==="number"?"any":undefined} className={input}/></label>}

export function CompetencyCreateForm(){const[state,action,pending]=useActionState(createCompetency,initialFormActionState);return <form action={action} className="rounded-3xl border border-white/10 bg-white/5 p-6"><h2 className="text-xl font-semibold">Create competency</h2><div className="mt-4 grid gap-4 sm:grid-cols-2"><Field name="code" label="Code" required/><Field name="name" label="Name" required/><label className="text-sm">Category<select name="category" className={input}>{Object.values(CompetencyCategory).map(x=><option key={x} value={x}>{x.replaceAll("_"," ")}</option>)}</select></label><Field name="validityMonths" label="Validity months" type="number"/></div><label className="mt-4 block text-sm">Description<textarea name="description" rows={3} className={input}/></label><label className="mt-4 flex items-center gap-3 text-sm"><input type="checkbox" name="isCritical"/>Safety-critical competency</label><button disabled={pending} className="mt-5 rounded-xl bg-cyan-300 px-5 py-3 font-semibold text-slate-950 disabled:opacity-50">{pending?"Saving…":"Create Competency"}</button><Feedback state={state}/></form>}

export function CourseCompetencyForm({competencies,courses}:{competencies:{id:string;code:string;name:string}[];courses:{id:string;code:string;name:string}[]}){const[state,action,pending]=useActionState(linkCourseCompetency,initialFormActionState);return <form action={action} className="rounded-3xl border border-white/10 bg-white/5 p-6"><h2 className="text-xl font-semibold">Map course outcome</h2><label className="mt-4 block text-sm">Competency<select name="competencyId" required className={input}><option value="">Select</option>{competencies.map(x=><option key={x.id} value={x.id}>{x.code} — {x.name}</option>)}</select></label><label className="mt-4 block text-sm">Course<select name="courseId" required className={input}><option value="">Select</option>{courses.map(x=><option key={x.id} value={x.id}>{x.code} — {x.name}</option>)}</select></label><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="text-sm">Achieved level<select name="achievedLevel" className={input}>{Object.values(CompetencyProficiency).map(x=><option key={x}>{x}</option>)}</select></label><Field name="minimumScore" label="Minimum score (%)" type="number"/></div><label className="mt-4 flex items-center gap-3 text-sm"><input type="checkbox" name="isPrimary"/>Primary course for this competency</label><button disabled={pending} className="mt-5 rounded-xl bg-cyan-300 px-5 py-3 font-semibold text-slate-950">{pending?"Mapping…":"Map Course"}</button><Feedback state={state}/></form>}

export function CompetencyRequirementForm({competencies,sites,departments}:{competencies:{id:string;code:string;name:string}[];sites:{id:string;name:string}[];departments:{id:string;name:string;site:{name:string}}[]}){const[state,action,pending]=useActionState(createCompetencyRequirement,initialFormActionState);return <form action={action} className="rounded-3xl border border-white/10 bg-white/5 p-6 xl:col-span-2"><h2 className="text-xl font-semibold">Define workforce requirement</h2><div className="mt-4 grid gap-4 md:grid-cols-3"><label className="text-sm">Competency<select name="competencyId" required className={input}><option value="">Select</option>{competencies.map(x=><option key={x.id} value={x.id}>{x.code} — {x.name}</option>)}</select></label><label className="text-sm">Required level<select name="requiredLevel" className={input}>{Object.values(CompetencyProficiency).map(x=><option key={x}>{x}</option>)}</select></label><label className="text-sm">Role<select name="role" className={input}><option value="">All roles</option>{Object.values(UserRole).map(x=><option key={x}>{x}</option>)}</select></label><Field name="jobTitle" label="Exact job title"/><label className="text-sm">Site<select name="siteId" className={input}><option value="">All sites</option>{sites.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label className="text-sm">Department<select name="departmentId" className={input}><option value="">All departments</option>{departments.map(x=><option key={x.id} value={x.id}>{x.site.name} — {x.name}</option>)}</select></label><Field name="dueWithinDays" label="Gap closure days" type="number" required defaultValue="30"/></div><label className="mt-4 flex items-center gap-3 text-sm"><input type="checkbox" name="isMandatory" defaultChecked/>Mandatory requirement</label><button disabled={pending} className="mt-5 rounded-xl bg-cyan-300 px-5 py-3 font-semibold text-slate-950">{pending?"Saving…":"Create Requirement"}</button><Feedback state={state}/></form>}

export function CompetencyAssessmentForm({users,competencies}:{users:{id:string;name:string;jobTitle:string|null}[];competencies:{id:string;code:string;name:string}[]}){const[state,action,pending]=useActionState(submitCompetencyAssessment,initialFormActionState);return <form action={action} className="rounded-3xl border border-white/10 bg-white/5 p-6"><h2 className="text-xl font-semibold">Submit competency evidence</h2><div className="mt-4 grid gap-4 md:grid-cols-2"><label className="text-sm">Learner<select name="learnerId" required className={input}><option value="">Select</option>{users.map(x=><option key={x.id} value={x.id}>{x.name}{x.jobTitle?` — ${x.jobTitle}`:""}</option>)}</select></label><label className="text-sm">Competency<select name="competencyId" required className={input}><option value="">Select</option>{competencies.map(x=><option key={x.id} value={x.id}>{x.code} — {x.name}</option>)}</select></label><label className="text-sm">Assessed level<select name="assessedLevel" className={input}>{Object.values(CompetencyProficiency).map(x=><option key={x} value={x}>{x}</option>)}</select></label><label className="text-sm">Evidence type<select name="evidenceType" className={input}>{Object.values(CompetencyEvidenceType).filter(x=>x!==CompetencyEvidenceType.TRAINING).map(x=><option key={x} value={x}>{x.replaceAll("_"," ")}</option>)}</select></label><Field name="assessedAt" label="Assessment date" type="date" required/><Field name="evidenceReference" label="Evidence / certificate reference"/></div><label className="mt-4 block text-sm">Assessment notes<textarea name="notes" rows={3} className={input}/></label><p className="mt-4 text-xs text-slate-500">Manual evidence requires verification by a different training manager. Course completions mapped to a competency are verified automatically.</p><button disabled={pending} className="mt-5 rounded-xl bg-cyan-300 px-5 py-3 font-semibold text-slate-950">{pending?"Submitting…":"Submit Evidence"}</button><Feedback state={state}/></form>}

export function CompetencyDecisionForm({assessmentId}:{assessmentId:string}){const[state,action,pending]=useActionState(decideCompetencyAssessment,initialFormActionState);return <form action={action} className="mt-3 grid gap-2 sm:grid-cols-[1fr_auto_auto]"><input type="hidden" name="assessmentId" value={assessmentId}/><input name="rejectionReason" placeholder="Reason required when rejecting" className="rounded-lg border border-white/10 bg-slate-950 px-3 py-2 text-sm"/><button name="decision" value="VERIFIED" disabled={pending} className="rounded-lg border border-emerald-400/20 px-3 py-2 text-xs text-emerald-300">Verify</button><button name="decision" value="REJECTED" disabled={pending} className="rounded-lg border border-red-400/20 px-3 py-2 text-xs text-red-300">Reject</button>{state.message&&<p role={state.status==="ERROR"?"alert":"status"} className={`sm:col-span-3 text-xs ${state.status==="ERROR"?"text-red-300":"text-emerald-300"}`}>{state.message}</p>}</form>}
