import { AuditActionForm } from "@/features/audits/audit-action-form";
import { addAuditScheduleTeamMember, changeAuditScheduleStatusWithFeedback, removeAuditScheduleTeamMember } from "@/features/audits/schedule.actions";
import { requirePermission } from "@/lib/permissions";
import { getCurrentUserTenant } from "@/lib/tenant";
import { findTenantAuditScheduleById, findTenantAuditUsers } from "@/modules/audit/audit-schedule.repository";
import { EnterpriseAuditScheduleStatus, EnterpriseAuditScheduleTeamRole, PermissionKey } from "@prisma/client";
import { ArrowLeft, CalendarClock, ShieldCheck, Users } from "lucide-react";
import Link from "next/link";
import { notFound } from "next/navigation";

export default async function AuditScheduleDetailPage({ params }: { params: Promise<{ id: string }> }) {
  await requirePermission(PermissionKey.VIEW_AUDITS); const [{ id }, { organizationId }] = await Promise.all([params, getCurrentUserTenant()]); const [schedule, users] = await Promise.all([findTenantAuditScheduleById(id, organizationId), findTenantAuditUsers(organizationId)]); if (!schedule) notFound();
  return <div><Link href="/audits/schedules" className="inline-flex items-center gap-2 text-sm text-slate-400 hover:text-white"><ArrowLeft size={16} /> Back to schedules</Link><div className="mt-6 flex flex-wrap items-start justify-between gap-4"><div><p className="flex items-center gap-2 text-sm text-cyan-300"><CalendarClock size={16} /> {schedule.program.code || "AUDIT PROGRAM"} · {pretty(schedule.status)}</p><h1 className="mt-2 text-4xl font-bold">{schedule.name}</h1><p className="mt-2 max-w-3xl text-slate-400">{schedule.description || schedule.program.name}</p></div><div className="flex gap-3">{schedule.status === EnterpriseAuditScheduleStatus.ACTIVE && <ScheduleStatusButton scheduleId={schedule.id} status={EnterpriseAuditScheduleStatus.PAUSED} label="Pause" />}{schedule.status === EnterpriseAuditScheduleStatus.PAUSED && <ScheduleStatusButton scheduleId={schedule.id} status={EnterpriseAuditScheduleStatus.ACTIVE} label="Resume" />}{(schedule.status === EnterpriseAuditScheduleStatus.ACTIVE || schedule.status === EnterpriseAuditScheduleStatus.PAUSED) && <ScheduleStatusButton scheduleId={schedule.id} status={EnterpriseAuditScheduleStatus.CANCELLED} label="Cancel" danger />}</div></div>
    <div className="mt-8 grid gap-4 md:grid-cols-4"><Info label="Frequency" value={`${pretty(schedule.frequency)} × ${schedule.intervalValue}`} /><Info label="Next generation" value={formatDate(schedule.nextRunAt)} /><Info label="Generation lead" value={`${schedule.generateDaysBefore} days`} /><Info label="Audit due window" value={`${schedule.dueDaysAfter} days`} /></div>
    <div className="mt-8 grid gap-6 lg:grid-cols-2"><Panel title="Schedule configuration" icon={<ShieldCheck size={18} />}><Line label="Program" value={schedule.program.name} /><Line label="Site" value={schedule.site.name} /><Line label="Department" value={schedule.department?.name || "All departments"} /><Line label="Protocol" value={schedule.protocol ? `${schedule.protocol.name} v${schedule.protocol.version}` : "Not assigned"} /><Line label="Lead auditor" value={schedule.leadAuditor?.name || "Not assigned"} /><Line label="Timezone" value={schedule.timezone} /><Line label="Start date" value={formatDate(schedule.startDate)} /><Line label="End date" value={formatDate(schedule.endDate)} /></Panel>
      <Panel title="Schedule team" icon={<Users size={18} />}><div className="space-y-3">{schedule.teamMembers.map((member) => <div key={member.id} className="flex items-center justify-between gap-3 rounded-2xl bg-slate-950/40 p-4"><div><p className="text-sm font-medium">{member.user.name}</p><p className="mt-1 text-xs text-slate-500">{pretty(member.role)}{member.user.jobTitle ? ` · ${member.user.jobTitle}` : ""}</p></div>{member.userId !== schedule.leadAuditorId && <form action={removeAuditScheduleTeamMember}><input type="hidden" name="scheduleId" value={schedule.id} /><input type="hidden" name="memberId" value={member.userId} /><button className="text-xs text-red-300">Remove</button></form>}</div>)}</div><form action={addAuditScheduleTeamMember} className="mt-5 space-y-4 rounded-2xl border border-white/10 p-4"><input type="hidden" name="scheduleId" value={schedule.id} /><Field label="Team member"><select name="memberId" required defaultValue="" className={inputClass}><option value="" disabled>Select user</option>{users.map((user) => <option key={user.id} value={user.id}>{user.name}{user.jobTitle ? ` — ${user.jobTitle}` : ""}</option>)}</select></Field><Field label="Role"><select name="role" defaultValue={EnterpriseAuditScheduleTeamRole.AUDITOR} className={inputClass}>{Object.values(EnterpriseAuditScheduleTeamRole).map((role) => <option key={role} value={role}>{pretty(role)}</option>)}</select></Field><button className="rounded-xl bg-cyan-300 px-4 py-2 text-sm font-semibold text-slate-950">Assign Team Member</button></form></Panel>
      <section className="rounded-3xl border border-white/10 bg-white/5 p-6 lg:col-span-2"><h2 className="mb-5 flex items-center gap-2 text-lg font-semibold"><CalendarClock size={18} className="text-cyan-300" /> Generated Audits</h2>{schedule.enterpriseAudits.length === 0 ? <p className="rounded-2xl border border-dashed border-white/10 p-5 text-sm text-slate-500">No audits have been generated from this schedule yet.</p> : <div className="grid gap-3 md:grid-cols-2">{schedule.enterpriseAudits.map((audit) => <Link key={audit.id} href={`/audits/${audit.id}`} className="rounded-2xl bg-slate-950/40 p-4"><p className="text-sm font-medium">{audit.reference} — {audit.title}</p><p className="mt-1 text-xs text-slate-500">{pretty(audit.status)} · Due {formatDate(audit.dueDate)}</p></Link>)}</div>}</section></div>
  </div>;
}
const inputClass = "mt-2 w-full rounded-xl border border-white/10 bg-slate-950/70 px-3 py-2 text-sm outline-none"; function pretty(value: string) { return value.replaceAll("_", " "); } function formatDate(value: Date | null) { return value ? value.toLocaleString() : "Not set"; } function Info({ label, value }: { label: string; value: string }) { return <div className="rounded-2xl bg-slate-950/40 p-4"><p className="text-xs uppercase text-slate-500">{label}</p><p className="mt-2 text-sm">{value}</p></div>; } function Panel({ title, icon, children }: { title: string; icon: React.ReactNode; children: React.ReactNode }) { return <section className="rounded-3xl border border-white/10 bg-white/5 p-6"><h2 className="mb-5 flex items-center gap-2 text-lg font-semibold"><span className="text-cyan-300">{icon}</span>{title}</h2>{children}</section>; } function Line({ label, value }: { label: string; value: string }) { return <div className="mb-3 flex justify-between gap-4 border-b border-white/5 pb-3 text-sm"><span className="text-slate-500">{label}</span><span className="text-right">{value}</span></div>; } function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block text-sm text-slate-300">{label}{children}</label>; }
function ScheduleStatusButton({ scheduleId, status, label, danger = false }: { scheduleId: string; status: EnterpriseAuditScheduleStatus; label: string; danger?: boolean }) { return <AuditActionForm action={changeAuditScheduleStatusWithFeedback}><input type="hidden" name="scheduleId" value={scheduleId} /><input type="hidden" name="status" value={status} /><button className={`rounded-xl border px-4 py-2 text-sm font-semibold ${danger ? "border-red-400/30 text-red-200" : "border-cyan-400/30 text-cyan-200"}`}>{label}</button></AuditActionForm>; }
