import { SifSignalReviewForm } from "@/features/assurance/sif-forms";
import { getCurrentUserPermissions, requirePermission } from "@/lib/permissions";
import { getCurrentUserTenant } from "@/lib/tenant";
import { getSifIntelligenceOverview } from "@/modules/assurance/sif-intelligence.service";
import { PermissionKey } from "@prisma/client";
import { Activity, Radar, ShieldCheck, Target } from "lucide-react";
import Link from "next/link";

export const dynamic="force-dynamic";
export default async function SifIntelligencePage(){
  await requirePermission(PermissionKey.VIEW_SIF_INTELLIGENCE);
  const[{organizationId},permissions]=await Promise.all([getCurrentUserTenant(),getCurrentUserPermissions()]);
  const canManage=permissions.includes(PermissionKey.MANAGE_CRITICAL_CONTROLS),overview=await getSifIntelligenceOverview({organizationId,permissions});
  return <div><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="flex items-center gap-2 text-sm text-cyan-300"><Radar size={17}/>Serious Injury & Fatality Prevention</p><h1 className="mt-2 text-4xl font-bold">SIF & Weak-Signal Intelligence</h1><p className="mt-2 max-w-3xl text-slate-400">Identify converging precursors, review potential SIF exposure, and verify the controls that prevent high-consequence events.</p></div><Link href="/assurance/sif/controls" className="inline-flex items-center gap-2 rounded-xl bg-cyan-300 px-5 py-3 font-semibold text-slate-950"><ShieldCheck size={17}/>Critical Controls</Link></div>
    <div className="mt-7 grid gap-4 sm:grid-cols-3 xl:grid-cols-6"><Metric label="Active signals" value={overview.metrics.activeSignals}/><Metric label="Awaiting review" value={overview.metrics.unreviewed} warning={overview.metrics.unreviewed>0}/><Metric label="High confidence" value={overview.metrics.highConfidence} danger={overview.metrics.highConfidence>0}/><Metric label="pSIF decisions" value={overview.metrics.potentialSif}/><Metric label="Critical clusters" value={overview.metrics.criticalClusters} danger={overview.metrics.criticalClusters>0}/><Metric label="Control coverage" value={`${overview.metrics.controlCoveragePercent}%`} warning={overview.metrics.controlCoveragePercent<80}/></div>
    <section className="mt-8 rounded-3xl border border-cyan-400/15 bg-cyan-400/[.04] p-6"><div className="flex items-start gap-3"><Target className="mt-1 shrink-0 text-cyan-300"/><div><h2 className="text-lg font-semibold">Explainable prevention pressure</h2><p className="mt-1 text-sm text-slate-400">This workspace is a prioritization aid—not an injury probability forecast. Scores use visible factors such as potential severity, near-miss status, overdue response, repeat conditions, missing action links, and critical-control verification results. Authorized reviewers make every pSIF and precursor decision.</p></div></div></section>
    <section className="mt-8"><div className="flex items-end justify-between"><div><h2 className="text-xl font-semibold">Prevention-pressure clusters</h2><p className="mt-1 text-sm text-slate-400">Signals grouped by site and SIF exposure category over the last {overview.windowDays} days.</p></div><span className="text-xs text-slate-500">Updated {overview.generatedAt.toLocaleString()}</span></div><div className="mt-5 grid gap-4 lg:grid-cols-2 xl:grid-cols-3">{overview.clusters.map(cluster=><article key={cluster.id} className="rounded-2xl border border-white/10 bg-white/5 p-5"><div className="flex justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-wide text-cyan-300">{cluster.siteName}</p><h3 className="mt-1 font-semibold">{cluster.category.replaceAll("_"," ")}</h3></div><span className={`h-fit rounded-full px-3 py-1 text-xs ${cluster.pressure==="CRITICAL"?"bg-red-400/15 text-red-300":cluster.pressure==="ELEVATED"?"bg-amber-400/15 text-amber-300":"bg-cyan-400/15 text-cyan-300"}`}>{cluster.pressure}</span></div><div className="mt-4 grid grid-cols-3 gap-2 text-center"><Small label="Signals" value={cluster.count}/><Small label="Score" value={cluster.score}/><Small label="Trend" value={cluster.trend}/></div><p className={`mt-4 text-sm ${cluster.coveragePercent<80?"text-amber-300":"text-emerald-300"}`}>{cluster.effectiveControls}/{cluster.controlCount} applicable controls currently effective ({cluster.coveragePercent}%).</p>{cluster.controlCount===0&&<p className="mt-2 text-xs text-red-300">No mapped critical control standard covers this exposure cluster.</p>}</article>)}{!overview.clusters.length&&<Empty text="No qualifying signal clusters are visible for the selected evidence window."/>}</div></section>
    <section className="mt-8 rounded-3xl border border-white/10 bg-white/5 p-6"><div className="flex items-center gap-2"><Activity className="text-cyan-300"/><h2 className="text-xl font-semibold">Priority weak signals</h2></div><p className="mt-1 text-sm text-slate-400">Review source evidence before confirming a precursor or potential SIF classification.</p><div className="mt-5 space-y-4">{overview.signals.slice(0,40).map(signal=><article key={signal.id} className="rounded-2xl border border-white/10 bg-slate-950/40 p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0"><p className="text-xs font-semibold uppercase tracking-wide text-cyan-300">{signal.sourceLabel}{signal.siteName?` · ${signal.siteName}`:""}</p><Link href={signal.href} className="mt-1 block font-semibold hover:text-cyan-200">{signal.title}</Link><p className="mt-1 text-sm text-slate-400">{signal.detail}</p><p className="mt-2 text-xs text-slate-500">{signal.reasons.join(" · ")}</p></div><div className="text-right"><span className={`rounded-full px-3 py-1 text-xs ${signal.confidence==="HIGH"?"bg-red-400/15 text-red-300":signal.confidence==="MEDIUM"?"bg-amber-400/15 text-amber-300":"bg-cyan-400/15 text-cyan-300"}`}>{signal.confidence} · {signal.score}</span><p className="mt-2 text-xs text-slate-500">{signal.category.replaceAll("_"," ")}</p>{signal.review&&<p className="mt-1 text-xs text-emerald-300">{signal.review.classification.replaceAll("_"," ")} · {signal.review.reviewedBy.name}</p>}</div></div>{canManage&&<SifSignalReviewForm signal={signal}/>}</article>)}{!overview.signals.length&&<Empty text="No active weak signals meet the evidence threshold."/>}</div></section>
  </div>;
}
function Metric({label,value,danger=false,warning=false}:{label:string;value:number|string;danger?:boolean;warning?:boolean}){return <div className="rounded-2xl border border-white/10 bg-white/5 p-5"><p className="text-xs uppercase text-slate-500">{label}</p><p className={`mt-2 text-3xl font-bold ${danger?"text-red-300":warning?"text-amber-300":""}`}>{value}</p></div>}
function Small({label,value}:{label:string;value:number|string}){return <div className="rounded-xl bg-slate-950/50 p-3"><p className="text-[10px] uppercase text-slate-500">{label}</p><p className="mt-1 text-sm font-semibold">{value}</p></div>}
function Empty({text}:{text:string}){return <p className="rounded-2xl border border-dashed border-white/10 p-8 text-center text-sm text-slate-500">{text}</p>}
