import { getCurrentUserPermissions, requirePermission } from "@/lib/permissions";
import { getCurrentUserTenant } from "@/lib/tenant";
import { getUnifiedCalendarItems } from "@/modules/compliance/unified-calendar.service";
import { PermissionKey } from "@prisma/client";
import Link from "next/link";

export default async function ComplianceCalendarAnalyticsPage(){
  await requirePermission(PermissionKey.VIEW_COMPLIANCE);const[{organizationId,user},permissions]=await Promise.all([getCurrentUserTenant(),getCurrentUserPermissions()]);const end=new Date(),start=new Date(end);start.setMonth(start.getMonth()-12);
  const items=await getUnifiedCalendarItems({organizationId,userId:user.id,userRole:user.role,permissions,start,end,mineOnly:false}),completed=items.filter(item=>item.completed),overdue=items.filter(item=>item.overdue);
  const sources=[...new Set(items.map(item=>item.sourceLabel))].map(name=>{const rows=items.filter(item=>item.sourceLabel===name),done=rows.filter(item=>item.completed).length;return{name,total:rows.length,completed:done,overdue:rows.filter(item=>item.overdue).length,rate:rows.length?Math.round(done/rows.length*100):0}}).sort((a,b)=>b.total-a.total);
  const sites=[...new Set(items.map(item=>item.site).filter((site):site is string=>Boolean(site)))].map(name=>{const rows=items.filter(item=>item.site===name),done=rows.filter(item=>item.completed).length;return{name,total:rows.length,rate:rows.length?Math.round(done/rows.length*100):0}}).sort((a,b)=>b.total-a.total);
  return <div><div className="flex justify-between gap-4"><div><p className="text-sm text-cyan-300">Cross-Module Assurance Intelligence</p><h1 className="mt-2 text-4xl font-bold">Unified Calendar Analytics</h1><p className="mt-2 text-slate-400">Rolling 12-month performance across every calendar-connected module accessible to your role.</p></div><Link href="/compliance/calendar" className="h-fit rounded-xl border border-white/10 px-4 py-2">Calendar</Link></div><div className="mt-8 grid gap-4 md:grid-cols-4"><Metric label="Dated commitments" value={items.length}/><Metric label="Completion rate" value={`${items.length?Math.round(completed.length/items.length*100):0}%`}/><Metric label="Completed" value={completed.length}/><Metric label="Overdue exposure" value={overdue.length}/></div>
    <div className="mt-8 grid gap-6 xl:grid-cols-2"><section className="rounded-3xl border border-white/10 bg-white/5 p-6"><h2 className="text-xl font-semibold">Performance by source</h2><div className="mt-5 space-y-4">{sources.map(row=><div key={row.name}><div className="flex justify-between gap-4 text-sm"><span>{row.name}</span><span className="text-slate-400">{row.completed}/{row.total} complete · {row.overdue} overdue</span></div><div className="mt-2 h-2 rounded-full bg-slate-800"><div className="h-2 rounded-full bg-cyan-300" style={{width:`${row.rate}%`}}/></div></div>)}</div></section><section className="rounded-3xl border border-white/10 bg-white/5 p-6"><h2 className="text-xl font-semibold">Performance by site</h2><div className="mt-5 space-y-4">{sites.map(row=><div key={row.name}><div className="flex justify-between text-sm"><span>{row.name}</span><span className="text-slate-400">{row.rate}% · {row.total} commitments</span></div><div className="mt-2 h-2 rounded-full bg-slate-800"><div className="h-2 rounded-full bg-emerald-300" style={{width:`${row.rate}%`}}/></div></div>)}{!sites.length&&<p className="text-sm text-slate-500">No site-linked calendar records are available.</p>}</div></section></div>
  </div>;
}
function Metric({label,value}:{label:string;value:string|number}){return <div className="rounded-3xl border border-white/10 bg-white/5 p-6"><p className="text-sm text-slate-400">{label}</p><p className="mt-2 text-3xl font-bold">{value}</p></div>}
