import { ScheduleManagementReviewForm } from "@/features/assurance/certification-forms";
import { getCurrentUserPermissions, requirePermission } from "@/lib/permissions";
import { prisma } from "@/lib/prisma";
import { getCurrentUserTenant } from "@/lib/tenant";
import { getCertificationReadinessService } from "@/modules/assurance/certification-readiness.service";
import { PermissionKey } from "@prisma/client";
import { ArrowLeft, ClipboardCheck, FileWarning, Gauge, ShieldCheck } from "lucide-react";
import Link from "next/link";
import { notFound } from "next/navigation";

const labels={protocolFoundation:"Protocol foundation",auditCoverage:"Audit coverage",conformance:"Conformance",evidenceAndClosure:"Evidence & closure",operationalControl:"Operational control",managementReview:"Management review"} as const;
export default async function CertificationProgramReadinessPage({params}:{params:Promise<{programId:string}>}){
  await requirePermission(PermissionKey.VIEW_CERTIFICATION_READINESS);const[{programId},{organizationId},permissions]=await Promise.all([params,getCurrentUserTenant(),getCurrentUserPermissions()]);const canManage=permissions.includes(PermissionKey.MANAGE_CERTIFICATION_READINESS);let overview;try{overview=await getCertificationReadinessService(organizationId,programId)}catch{return notFound()}const users=canManage?await prisma.user.findMany({where:{organizationId,isActive:true},select:{id:true,name:true},orderBy:{name:"asc"}}):[];const{program,readiness,evidence}=overview;
  return <div><Link href="/assurance/certification" className="inline-flex items-center gap-2 text-sm text-slate-400"><ArrowLeft size={16}/>Certification Readiness</Link><div className="mt-6 flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm text-cyan-300">{program.standardName||program.framework}{program.standardVersion?` · ${program.standardVersion}`:""}</p><h1 className="mt-2 text-4xl font-bold">{program.name}</h1><p className="mt-2 max-w-3xl text-slate-400">{program.scope||"Program scope has not been described."}</p></div><div className="rounded-2xl border border-white/10 bg-white/5 p-5 text-right"><strong className="text-5xl">{readiness.total}%</strong><p className={`mt-1 text-xs ${readiness.band==="READY_FOR_FORMAL_REVIEW"?"text-emerald-300":readiness.band==="NEEDS_ATTENTION"?"text-amber-300":"text-red-300"}`}>{readiness.band.replaceAll("_"," ")}</p></div></div>
    <section className="mt-8 grid gap-4 md:grid-cols-3"><Metric icon={Gauge} label="Audited scope" value={`${evidence.auditedSites}/${evidence.scopedSites} sites`}/><Metric icon={ShieldCheck} label="Conforming responses" value={`${evidence.compliantQuestions}/${evidence.applicableQuestions}`}/><Metric icon={FileWarning} label="Open findings" value={String(evidence.openFindings)} danger={evidence.openFindings>0}/></section>
    <section className="mt-8 rounded-3xl border border-white/10 bg-white/5 p-6"><h2 className="text-xl font-semibold">Transparent readiness dimensions</h2><p className="mt-1 text-sm text-slate-400">Each dimension shows its raw score and contribution to the weighted total.</p><div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{readiness.dimensions.map(row=><div key={row.key} className="rounded-2xl border border-white/10 bg-slate-950/40 p-5"><div className="flex justify-between"><p className="font-medium">{labels[row.key]}</p><strong>{row.score}%</strong></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-slate-900"><div className="h-full bg-cyan-300" style={{width:`${row.score}%`}}/></div><p className="mt-2 text-xs text-slate-500">Weight {row.weight}% · contributes {row.contribution.toFixed(1)} points</p></div>)}</div></section>
    <div className="mt-8 grid gap-6 xl:grid-cols-[1.2fr_.8fr]"><section className="rounded-3xl border border-white/10 bg-white/5 p-6"><h2 className="text-xl font-semibold">Protocol section coverage</h2><div className="mt-5 space-y-3">{overview.sections.map(section=><div key={section.id} className="rounded-2xl border border-white/10 bg-slate-950/40 p-4"><div className="flex flex-wrap justify-between gap-3"><div><p className="font-medium">{section.title}</p><p className="mt-1 text-xs text-slate-500">{section.standardRef||"No section standard reference"} · {section.questionCount} protocol questions</p></div><p className="text-sm text-cyan-300">{section.answeredPercent}% answered · {section.conformancePercent}% conforming</p></div></div>)}{!overview.sections.length&&<p className="text-sm text-slate-500">The default protocol has no active sections.</p>}</div></section><section className="rounded-3xl border border-amber-400/15 bg-amber-400/[.04] p-6"><h2 className="text-xl font-semibold">Priority readiness gaps</h2><div className="mt-5 space-y-3">{overview.gaps.map((gap,index)=><div key={`${gap}-${index}`} className="flex gap-3 rounded-xl bg-slate-950/40 p-4"><FileWarning className="shrink-0 text-amber-300" size={18}/><p className="text-sm text-slate-300">{gap}</p></div>)}{!overview.gaps.length&&<p className="text-sm text-emerald-300">No readiness gaps were identified by the configured evidence rules.</p>}</div></section></div>
    <section className="mt-8 rounded-3xl border border-white/10 bg-white/5 p-6"><div className="flex items-center gap-2"><ClipboardCheck className="text-cyan-300"/><h2 className="text-xl font-semibold">Management-review history</h2></div><div className="mt-5 space-y-3">{program.certificationReviews.map(review=><Link key={review.id} href={`/assurance/certification/reviews/${review.id}`} className="flex flex-wrap items-center justify-between gap-4 rounded-2xl border border-white/10 bg-slate-950/40 p-5 hover:border-cyan-400/30"><div><p className="font-semibold">{review.reference} — {review.title}</p><p className="mt-1 text-xs text-slate-500">{review.scheduledAt.toLocaleDateString()} · Chair {review.chair.name}{review.readinessScore!==null?` · ${review.readinessScore}% snapshot`:""}</p></div><span className="rounded-full bg-cyan-400/10 px-3 py-1 text-xs text-cyan-300">{review.status.replaceAll("_"," ")}</span></Link>)}{!program.certificationReviews.length&&<p className="text-sm text-slate-500">No management review has been scheduled for this program.</p>}</div></section>
    {canManage&&<div className="mt-8"><ScheduleManagementReviewForm programId={program.id} programName={program.name} users={users}/></div>}
  </div>;
}
function Metric({icon:Icon,label,value,danger=false}:{icon:typeof Gauge;label:string;value:string;danger?:boolean}){return <div className="rounded-2xl border border-white/10 bg-white/5 p-5"><div className="flex justify-between"><div><p className="text-xs uppercase text-slate-500">{label}</p><p className={`mt-2 text-2xl font-bold ${danger?"text-red-300":""}`}>{value}</p></div><Icon className="text-cyan-300"/></div></div>}
