"use client";
import { initialFormActionState } from "@/core/actions/action-state";
import { createExposureGroup,createHygieneAgent } from "@/features/industrial-hygiene/actions";
import { HygieneAgentCategory } from "@prisma/client";
import { useActionState } from "react";
const input="mt-2 w-full rounded-xl border border-white/10 bg-slate-950/70 px-4 py-3";
function Feedback({state}:{state:{status:string;message:string|null}}){return state.message?<p role={state.status==="ERROR"?"alert":"status"} className={`mt-4 rounded-xl border p-3 text-sm ${state.status==="ERROR"?"border-red-400/20 bg-red-400/10 text-red-300":"border-emerald-400/20 bg-emerald-400/10 text-emerald-200"}`}>{state.message}</p>:null}
export function HygieneAgentForm(){const[state,action,pending]=useActionState(createHygieneAgent,initialFormActionState);return <form action={action} className="rounded-3xl border border-white/10 bg-white/5 p-6"><h2 className="text-xl font-semibold">Add exposure agent</h2><div className="mt-4 grid gap-4 sm:grid-cols-2"><Field name="name" label="Agent name" required/><label className="text-sm">Category<select name="category" className={input}>{Object.values(HygieneAgentCategory).map(x=><option key={x}>{x}</option>)}</select></label><Field name="casNumber" label="CAS number"/><Field name="unit" label="Limit unit"/><Field name="occupationalLimit" label="Occupational limit" type="number"/><Field name="actionLevel" label="Action level" type="number"/><Field name="ceilingLimit" label="Ceiling limit" type="number"/><Field name="limitSource" label="Limit source"/><Field name="samplingMethod" label="Sampling method"/><Field name="analyticalMethod" label="Analytical method"/></div><Area name="healthEffects" label="Health effects"/><Area name="exposureRoutes" label="Exposure routes"/><label className="mt-4 flex items-center gap-3 text-sm"><input type="checkbox" name="requiresSurveillance"/>May trigger medical surveillance</label><button disabled={pending} className="mt-5 rounded-xl bg-cyan-300 px-5 py-3 font-semibold text-slate-950 disabled:opacity-50">{pending?"Saving…":"Save Agent"}</button><Feedback state={state}/></form>}
export function ExposureGroupForm({sites,departments,users,agents}:{sites:{id:string;name:string}[];departments:{id:string;name:string;site:{name:string}}[];users:{id:string;name:string}[];agents:{id:string;name:string}[]}){const[state,action,pending]=useActionState(createExposureGroup,initialFormActionState);return <form action={action} className="rounded-3xl border border-white/10 bg-white/5 p-6 xl:col-span-2"><h2 className="text-xl font-semibold">Create Similar Exposure Group</h2><div className="mt-4 grid gap-4 md:grid-cols-3"><Field name="name" label="Group name" required/><Field name="code" label="Code"/><label className="text-sm">Site<select name="siteId" required className={input}><option value="">Select</option>{sites.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label className="text-sm">Department<select name="departmentId" className={input}><option value="">None</option>{departments.map(x=><option key={x.id} value={x.id}>{x.site.name} — {x.name}</option>)}</select></label><label className="text-sm">Owner<select name="ownerId" className={input}><option value="">Unassigned</option>{users.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><Field name="exposedHeadcount" label="Exposed headcount" type="number"/><Field name="reviewDueDate" label="Review due" type="date"/></div><div className="mt-4 grid gap-4 md:grid-cols-2"><Area name="jobRoles" label="Job roles"/><Area name="tasks" label="Tasks"/><Area name="locations" label="Locations"/><Area name="existingControls" label="Existing controls"/><Area name="requiredPpe" label="Required PPE"/></div><fieldset className="mt-4"><legend className="text-sm">Exposure agents <span className="text-red-300">*</span></legend><div className="mt-3 grid gap-2 sm:grid-cols-2">{agents.map(x=><label key={x.id} className="flex items-center gap-3 rounded-xl border border-white/10 p-3 text-sm"><input type="checkbox" name="agentIds" value={x.id}/>{x.name}</label>)}</div></fieldset><button disabled={pending} className="mt-5 rounded-xl bg-cyan-300 px-5 py-3 font-semibold text-slate-950 disabled:opacity-50">{pending?"Saving…":"Create Group"}</button><Feedback state={state}/></form>}
function Field({name,label,type="text",required=false}:{name:string;label:string;type?:string;required?:boolean}){return <label className="text-sm">{label}<input name={name} type={type} required={required} min={type==="number"?0:undefined} step={type==="number"?"any":undefined} className={input}/></label>};function Area({name,label}:{name:string;label:string}){return <label className="mt-4 block text-sm">{label}<textarea name={name} rows={2} className={input}/></label>}
