"use server";

import type { FormActionState } from "@/core/actions/action-state";
import { requirePermission } from "@/lib/permissions";
import { getCurrentUserTenant } from "@/lib/tenant";
import { completeSurveillanceEnrollmentService, createSurveillanceProgramService, enrollSurveillanceUserService, removeSurveillanceEnrollmentService, updateSurveillanceProgramStatusService } from "@/modules/occupational-health/occupational-health.service";
import { FitnessOutcome, PermissionKey, SurveillanceProgramStatus } from "@prisma/client";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";

const text=(data:FormData,key:string)=>String(data.get(key)||"").trim();const required=(data:FormData,key:string)=>{const value=text(data,key);if(!value)throw new Error(`${key} is required.`);return value};const optional=(data:FormData,key:string)=>text(data,key)||null;const integer=(data:FormData,key:string)=>{const value=Number(required(data,key));if(!Number.isInteger(value))throw new Error(`${key} must be a whole number.`);return value};const date=(data:FormData,key:string)=>{const value=new Date(required(data,key));if(Number.isNaN(value.getTime()))throw new Error(`${key} must be a valid date.`);return value};const error=(cause:unknown,fallback:string):FormActionState=>({status:"ERROR",message:cause instanceof Error?cause.message:fallback});

export async function createSurveillanceProgram(_state:FormActionState,data:FormData):Promise<FormActionState>{await requirePermission(PermissionKey.MANAGE_OCCUPATIONAL_HEALTH);const{organizationId,user}=await getCurrentUserTenant();let id:string;try{const program=await createSurveillanceProgramService({organizationId,userId:user.id,name:required(data,"name"),description:optional(data,"description"),regulatoryBasis:optional(data,"regulatoryBasis"),protocolReference:optional(data,"protocolReference"),providerName:optional(data,"providerName"),frequencyMonths:integer(data,"frequencyMonths"),leadDays:integer(data,"leadDays"),agentId:optional(data,"agentId"),groupId:optional(data,"groupId"),responsibleUserId:required(data,"responsibleUserId")});id=program.id}catch(cause){return error(cause,"The surveillance program could not be created.")}redirect(`/occupational-health/${id}`)}
export async function updateSurveillanceProgramStatus(_state:FormActionState,data:FormData):Promise<FormActionState>{await requirePermission(PermissionKey.MANAGE_OCCUPATIONAL_HEALTH);const{organizationId,user}=await getCurrentUserTenant();const programId=required(data,"programId");try{const status=required(data,"status") as SurveillanceProgramStatus;if(!Object.values(SurveillanceProgramStatus).includes(status))throw new Error("Select a valid program status.");await updateSurveillanceProgramStatusService({organizationId,userId:user.id,programId,status})}catch(cause){return error(cause,"The program status could not be updated.")}revalidatePath(`/occupational-health/${programId}`);revalidatePath("/occupational-health");return{status:"SUCCESS",message:"Program status updated."}}
export async function enrollSurveillanceUser(_state:FormActionState,data:FormData):Promise<FormActionState>{await requirePermission(PermissionKey.MANAGE_OCCUPATIONAL_HEALTH);const{organizationId,user}=await getCurrentUserTenant();const programId=required(data,"programId");try{await enrollSurveillanceUserService({organizationId,userId:user.id,programId,enrolledUserId:required(data,"enrolledUserId"),nextDueAt:date(data,"nextDueAt"),notes:optional(data,"notes")})}catch(cause){return error(cause,"The worker could not be enrolled.")}revalidatePath(`/occupational-health/${programId}`);return{status:"SUCCESS",message:"Worker enrolled in surveillance."}}
export async function completeSurveillanceEnrollment(_state:FormActionState,data:FormData):Promise<FormActionState>{await requirePermission(PermissionKey.MANAGE_OCCUPATIONAL_HEALTH);const{organizationId,user}=await getCurrentUserTenant();const programId=required(data,"programId");try{const fitnessOutcome=required(data,"fitnessOutcome") as FitnessOutcome;if(!Object.values(FitnessOutcome).includes(fitnessOutcome))throw new Error("Select a valid fitness outcome.");await completeSurveillanceEnrollmentService({organizationId,userId:user.id,enrollmentId:required(data,"enrollmentId"),completedAt:date(data,"completedAt"),fitnessOutcome,workRestrictions:optional(data,"workRestrictions"),certificateReference:optional(data,"certificateReference"),notes:optional(data,"notes")})}catch(cause){return error(cause,"The surveillance completion could not be recorded.")}revalidatePath(`/occupational-health/${programId}`);return{status:"SUCCESS",message:"Surveillance completion recorded."}}
export async function removeSurveillanceEnrollment(_state:FormActionState,data:FormData):Promise<FormActionState>{await requirePermission(PermissionKey.MANAGE_OCCUPATIONAL_HEALTH);const{organizationId,user}=await getCurrentUserTenant();const programId=required(data,"programId");try{await removeSurveillanceEnrollmentService({organizationId,userId:user.id,enrollmentId:required(data,"enrollmentId"),reason:required(data,"reason")})}catch(cause){return error(cause,"The enrollment could not be removed.")}revalidatePath(`/occupational-health/${programId}`);return{status:"SUCCESS",message:"Enrollment removed."}}
