INSERT INTO "RolePermission" ("id","role","permission","createdAt") VALUES
('chem-super-view','SUPER_ADMIN','VIEW_CHEMICALS',CURRENT_TIMESTAMP),('chem-super-manage','SUPER_ADMIN','MANAGE_CHEMICALS',CURRENT_TIMESTAMP),
('chem-org-view','ORG_ADMIN','VIEW_CHEMICALS',CURRENT_TIMESTAMP),('chem-org-manage','ORG_ADMIN','MANAGE_CHEMICALS',CURRENT_TIMESTAMP),
('chem-ehs-view','EHS_MANAGER','VIEW_CHEMICALS',CURRENT_TIMESTAMP),('chem-ehs-manage','EHS_MANAGER','MANAGE_CHEMICALS',CURRENT_TIMESTAMP),
('chem-supervisor-view','SUPERVISOR','VIEW_CHEMICALS',CURRENT_TIMESTAMP),('chem-auditor-view','AUDITOR','VIEW_CHEMICALS',CURRENT_TIMESTAMP)
ON CONFLICT ("role","permission") DO NOTHING;
