import { prisma } from "@/lib/prisma";
import { getCompetencyMatrixService } from "@/modules/training/competency.service";
import { PermissionKey, UserRole } from "@prisma/client";

export type UnifiedCalendarSource = "COMPLIANCE_CALENDAR"|"COMPLIANCE_OBLIGATION"|"OBSERVATION"|"AUDIT"|"AUDIT_FINDING"|"INSPECTION"|"CAPA"|"TRAINING"|"COMPETENCY"|"CRITICAL_CONTROL"|"MANAGEMENT_REVIEW"|"ASSET_INSPECTION"|"ASSET_MAINTENANCE"|"PERMIT"|"CONTRACTOR"|"PERMIT_TO_WORK"|"INDUSTRIAL_HYGIENE"|"OCCUPATIONAL_HEALTH"|"RISK_REVIEW"|"MOC"|"WORKFLOW";
export type UnifiedCalendarItem = { id:string; source:UnifiedCalendarSource; sourceLabel:string; title:string; detail:string; date:Date; status:string; href:string; assignee:string; site:string|null; completed:boolean; overdue:boolean };
type Input={organizationId:string;userId:string;userRole:UserRole;permissions:PermissionKey[];start:Date;end:Date;mineOnly:boolean};
const doneStatuses=new Set(["COMPLETED","CLOSED","CANCELLED","APPROVED","VERIFIED","RESOLVED","REJECTED","EXPIRED"]);
export const isUnifiedCalendarStatusComplete=(status:string)=>doneStatuses.has(status);
const openStatus=(status:string)=>!isUnifiedCalendarStatusComplete(status);
const item=(data:Omit<UnifiedCalendarItem,"overdue">):UnifiedCalendarItem=>({...data,overdue:data.date<new Date()&&!data.completed});

export async function getUnifiedCalendarItems(input:Input){
  const allowed=new Set(input.permissions), range={gte:input.start,lt:input.end}, mine=input.mineOnly;
  const canCapa=allowed.has(PermissionKey.CREATE_CAPA)||allowed.has(PermissionKey.UPDATE_CAPA)||allowed.has(PermissionKey.CLOSE_CAPA);
  const [calendar,obligations,observations,audits,findings,inspections,actions,training,competencies,criticalControls,managementReviews,permits,contractors,contractorWorkers,permitsToWork,exposureGroups,exposureAssessments,surveillance,risks,mocTasks,workflowSteps,assetInspections,assetMaintenance,assetWork,competencyMatrix]=await Promise.all([
    allowed.has(PermissionKey.VIEW_COMPLIANCE)?prisma.complianceCalendarOccurrence.findMany({where:{organizationId:input.organizationId,dueAt:range,...(mine?{assignedToId:input.userId}:{})},include:{task:true,site:true,assignedTo:true}}):[],
    allowed.has(PermissionKey.VIEW_COMPLIANCE)?prisma.complianceItem.findMany({where:{site:{organizationId:input.organizationId},dueDate:range,...(mine?{ownerId:input.userId}:{})},include:{site:true,owner:true}}):[],
    allowed.has(PermissionKey.VIEW_OBSERVATIONS)?prisma.safetyObservation.findMany({where:{organizationId:input.organizationId,followUpDueDate:range,...(mine?{assignedToId:input.userId}:{})},include:{site:true,assignedTo:true}}):[],
    allowed.has(PermissionKey.VIEW_AUDITS)?prisma.enterpriseAudit.findMany({where:{organizationId:input.organizationId,AND:[{OR:[{dueDate:range},{AND:[{dueDate:null},{scheduledAt:range}]}]},...(mine?[{OR:[{leadAuditorId:input.userId},{ownerId:input.userId},{teamMembers:{some:{userId:input.userId}}}]}]:[])]},include:{site:true,leadAuditor:true,owner:true}}):[],
    allowed.has(PermissionKey.VIEW_AUDITS)?prisma.enterpriseAuditFinding.findMany({where:{organizationId:input.organizationId,dueDate:range,...(mine?{ownerId:input.userId}:{})},include:{audit:true,owner:true}}):[],
    allowed.has(PermissionKey.VIEW_INSPECTIONS)?prisma.inspection.findMany({where:{site:{organizationId:input.organizationId},AND:[{OR:[{dueDate:range},{AND:[{dueDate:null},{scheduledAt:range}]}]},...(mine?[{OR:[{leadInspectorId:input.userId},{teamMembers:{some:{userId:input.userId}}}]}]:[])]},include:{site:true,leadInspector:true}}):[],
    canCapa?prisma.correctiveAction.findMany({where:{assignedTo:{organizationId:input.organizationId},dueDate:range,...(mine?{assignedToId:input.userId}:{})},include:{assignedTo:true}}):[],
    allowed.has(PermissionKey.VIEW_TRAINING)?prisma.trainingRecord.findMany({where:{user:{organizationId:input.organizationId},dueDate:range,...(mine?{userId:input.userId}:{})},include:{user:true}}):[],
    allowed.has(PermissionKey.VIEW_TRAINING)?prisma.competencyAssessment.findMany({where:{organizationId:input.organizationId,status:"VERIFIED",expiresAt:range,...(mine?{userId:input.userId}:{})},include:{competency:true,user:true}}):[],
    allowed.has(PermissionKey.VIEW_SIF_INTELLIGENCE)?prisma.criticalControlStandard.findMany({where:{organizationId:input.organizationId,isActive:true,nextVerificationDueAt:range,...(mine?{ownerId:input.userId}:{})},include:{owner:true,site:true,verifications:{orderBy:{verifiedAt:"desc"},take:1}}}):[],
    allowed.has(PermissionKey.VIEW_CERTIFICATION_READINESS)?prisma.certificationManagementReview.findMany({where:{organizationId:input.organizationId,OR:[{scheduledAt:range,status:{in:["PLANNED","IN_PROGRESS"]}},{nextReviewAt:range,status:"APPROVED"}],...(mine?{chairId:input.userId}:{})},include:{program:true,chair:true}}):[],
    allowed.has(PermissionKey.VIEW_COMPLIANCE)?prisma.permit.findMany({where:{organizationId:input.organizationId,OR:[{renewalDueDate:range},{AND:[{renewalDueDate:null},{expirationDate:range}]}],...(mine?{ownerId:input.userId}:{})},include:{site:true,owner:true}}):[],
    allowed.has(PermissionKey.VIEW_CONTRACTORS)&&!mine?prisma.contractor.findMany({where:{organizationId:input.organizationId,insuranceExpiresAt:range},include:{approvedBy:true}}):[],
    allowed.has(PermissionKey.VIEW_CONTRACTORS)&&!mine?prisma.contractorWorker.findMany({where:{contractor:{organizationId:input.organizationId},inductionExpiresAt:range},include:{contractor:true}}):[],
    allowed.has(PermissionKey.VIEW_PERMITS_TO_WORK)?prisma.permitToWork.findMany({where:{organizationId:input.organizationId,plannedEndAt:range,...(mine?{requestedById:input.userId}:{})},include:{site:true,contractor:true,requestedBy:true}}):[],
    allowed.has(PermissionKey.VIEW_INDUSTRIAL_HYGIENE)&&!mine?prisma.similarExposureGroup.findMany({where:{organizationId:input.organizationId,reviewDueDate:range,isActive:true},include:{site:true,owner:true}}):[],
    allowed.has(PermissionKey.VIEW_INDUSTRIAL_HYGIENE)?prisma.exposureAssessment.findMany({where:{organizationId:input.organizationId,dueDate:range,...(mine?{assessorId:input.userId}:{})},include:{site:true,assessor:true,group:true}}):[],
    allowed.has(PermissionKey.VIEW_OCCUPATIONAL_HEALTH)?prisma.medicalSurveillanceEnrollment.findMany({where:{program:{organizationId:input.organizationId,isActive:true},nextDueAt:range,...(mine?{OR:[{userId:input.userId},{program:{responsibleUserId:input.userId}}]}:{})},include:{program:true,user:true}}):[],
    allowed.has(PermissionKey.VIEW_RISKS)?prisma.risk.findMany({where:{organizationId:input.organizationId,nextReviewDate:range,...(mine?{ownerId:input.userId}:{})},include:{site:true,owner:true}}):[],
    allowed.has(PermissionKey.VIEW_MOC)?prisma.mocTask.findMany({where:{moc:{organizationId:input.organizationId},dueDate:range,...(mine?{assignedToId:input.userId}:{})},include:{moc:true,assignedTo:true}}):[],
    (mine||allowed.has(PermissionKey.MANAGE_WORKFLOWS))?prisma.workflowInstanceStep.findMany({where:{instance:{organizationId:input.organizationId},dueAt:range,...(mine?{OR:[{assignedUserId:input.userId},{assignedRole:input.userRole},{assignedUserId:null,assignedRole:null}]}:{})},include:{instance:{include:{template:true}},assignedUser:true}}):[],
    allowed.has(PermissionKey.VIEW_ASSETS)?prisma.asset.findMany({where:{organizationId:input.organizationId,status:{not:"RETIRED"},nextInspectionDueAt:range,...(mine?{ownerId:input.userId}:{})},include:{site:true,owner:true}}):[],
    allowed.has(PermissionKey.VIEW_ASSETS)?prisma.asset.findMany({where:{organizationId:input.organizationId,status:{not:"RETIRED"},nextMaintenanceDueAt:range,...(mine?{ownerId:input.userId}:{})},include:{site:true,owner:true}}):[],
    allowed.has(PermissionKey.VIEW_ASSETS)?prisma.assetMaintenanceRecord.findMany({where:{organizationId:input.organizationId,dueAt:range,...(mine?{OR:[{technicianId:input.userId},{asset:{ownerId:input.userId}}]}:{})},include:{asset:{include:{site:true,owner:true}},technician:true}}):[],
    allowed.has(PermissionKey.VIEW_TRAINING)?getCompetencyMatrixService(input.organizationId):{rows:[]},
  ]);
  const items:UnifiedCalendarItem[]=[];
items.push(...calendar.map(x=>item({id:`calendar:${x.id}`,source:"COMPLIANCE_CALENDAR",sourceLabel:"Compliance Calendar",title:x.task.title,detail:x.task.category.replaceAll("_"," "),date:x.dueAt,status:x.status,href:`/compliance/calendar/${x.id}`,assignee:x.assignedTo.name,site:x.site.name,completed:isUnifiedCalendarStatusComplete(x.status)})));
  items.push(...obligations.map(x=>item({id:`obligation:${x.id}`,source:"COMPLIANCE_OBLIGATION",sourceLabel:"Compliance Obligation",title:x.title,detail:x.reference||x.obligationType.replaceAll("_"," "),date:x.dueDate,status:x.status,href:`/compliance/${x.id}`,assignee:x.owner?.name||"Unassigned",site:x.site.name,completed:!openStatus(x.status)})));
  items.push(...observations.map(x=>item({id:`observation:${x.id}`,source:"OBSERVATION",sourceLabel:"Safety Observation",title:`${x.reference} — ${x.title}`,detail:`${x.riskLevel} follow-up`,date:x.followUpDueDate!,status:x.status,href:`/observations/${x.id}`,assignee:x.assignedTo?.name||"Unassigned",site:x.site.name,completed:!openStatus(x.status)})));
  items.push(...audits.map(x=>item({id:`audit:${x.id}`,source:"AUDIT",sourceLabel:"Audit",title:`${x.reference} — ${x.title}`,detail:"Audit execution milestone",date:x.dueDate??x.scheduledAt!,status:x.status,href:`/audits/${x.id}`,assignee:x.leadAuditor?.name||x.owner?.name||"Unassigned",site:x.site.name,completed:!openStatus(x.status)})));
  items.push(...findings.map(x=>item({id:`audit-finding:${x.id}`,source:"AUDIT_FINDING",sourceLabel:"Audit Finding",title:`${x.reference} — ${x.title}`,detail:`${x.severity} finding`,date:x.dueDate!,status:x.status,href:`/audits/${x.auditId}`,assignee:x.owner?.name||"Unassigned",site:null,completed:!openStatus(x.status)})));
  items.push(...inspections.map(x=>item({id:`inspection:${x.id}`,source:"INSPECTION",sourceLabel:"Inspection",title:`${x.reference?`${x.reference} — `:""}${x.title}`,detail:x.type.replaceAll("_"," "),date:x.dueDate??x.scheduledAt!,status:x.status,href:`/inspections/${x.id}`,assignee:x.leadInspector?.name||"Unassigned",site:x.site.name,completed:!openStatus(x.status)})));
  items.push(...actions.map(x=>item({id:`capa:${x.id}`,source:"CAPA",sourceLabel:"Corrective Action",title:x.title,detail:`${x.riskLevel} priority`,date:x.dueDate,status:x.status,href:"/capa",assignee:x.assignedTo.name,site:null,completed:!openStatus(x.status)})));
  items.push(...training.map(x=>item({id:`training:${x.id}`,source:"TRAINING",sourceLabel:"Training",title:x.courseName,detail:"Training assignment",date:x.dueDate!,status:x.status,href:"/training",assignee:x.user.name,site:null,completed:!openStatus(x.status)})));
  items.push(...competencies.map(x=>item({id:`competency:${x.id}`,source:"COMPETENCY",sourceLabel:"Competency Renewal",title:x.competency.name,detail:`${x.assessedLevel} proficiency expires`,date:x.expiresAt!,status:x.status,href:"/training/competencies/matrix",assignee:x.user.name,site:null,completed:false})));
  items.push(...criticalControls.map(x=>item({id:`critical-control:${x.id}`,source:"CRITICAL_CONTROL",sourceLabel:"Critical Control Verification",title:`${x.code} — ${x.name}`,detail:`${x.category.replaceAll("_"," ")} · ${x.verifications[0]?.result.replaceAll("_"," ")||"not yet verified"}`,date:x.nextVerificationDueAt,status:x.nextVerificationDueAt<new Date()?"OVERDUE":"DUE",href:`/assurance/sif/controls/${x.id}`,assignee:x.owner?.name||"Unassigned",site:x.site?.name||null,completed:false})));
  items.push(...managementReviews.map(x=>item({id:`management-review:${x.id}`,source:"MANAGEMENT_REVIEW",sourceLabel:"Management Review",title:`${x.reference} — ${x.title}`,detail:`${x.program.standardName||x.program.framework||"Management system"} · ${x.status==="APPROVED"?"next review":"scheduled review"}`,date:x.status==="APPROVED"?x.nextReviewAt!:x.scheduledAt,status:x.status==="APPROVED"?"NEXT_REVIEW_DUE":x.status,href:`/assurance/certification/reviews/${x.id}`,assignee:x.chair.name,site:null,completed:false})));
  items.push(...assetInspections.map(x=>item({id:`asset-inspection:${x.id}`,source:"ASSET_INSPECTION",sourceLabel:"Asset Inspection",title:`${x.reference} — ${x.name}`,detail:`${x.type.replaceAll("_"," ")} safety inspection`,date:x.nextInspectionDueAt,status:x.nextInspectionDueAt<new Date()?"OVERDUE":"DUE",href:`/assets/${x.id}`,assignee:x.owner?.name||"Unassigned",site:x.site.name,completed:false})));
  items.push(...assetMaintenance.map(x=>item({id:`asset-maintenance:${x.id}`,source:"ASSET_MAINTENANCE",sourceLabel:"Asset Preventive Maintenance",title:`${x.reference} — ${x.name}`,detail:"Recurring preventive-maintenance milestone",date:x.nextMaintenanceDueAt,status:x.nextMaintenanceDueAt<new Date()?"OVERDUE":"DUE",href:`/assets/${x.id}`,assignee:x.owner?.name||"Unassigned",site:x.site.name,completed:false})));
  items.push(...assetWork.map(x=>item({id:`asset-work:${x.id}`,source:"ASSET_MAINTENANCE",sourceLabel:"Asset Maintenance Work",title:x.title,detail:`${x.asset.reference} — ${x.type.replaceAll("_"," ")}`,date:x.dueAt,status:x.status,href:`/assets/${x.assetId}`,assignee:x.technician?.name||x.asset.owner?.name||"Unassigned",site:x.asset.site.name,completed:isUnifiedCalendarStatusComplete(x.status)})));
  items.push(...competencyMatrix.rows.filter(x=>x.gapDueAt&&x.gapDueAt>=input.start&&x.gapDueAt<input.end&&(!mine||x.user.id===input.userId)).map(x=>item({id:`competency-gap:${x.id}`,source:"COMPETENCY",sourceLabel:"Competency Gap",title:x.requirement.competency.name,detail:`${x.requirement.requiredLevel} proficiency required`,date:x.gapDueAt!,status:x.isOverdue?"OVERDUE":x.status,href:"/training/competencies/matrix",assignee:x.user.name,site:x.user.department?.site.name||null,completed:false})));
  items.push(...permits.map(x=>item({id:`permit:${x.id}`,source:"PERMIT",sourceLabel:"Permit",title:`${x.number} — ${x.name}`,detail:x.renewalDueDate?"Renewal deadline":"Expiration date",date:x.renewalDueDate??x.expirationDate!,status:x.status,href:"/compliance/permits",assignee:x.owner?.name||"Unassigned",site:x.site.name,completed:!openStatus(x.status)})));
  items.push(...contractors.map(x=>item({id:`contractor:${x.id}`,source:"CONTRACTOR",sourceLabel:"Contractor Insurance",title:`${x.name} insurance expiry`,detail:x.insurancePolicyNumber||"Insurance renewal",date:x.insuranceExpiresAt!,status:x.status,href:`/contractors/${x.id}`,assignee:x.approvedBy?.name||"Contractor manager",site:null,completed:x.status==="INACTIVE"})));
  items.push(...contractorWorkers.map(x=>item({id:`contractor-worker:${x.id}`,source:"CONTRACTOR",sourceLabel:"Contractor Induction",title:`${x.firstName} ${x.lastName} induction expiry`,detail:x.contractor.name,date:x.inductionExpiresAt!,status:x.status,href:`/contractors/${x.contractorId}`,assignee:"Contractor manager",site:null,completed:x.status==="INACTIVE"})));
  items.push(...permitsToWork.map(x=>item({id:`permit-to-work:${x.id}`,source:"PERMIT_TO_WORK",sourceLabel:"Permit to Work",title:`${x.reference} — ${x.title}`,detail:`${x.type.replaceAll("_"," ")} · ${x.contractor?.name||"Internal work"}`,date:x.plannedEndAt,status:x.status,href:`/permits-to-work/${x.id}`,assignee:x.requestedBy.name,site:x.site.name,completed:!openStatus(x.status)})));
  items.push(...exposureGroups.map(x=>item({id:`exposure-group:${x.id}`,source:"INDUSTRIAL_HYGIENE",sourceLabel:"Exposure Group Review",title:`${x.name} review`,detail:"Similar Exposure Group review",date:x.reviewDueDate!,status:x.isActive?"ACTIVE":"INACTIVE",href:"/industrial-hygiene",assignee:x.owner?.name||"Unassigned",site:x.site.name,completed:!x.isActive})));
  items.push(...exposureAssessments.map(x=>item({id:`exposure-assessment:${x.id}`,source:"INDUSTRIAL_HYGIENE",sourceLabel:"Exposure Assessment",title:`${x.reference} — ${x.title}`,detail:x.group.name,date:x.dueDate!,status:x.status,href:`/industrial-hygiene/${x.id}`,assignee:x.assessor?.name||"Unassigned",site:x.site.name,completed:!openStatus(x.status)})));
  items.push(...surveillance.map(x=>item({id:`surveillance:${x.id}`,source:"OCCUPATIONAL_HEALTH",sourceLabel:"Occupational Health",title:`${x.program.name} milestone`,detail:"Restricted surveillance milestone",date:x.nextDueAt,status:x.status,href:`/occupational-health/${x.programId}`,assignee:x.user.name,site:null,completed:!openStatus(x.status)})));
  items.push(...risks.map(x=>item({id:`risk:${x.id}`,source:"RISK_REVIEW",sourceLabel:"Risk Review",title:`${x.reference} — ${x.title}`,detail:`${x.currentRiskLevel} risk`,date:x.nextReviewDate!,status:x.status,href:`/risks/${x.id}`,assignee:x.owner?.name||"Unassigned",site:x.site?.name||null,completed:false})));
  items.push(...mocTasks.map(x=>item({id:`moc:${x.id}`,source:"MOC",sourceLabel:"MOC Task",title:x.title,detail:`${x.moc.reference} — ${x.moc.title}`,date:x.dueDate!,status:x.status,href:`/moc/${x.mocId}`,assignee:x.assignedTo?.name||"Unassigned",site:null,completed:!openStatus(x.status)})));
  items.push(...workflowSteps.map(x=>item({id:`workflow:${x.id}`,source:"WORKFLOW",sourceLabel:"Workflow",title:x.name,detail:x.instance.template.name,date:x.dueAt!,status:x.status,href:"/tasks",assignee:x.assignedUser?.name||x.assignedRole?.replaceAll("_"," ")||"Available role task",site:null,completed:!openStatus(x.status)})));
  return items.sort((a,b)=>a.date.getTime()-b.date.getTime());
}
