"use client";
import{useActionState}from"react";
import{initialFormActionState,type FormActionState}from"@/core/actions/action-state";
import{recordClientReviewDecision,submitClientReviewRequest}from"@/features/research/client-review-actions";
import{useRefreshOnSuccess}from"@/features/research/use-refresh-on-success";
const input="mt-2 w-full rounded-xl border border-white/10 bg-slate-950/80 px-4 py-3 text-sm";
function Feedback({state}:{state:FormActionState}){return state.status==="IDLE"?null:<p role="status" className={`mt-3 text-sm ${state.status==="ERROR"?"text-red-300":"text-emerald-300"}`}>{state.message}</p>}
export function ClientReviewRequestForm({projectId,artifacts}:{projectId:string;artifacts:Array<{id:string;type:string;title:string}>}){const[state,action,pending]=useActionState(submitClientReviewRequest,initialFormActionState);useRefreshOnSuccess(state);return <form action={action} className="rounded-3xl border border-white/10 bg-white/[.04] p-6"><input type="hidden" name="projectId" value={projectId}/><h2 className="text-xl font-semibold">Submit approved artifact to client</h2><select name="artifact" required className={input} onChange={event=>{const[type,id]=event.currentTarget.value.split(":");const form=event.currentTarget.form;if(form){(form.elements.namedItem("artifactType")as HTMLInputElement).value=type;(form.elements.namedItem("artifactId")as HTMLInputElement).value=id}}}><option value="">Select eligible artifact</option>{artifacts.map(item=><option key={`${item.type}:${item.id}`} value={`${item.type}:${item.id}`}>{item.type.replaceAll("_"," ")} — {item.title}</option>)}</select><input type="hidden" name="artifactType"/><input type="hidden" name="artifactId"/><label className="mt-4 block text-sm">Review due date<input name="dueAt" type="date" className={input}/></label><label className="mt-4 block text-sm">Instructions<textarea name="instructions" rows={3} maxLength={4000} className={input}/></label><button disabled={pending||!artifacts.length} className="mt-5 rounded-xl bg-cyan-300 px-5 py-3 font-semibold text-slate-950 disabled:opacity-50">{pending?"Submitting…":"Request client review"}</button><Feedback state={state}/></form>}
export function ClientReviewDecisionForm({projectId,requestId,status}:{projectId:string;requestId:string;status:string}){const[state,action,pending]=useActionState(recordClientReviewDecision,initialFormActionState);useRefreshOnSuccess(state);return <form action={action} className="mt-4 border-t border-white/10 pt-4"><input type="hidden" name="projectId" value={projectId}/><input type="hidden" name="requestId" value={requestId}/><textarea name="comment" required minLength={2} maxLength={4000} rows={3} placeholder="Add your review comment or decision rationale" className={input}/><div className="mt-3 flex flex-wrap gap-2"><button name="decision" value="COMMENT" disabled={pending} className="rounded-lg border border-white/15 px-3 py-2 text-xs">Comment</button>{status==="PENDING_REVIEW"&&<><button name="decision" value="REQUEST_REVISION" disabled={pending} className="rounded-lg border border-amber-300/20 px-3 py-2 text-xs text-amber-200">Request revision</button><button name="decision" value="APPROVE" disabled={pending} className="rounded-lg border border-emerald-300/20 px-3 py-2 text-xs text-emerald-200">Approve</button></>}{status==="APPROVED"&&<button name="decision" value="ACCEPT" disabled={pending} className="rounded-lg bg-emerald-300 px-3 py-2 text-xs font-semibold text-slate-950">Final acceptance</button>}</div><Feedback state={state}/></form>}
