"use client";

import { initialFormActionState,type FormActionState } from "@/core/actions/action-state";
import { RuntimeFormFields } from "@/features/forms/runtime-form-fields";
import { assignQuestionnaireRespondent,changeCollectionStatus,createCollectionWave,submitResearchResponse,updateCollectionLocationPolicy } from "@/features/research/collection-actions";
import { ResearchCollectionStatus, ResearchLocationCapturePolicy } from "@prisma/client";
import { useActionState } from "react";
import { useRefreshOnSuccess } from "@/features/research/use-refresh-on-success";

const input="mt-2 w-full rounded-xl border border-white/10 bg-slate-950/80 px-4 py-3 text-sm text-white";const button="rounded-xl bg-cyan-300 px-5 py-3 text-sm font-semibold text-slate-950 disabled:opacity-50";
function Feedback({state}:{state:FormActionState}){useRefreshOnSuccess(state);return state.message?<p role={state.status==="ERROR"?"alert":"status"} className={`mt-4 rounded-xl border p-3 text-sm ${state.status==="ERROR"?"border-red-400/20 bg-red-400/10 text-red-300":"border-emerald-400/20 bg-emerald-400/10 text-emerald-300"}`}>{state.message}</p>:null}
export function CollectionWaveForm({projectId,questionnaireId}:{projectId:string;questionnaireId:string}){const[state,action,pending]=useActionState(createCollectionWave,initialFormActionState);return <form action={action} className="rounded-3xl border border-white/10 bg-white/[.04] p-6"><input type="hidden" name="projectId" value={projectId}/><input type="hidden" name="questionnaireId" value={questionnaireId}/><h2 className="text-xl font-semibold">Create collection wave</h2><div className="mt-4 grid gap-4 md:grid-cols-2"><Label text="Wave name"><input name="name" required maxLength={160} className={input}/></Label><Label text="Target responses"><input name="targetResponseCount" type="number" min={1} className={input}/></Label><Label text="Opens"><input name="opensAt" type="datetime-local" className={input}/></Label><Label text="Closes"><input name="closesAt" type="datetime-local" className={input}/></Label><Label text="Default assignment due"><input name="dueAt" type="datetime-local" className={input}/></Label></div><Label text="Enumerator/respondent instructions"><textarea name="instructions" rows={4} maxLength={3000} className={input}/></Label><button disabled={pending} className={`mt-5 ${button}`}>{pending?"Creating…":"Create governed wave"}</button><Feedback state={state}/></form>}
export function RespondentAssignmentForm({collectionId,users}:{collectionId:string;users:Array<{id:string;name:string;email:string}>}){const[state,action,pending]=useActionState(assignQuestionnaireRespondent,initialFormActionState);return <form action={action} className="rounded-3xl border border-white/10 bg-white/[.04] p-6"><input type="hidden" name="collectionId" value={collectionId}/><h2 className="text-xl font-semibold">Assign respondent or enumerator</h2><Label text="Tenant user"><select name="respondentId" required defaultValue="" className={input}><option value="" disabled>Select user</option>{users.map(user=><option key={user.id} value={user.id}>{user.name} — {user.email}</option>)}</select></Label><Label text="Individual due date"><input name="dueAt" type="datetime-local" className={input}/></Label><button disabled={pending} className={`mt-5 ${button}`}>{pending?"Assigning…":"Assign and notify"}</button><Feedback state={state}/></form>}
export function CollectionStatusForm({collectionId,status}:{collectionId:string;status:ResearchCollectionStatus}){const[state,action,pending]=useActionState(changeCollectionStatus,initialFormActionState);const options:Record<ResearchCollectionStatus,ResearchCollectionStatus[]>={DRAFT:[ResearchCollectionStatus.ACTIVE,ResearchCollectionStatus.CANCELLED],ACTIVE:[ResearchCollectionStatus.PAUSED,ResearchCollectionStatus.CLOSED],PAUSED:[ResearchCollectionStatus.ACTIVE,ResearchCollectionStatus.CLOSED,ResearchCollectionStatus.CANCELLED],CLOSED:[],CANCELLED:[]};if(!options[status].length)return null;return <form action={action} className="flex flex-wrap items-end gap-3"><input type="hidden" name="collectionId" value={collectionId}/><Label text="Collection status"><select name="status" className={input}>{options[status].map(value=><option key={value}>{value}</option>)}</select></Label><button disabled={pending} className={button}>{pending?"Updating…":"Update status"}</button><Feedback state={state}/></form>}
export function CollectionLocationPolicyForm({collection}:{collection:{id:string;locationCapturePolicy:ResearchLocationCapturePolicy;maximumLocationAccuracyM:number|null;retainPreciseLocation:boolean}}){const[state,action,pending]=useActionState(updateCollectionLocationPolicy,initialFormActionState);return <form action={action} className="rounded-3xl border border-cyan-400/15 bg-cyan-400/[.035] p-6"><input type="hidden" name="collectionId" value={collection.id}/><h2 className="text-xl font-semibold">Field location governance</h2><p className="mt-2 text-sm text-slate-400">Coordinates require separate participant consent. Unless precise retention is justified, synchronized coordinates are reduced to approximately 110-metre precision.</p><div className="mt-4 grid gap-4 md:grid-cols-2"><Label text="Capture policy"><select name="locationCapturePolicy" defaultValue={collection.locationCapturePolicy} className={input}>{Object.values(ResearchLocationCapturePolicy).map(policy=><option key={policy}>{policy}</option>)}</select></Label><Label text="Maximum accepted accuracy (metres)"><input name="maximumLocationAccuracyM" type="number" min={5} max={10000} defaultValue={collection.maximumLocationAccuracyM??""} className={input}/></Label></div><label className="mt-4 flex items-start gap-3 text-sm text-slate-300"><input name="retainPreciseLocation" type="checkbox" defaultChecked={collection.retainPreciseLocation} className="mt-1"/><span><strong>Retain precise coordinates</strong><span className="mt-1 block text-xs text-slate-500">Enable only where the research purpose, consent language and privacy assessment justify exact location retention.</span></span></label><button disabled={pending} className={`mt-5 ${button}`}>{pending?"Saving…":"Save location policy"}</button><Feedback state={state}/></form>}
export function ResearchResponseForm({assignmentId,consentStatement,form}:{assignmentId:string;consentStatement:string|null;form:Parameters<typeof RuntimeFormFields>[0]["forms"][number]}){const[state,action,pending]=useActionState(submitResearchResponse,initialFormActionState);return <form action={action} className="space-y-5"><input type="hidden" name="assignmentId" value={assignmentId}/>{consentStatement&&<label className="block rounded-2xl border border-amber-400/20 bg-amber-400/[.06] p-5 text-sm text-slate-300"><span className="block font-semibold text-amber-200">Participant consent</span><span className="mt-2 block whitespace-pre-wrap">{consentStatement}</span><span className="mt-4 flex items-center gap-3"><input type="checkbox" name="participantConsent" required/> I have read this statement and consent to participate.</span></label>}<RuntimeFormFields forms={[form]}/><Feedback state={state}/><button disabled={pending} className={button}>{pending?"Submitting securely…":"Submit final response"}</button><p className="text-xs text-slate-500">Submission is final and is recorded against this published questionnaire version.</p></form>}
function Label({text,children}:{text:string;children:React.ReactNode}){return <label className="block text-sm text-slate-300"><span>{text}</span>{children}</label>}
