"use client";
import { Bar,BarChart,CartesianGrid,ResponsiveContainer,Tooltip,XAxis,YAxis } from "recharts";
import type{ResearchQualityProfile}from"@/modules/research/research-quality-profile";

export function ResearchDataQualityWorkbench({profile,versionId,canExport}:{profile:ResearchQualityProfile;versionId:string;canExport:boolean}){
  const chart=profile.variables.map((item)=>({name:item.label.length>18?`${item.label.slice(0,18)}…`:item.label,completeness:Number(item.completeness.toFixed(1))}));
  return <section className="mt-9 rounded-3xl border border-cyan-400/20 bg-cyan-400/[.03] p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-cyan-300">Data quality intelligence</p><h2 className="mt-1 text-2xl font-semibold">Quality & Readiness Workbench</h2><p className="mt-1 text-sm text-slate-400">Transparent diagnostics support analyst review; they never alter the approved immutable version.</p></div>{canExport&&<a href={`/api/research/imports/versions/${versionId}/quality-workbook`} className="rounded-xl border border-emerald-400/25 px-4 py-2 text-sm text-emerald-300">Export quality workbook</a>}</div><div className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Metric label="Readiness score" value={`${profile.readinessScore}%`}/><Metric label="Rows" value={profile.rowCount}/><Metric label="Variables" value={profile.variableCount}/><Metric label="Missing cells" value={profile.missingCells}/><Metric label="Duplicate rows" value={profile.duplicateRows}/></div><div className="mt-6 h-72"><ResponsiveContainer width="100%" height="100%"><BarChart data={chart}><CartesianGrid stroke="#1e293b"/><XAxis dataKey="name" stroke="#94a3b8" interval={0} angle={-20} textAnchor="end" height={70}/><YAxis domain={[0,100]} stroke="#94a3b8"/><Tooltip/><Bar dataKey="completeness" fill="#22d3ee" radius={[6,6,0,0]}/></BarChart></ResponsiveContainer></div><div className="mt-6 overflow-x-auto"><table className="w-full text-left text-sm"><thead className="text-xs text-slate-500"><tr><th className="p-3">Variable</th><th className="p-3">Type</th><th className="p-3">Complete</th><th className="p-3">Unique</th><th className="p-3">Mean / range</th><th className="p-3">Flags</th></tr></thead><tbody>{profile.variables.map((item)=><tr key={item.key} className="border-t border-white/10"><td className="p-3 font-medium">{item.label}<span className="block text-xs text-slate-600">{item.key}</span></td><td className="p-3 text-cyan-200">{item.type}</td><td className="p-3">{item.completeness.toFixed(1)}%</td><td className="p-3">{item.unique}</td><td className="p-3">{item.mean===null?"—":`${fmt(item.mean)} · ${fmt(item.minimum)}–${fmt(item.maximum)}`}</td><td className="p-3 text-amber-300">{[item.missing?`${item.missing} missing`:"",item.outliers?`${item.outliers} outliers`:"",item.constant?"constant":""].filter(Boolean).join(" · ")||"None"}</td></tr>)}</tbody></table></div>{profile.missingnessPairs.length>0&&<div className="mt-6 rounded-2xl border border-white/10 p-5"><h3 className="font-semibold">Top co-missing variable pairs</h3><div className="mt-3 grid gap-2 md:grid-cols-2">{profile.missingnessPairs.slice(0,10).map((pair)=><p key={`${pair.first}:${pair.second}`} className="rounded-xl bg-slate-950/40 p-3 text-sm"><span className="text-slate-300">{pair.first} + {pair.second}</span><strong className="float-right text-amber-300">{pair.count}</strong></p>)}</div></div>}</section>
}
function Metric({label,value}:{label:string;value:string|number}){return <div className="rounded-2xl border border-white/10 bg-slate-950/40 p-4"><p className="text-xs text-slate-500">{label}</p><p className="mt-2 text-xl font-bold">{value}</p></div>}
const fmt=(value:number|null)=>value===null?"—":Number(value.toFixed(3));
