import Link from"next/link";
import{notFound}from"next/navigation";
import{PermissionKey}from"@prisma/client";
import{requirePermission}from"@/lib/permissions";
import{getCurrentUserTenant}from"@/lib/tenant";
import{prisma}from"@/lib/prisma";
import{listEligibleClientReviewArtifacts,listProjectClientReviews}from"@/modules/research/research-client-review.service";
import{ClientReviewRequestForm}from"@/features/research/client-review-forms";
export const dynamic="force-dynamic";
export default async function ProjectClientReviewPage({params}:{params:Promise<{id:string}>}){await requirePermission(PermissionKey.MANAGE_RESEARCH_PROJECTS);const[{id},{organizationId}]=await Promise.all([params,getCurrentUserTenant()]);const project=await prisma.researchProject.findFirst({where:{id,organizationId},include:{client:true}});if(!project)notFound();let artifacts:Array<{id:string;type:string;title:string}>=[];if(project.clientId)artifacts=await listEligibleClientReviewArtifacts(organizationId,id);const reviews=await listProjectClientReviews(organizationId,id);return <div><Link href={`/research/projects/${id}`} className="text-sm text-slate-400">← Research project</Link><p className="mt-6 text-sm text-cyan-300">Governed Client Review</p><h1 className="mt-2 text-4xl font-bold">{project.title}</h1><p className="mt-2 text-slate-400">{project.client?.name??"Internal research"} · Submit only internally approved or published artifacts.</p>{project.clientId?<div className="mt-8"><ClientReviewRequestForm projectId={id} artifacts={artifacts}/></div>:<p className="mt-8 rounded-2xl border border-amber-300/20 bg-amber-300/5 p-5 text-amber-200">Assign a commissioning client before opening client review.</p>}<section className="mt-8 rounded-3xl border border-white/10 bg-white/[.035] p-6"><h2 className="text-xl font-semibold">Review register</h2><div className="mt-5 space-y-4">{reviews.map(review=><article key={review.id} className="rounded-2xl border border-white/10 bg-slate-950/40 p-5"><div className="flex flex-wrap justify-between gap-4"><div><p className="text-xs text-cyan-300">{review.artifactType.replaceAll("_"," ")}</p><h3 className="mt-1 font-semibold">{review.artifactTitle}</h3><p className="mt-1 text-xs text-slate-500">Requested by {review.requestedBy.name} · due {review.dueAt?.toLocaleDateString()??"not set"}</p></div><span className="h-fit rounded-full bg-white/5 px-3 py-1 text-xs">{review.status.replaceAll("_"," ")}</span></div>{review.instructions&&<p className="mt-4 text-sm text-slate-300">{review.instructions}</p>}<div className="mt-4 space-y-2">{review.comments.map(comment=><p key={comment.id} className="rounded-lg bg-white/[.035] p-3 text-sm"><strong>{comment.user.name}</strong><span className="ml-2 text-xs text-slate-500">{comment.createdAt.toLocaleString()}</span><span className="mt-1 block text-slate-300">{comment.body}</span></p>)}</div></article>)}{!reviews.length?<p className="text-sm text-slate-500">No artifacts have been submitted for client review.</p>:null}</div></section></div>}
