import assert from"node:assert/strict";
import test from"node:test";
import{readFile}from"node:fs/promises";
import{normalizeDashboardBranding,normalizeDashboardLayout}from"../src/modules/research/research-dashboard";
import{createResearchDashboardPdf,createResearchDashboardPng,createResearchDashboardSvg}from"../src/modules/research/research-dashboard-export";

test("dashboard layouts retain only authorized analyses and bounded annotations",()=>{const allowed=new Set(["analysis-1"]),layout=normalizeDashboardLayout({columns:2,widgets:[{analysisId:"analysis-1",title:"Outcome",width:"FULL",annotation:"A".repeat(1200),referenceLine:75},{analysisId:"other-tenant",title:"Unsafe"}]},allowed);assert.equal(layout.widgets.length,1);assert.equal(layout.widgets[0].analysisId,"analysis-1");assert.equal(layout.widgets[0].annotation?.length,1000);assert.equal(layout.widgets[0].referenceLine,75)});

test("dashboard branding accepts hex colors and falls back safely",()=>{assert.deepEqual(normalizeDashboardBranding({brandName:"Client A",primaryColor:"#123abc",accentColor:"javascript:bad",footerText:"Confidential"},"Project"),{brandName:"Client A",primaryColor:"#123ABC",accentColor:"#A78BFA",footerText:"Confidential"})});

test("dashboard persistence is tenant-scoped, audited, and independently approved",async()=>{const[action,schema,migration,page]=await Promise.all([readFile(new URL("../src/features/research/dashboard-actions.ts",import.meta.url),"utf8"),readFile(new URL("../prisma/schema.prisma",import.meta.url),"utf8"),readFile(new URL("../prisma/migrations/20260910210000_research_visualization_dashboards/migration.sql",import.meta.url),"utf8"),readFile(new URL("../src/app/(platform)/research/projects/[id]/dashboards/page.tsx",import.meta.url),"utf8")]);assert.match(action,/organizationId/);assert.match(action,/logActivity/);assert.match(action,/createdById===user\.id/);assert.match(action,/APPROVE_RESEARCH_OUTPUTS/);assert.match(schema,/model ResearchVisualizationDashboard/);assert.match(migration,/ResearchVisualizationDashboard/);assert.match(page,/ResearchDashboardBuilder/)});

test("approved dashboard exports produce escaped SVG, PNG, and valid PDF containers",async()=>{const svg=createResearchDashboardSvg({title:"Results <Final>",description:"Client & board",status:"APPROVED",layout:{columns:1,widgets:[{analysisId:"a1",title:"Performance",width:"FULL",annotation:"Reviewed",referenceLine:75}]},branding:{brandName:"Client",primaryColor:"#22D3EE",accentColor:"#A78BFA",footerText:"Confidential"},analyses:[{id:"a1",title:"Performance",method:"DISTRIBUTION",status:"APPROVED",datasetResponseCount:20,resultSnapshot:{summary:{mean:81.25}}}],generatedAt:"2026-09-10T00:00:00.000Z"});assert.match(svg,/Results &lt;Final&gt;/);assert.doesNotMatch(svg,/Results <Final>/);const png=await createResearchDashboardPng(svg),pdf=await createResearchDashboardPdf(svg);assert.deepEqual([...png.subarray(0,8)],[137,80,78,71,13,10,26,10]);assert.equal(pdf.subarray(0,8).toString("binary"),"%PDF-1.4");assert.match(pdf.subarray(-200).toString(),/%%EOF/)});

test("publication export route requires tenant permission and approved dashboard evidence",async()=>{const route=await readFile(new URL("../src/app/api/research/dashboards/[dashboardId]/export/route.ts",import.meta.url),"utf8");assert.match(route,/EXPORT_RESEARCH_OUTPUTS/);assert.match(route,/organizationId/);assert.match(route,/ResearchDashboardStatus\.APPROVED/);assert.match(route,/status:\s*"APPROVED"/);assert.match(route,/private, no-store/)});
