import type { ResearchDataRow, ResearchVariable } from "@/modules/research/research-analysis";

const mean=(v:number[])=>v.reduce((a,b)=>a+b,0)/v.length;
const variance=(v:number[])=>v.length>1?v.reduce((s,x)=>s+(x-mean(v))**2,0)/(v.length-1):0;
const transpose=(m:number[][])=>m[0].map((_,i)=>m.map(r=>r[i]));
const multiply=(a:number[][],b:number[][])=>a.map(r=>transpose(b).map(c=>r.reduce((s,v,i)=>s+v*c[i],0)));
function inverse(matrix:number[][]){const n=matrix.length,a=matrix.map((row,i)=>[...row,...Array.from({length:n},(_,j)=>i===j?1:0)]);for(let c=0;c<n;c++){let pivot=c;for(let r=c+1;r<n;r++)if(Math.abs(a[r][c])>Math.abs(a[pivot][c]))pivot=r;[a[c],a[pivot]]=[a[pivot],a[c]];if(Math.abs(a[c][c])<1e-10)return null;const divisor=a[c][c];a[c]=a[c].map(v=>v/divisor);for(let r=0;r<n;r++)if(r!==c){const factor=a[r][c];a[r]=a[r].map((v,j)=>v-factor*a[c][j])}}return a.map(row=>row.slice(n));}
const completeRows=(rows:ResearchDataRow[],predictors:ResearchVariable[],outcome:ResearchVariable)=>rows.flatMap(row=>{const x=predictors.map(v=>row.values[v.key]),y=row.values[outcome.key];return x.every(v=>typeof v==="number"&&Number.isFinite(v))&&typeof y==="number"&&Number.isFinite(y)?[{x:x as number[],y}]:[]});

export function multipleLinearRegression(rows:ResearchDataRow[],predictors:ResearchVariable[],outcome:ResearchVariable){const data=completeRows(rows,predictors,outcome);if(!predictors.length||data.length<=predictors.length+1)return null;const design=data.map(row=>[1,...row.x]),target=data.map(row=>[row.y]),xt=transpose(design),information=multiply(xt,design),informationInverse=inverse(information);if(!informationInverse)return null;const coefficients=multiply(multiply(informationInverse,xt),target).map(row=>row[0]),predicted=design.map(row=>row.reduce((s,v,i)=>s+v*coefficients[i],0)),average=mean(data.map(row=>row.y)),residualSum=data.reduce((s,row,i)=>s+(row.y-predicted[i])**2,0),totalSum=data.reduce((s,row)=>s+(row.y-average)**2,0),rSquared=totalSum?1-residualSum/totalSum:1,df=data.length-predictors.length-1,mse=residualSum/df;const terms=["Intercept",...predictors.map(v=>v.label)].map((term,i)=>({term,coefficient:coefficients[i],standardError:Math.sqrt(Math.max(0,mse*informationInverse[i][i])),vif:i?varianceInflation(data.map(row=>row.x),i-1):null}));return{n:data.length,rSquared,adjustedRSquared:1-(1-rSquared)*(data.length-1)/df,rootMeanSquareError:Math.sqrt(mse),terms,diagnostics:data.map((row,i)=>({observed:row.y,predicted:predicted[i],residual:row.y-predicted[i]}))};}
function varianceInflation(matrix:number[][],index:number){const target=matrix.map(row=>row[index]),indices=matrix[0].map((_,i)=>i).filter(i=>i!==index);if(!indices.length)return 1;const design=matrix.map(row=>[1,...indices.map(i=>row[i])]),xt=transpose(design),inv=inverse(multiply(xt,design));if(!inv)return null;const beta=multiply(multiply(inv,xt),target.map(v=>[v])).map(row=>row[0]),predicted=design.map(row=>row.reduce((s,v,i)=>s+v*beta[i],0)),average=mean(target),total=target.reduce((s,v)=>s+(v-average)**2,0),residual=target.reduce((s,v,i)=>s+(v-predicted[i])**2,0),rSquared=total?1-residual/total:1;return rSquared<.999999?1/(1-rSquared):null;}

export function cronbachAlpha(rows:ResearchDataRow[],items:ResearchVariable[]){const complete=rows.flatMap(row=>{const values=items.map(item=>row.values[item.key]);return values.every(value=>typeof value==="number"&&Number.isFinite(value))?[values as number[]]:[]});if(items.length<2||complete.length<2)return null;const itemVariance=items.map((_,i)=>variance(complete.map(row=>row[i]))).reduce((a,b)=>a+b,0),totals=complete.map(row=>row.reduce((a,b)=>a+b,0)),totalVariance=variance(totals);if(!totalVariance)return null;const alpha=items.length/(items.length-1)*(1-itemVariance/totalVariance);return{alpha,n:complete.length,itemCount:items.length,itemStatistics:items.map((item,i)=>({item:item.label,mean:mean(complete.map(row=>row[i])),standardDeviation:Math.sqrt(variance(complete.map(row=>row[i])))}))};}

export function logisticRegression(rows:ResearchDataRow[],predictors:ResearchVariable[],outcome:ResearchVariable){const raw=rows.flatMap(row=>{const x=predictors.map(v=>row.values[v.key]),y=row.values[outcome.key];return x.every(v=>typeof v==="number")&&y!==null&&y!==""?[{x:x as number[],label:String(y)}]:[]}),labels=[...new Set(raw.map(row=>row.label))];if(!predictors.length||labels.length!==2||raw.length<predictors.length+5)return null;const data=raw.map(row=>({x:[1,...row.x],y:row.label===labels[1]?1:0}));let beta=Array(predictors.length+1).fill(0);for(let iteration=0;iteration<30;iteration++){const probabilities=data.map(row=>{const linear=row.x.reduce((sum,value,index)=>sum+value*beta[index],0);return 1/(1+Math.exp(-Math.max(-30,Math.min(30,linear))))}),weights=probabilities.map(p=>Math.max(1e-6,p*(1-p))),design=data.map(row=>row.x),xt=transpose(design),weighted=design.map((row,i)=>row.map(v=>v*weights[i])),informationInverse=inverse(multiply(xt,weighted));if(!informationInverse)return null;const score=multiply(xt,data.map((row,i)=>[row.y-probabilities[i]])).map(row=>row[0]),step=multiply(informationInverse,score.map(v=>[v])).map(row=>row[0]);beta=beta.map((v,i)=>v+step[i]);if(Math.max(...step.map(Math.abs))<1e-7)break}const predicted=data.map(row=>1/(1+Math.exp(-row.x.reduce((s,v,i)=>s+v*beta[i],0)))),accuracy=predicted.filter((p,i)=>(p>=.5?1:0)===data[i].y).length/data.length;return{n:data.length,outcomeLabels:labels,accuracy,terms:["Intercept",...predictors.map(v=>v.label)].map((term,i)=>({term,coefficient:beta[i],oddsRatio:Math.exp(beta[i])})),diagnostics:predicted.map((probability,i)=>({probability,observed:data[i].y}))};}
