export type ResearchValue=string|number|boolean|string[]|null;
export type ResearchVariable={id:string;key:string;label:string;type:string;required:boolean};
export type ResearchDataRow={assignmentId:string;responseId:string;submittedAt:string;values:Record<string,ResearchValue>};

const numeric=(values:ResearchValue[])=>values.filter((value):value is number=>typeof value==="number"&&Number.isFinite(value)).sort((a,b)=>a-b);
const quantile=(values:number[],p:number)=>{if(!values.length)return null;const index=(values.length-1)*p,lower=Math.floor(index),upper=Math.ceil(index);return lower===upper?values[lower]:values[lower]+(values[upper]-values[lower])*(index-lower)};
export function summarizeVariable(variable:ResearchVariable,rows:ResearchDataRow[]){const values=rows.map(row=>row.values[variable.key]??null),present=values.filter(value=>value!==null&&value!==""&&(!Array.isArray(value)||value.length));const numbers=numeric(values);const counts=new Map<string,number>();for(const value of present){const keys=Array.isArray(value)?value.map(String):[String(value)];for(const key of keys)counts.set(key,(counts.get(key)??0)+1)}const mean=numbers.length?numbers.reduce((sum,value)=>sum+value,0)/numbers.length:null;const variance=numbers.length>1?numbers.reduce((sum,value)=>sum+(value-(mean??0))**2,0)/(numbers.length-1):null;return{key:variable.key,label:variable.label,type:variable.type,total:rows.length,present:present.length,missing:rows.length-present.length,unique:counts.size,min:numbers[0]??null,max:numbers.at(-1)??null,mean,median:quantile(numbers,.5),standardDeviation:variance===null?null:Math.sqrt(variance),q1:quantile(numbers,.25),q3:quantile(numbers,.75),frequencies:[...counts].sort((a,b)=>b[1]-a[1]).map(([value,count])=>({value,count,percent:present.length?count/present.length*100:0}))};}
export function detectQualityIssues(variables:ResearchVariable[],rows:ResearchDataRow[]){const issues=new Map<string,string[]>(),fingerprints=new Map<string,string>();for(const row of rows){for(const variable of variables){const value=row.values[variable.key];if(variable.required&&(value===null||value===""||(Array.isArray(value)&&!value.length)))issues.set(row.assignmentId,[...(issues.get(row.assignmentId)??[]),`Missing required value: ${variable.label}`])}const fingerprint=JSON.stringify(variables.map(variable=>row.values[variable.key]??null));const first=fingerprints.get(fingerprint);if(first){issues.set(row.assignmentId,[...(issues.get(row.assignmentId)??[]),`Possible duplicate of response ${first.slice(-8)}`])}else fingerprints.set(fingerprint,row.assignmentId)}for(const variable of variables.filter(item=>item.type==="NUMBER")){const values=numeric(rows.map(row=>row.values[variable.key]??null)),q1=quantile(values,.25),q3=quantile(values,.75);if(q1===null||q3===null||values.length<4)continue;const low=q1-1.5*(q3-q1),high=q3+1.5*(q3-q1);for(const row of rows){const value=row.values[variable.key];if(typeof value==="number"&&(value<low||value>high))issues.set(row.assignmentId,[...(issues.get(row.assignmentId)??[]),`Potential outlier: ${variable.label}`])}}return issues;}
export function buildChartData(rows:ResearchDataRow[],x:ResearchVariable,y?:ResearchVariable|null){if(x.type==="NUMBER"&&y?.type==="NUMBER")return rows.flatMap(row=>{const xv=row.values[x.key],yv=row.values[y.key];return typeof xv==="number"&&typeof yv==="number"?[{x:xv,y:yv}]:[]});if(y?.type==="NUMBER"){const groups=new Map<string,number[]>();for(const row of rows){const category=String(row.values[x.key]??"Missing"),value=row.values[y.key];if(typeof value==="number")groups.set(category,[...(groups.get(category)??[]),value])}return[...groups].map(([name,values])=>({name,value:values.reduce((a,b)=>a+b,0)/values.length,count:values.length}))}return summarizeVariable(x,rows).frequencies.map(item=>({name:item.value,value:item.count,percent:item.percent}));}
