import{deflateSync}from"node:zlib";
import sharp from"sharp";
import type{ResearchDashboardBranding,ResearchDashboardLayout}from"@/modules/research/research-dashboard";

export type DashboardExportAnalysis={id:string;title:string;method:string;status:string;datasetResponseCount:number;resultSnapshot:unknown};
const xml=(value:unknown)=>String(value??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&apos;");
const metrics=(value:unknown,path=""):Array<{label:string;value:string}>=>{if(typeof value==="number"&&Number.isFinite(value))return[{label:path||"Value",value:Math.abs(value)<.001&&value!==0?value.toExponential(2):String(Number(value.toFixed(3)))}];if(typeof value==="string"||typeof value==="boolean")return[{label:path||"Value",value:String(value)}];if(!value||typeof value!=="object")return[];return(Array.isArray(value)?value.map((item,index)=>[String(index),item]as const):Object.entries(value)).flatMap(([key,item])=>metrics(item,path?`${path} · ${key}`:key)).slice(0,6)};

export function createResearchDashboardSvg({title,description,status,layout,branding,analyses,generatedAt}:{title:string;description?:string|null;status:string;layout:ResearchDashboardLayout;branding:ResearchDashboardBranding;analyses:DashboardExportAnalysis[];generatedAt:string}){
  const width=1600,columns=layout.columns,rowHeight=330,gap=28,margin=72,contentWidth=width-margin*2,columnWidth=(contentWidth-gap*(columns-1))/columns;
  let row=0,column=0;const cards=layout.widgets.map(widget=>{const analysis=analyses.find(item=>item.id===widget.analysisId),span=columns===1||widget.width==="FULL"?columns:1;if(column+span>columns){row++;column=0}const x=margin+column*(columnWidth+gap),y=260+row*(rowHeight+gap),w=span===columns?contentWidth:columnWidth;column+=span;if(column>=columns){row++;column=0}const items=metrics(analysis?.resultSnapshot).slice(0,4);return`<g><rect x="${x}" y="${y}" width="${w}" height="${rowHeight}" rx="24" fill="#0F1D2E" stroke="#294158"/><rect x="${x}" y="${y}" width="8" height="${rowHeight}" rx="4" fill="${branding.accentColor}"/><text x="${x+32}" y="${y+48}" class="widget">${xml(widget.title)}</text><text x="${x+32}" y="${y+78}" class="meta">${xml(analysis?.method.replaceAll("_"," ")??"Unavailable analysis")} · N ${analysis?.datasetResponseCount??0}</text>${items.map((item,index)=>`<text x="${x+32+(index%2)*(w/2-30)}" y="${y+132+Math.floor(index/2)*68}" class="label">${xml(item.label.slice(0,40))}</text><text x="${x+32+(index%2)*(w/2-30)}" y="${y+158+Math.floor(index/2)*68}" class="value">${xml(item.value)}</text>`).join("")}${widget.referenceLine!==undefined?`<line x1="${x+32}" y1="${y+272}" x2="${x+w-32}" y2="${y+272}" stroke="#FBBF24" stroke-width="2" stroke-dasharray="8 7"/><text x="${x+32}" y="${y+300}" class="reference">Reference ${xml(widget.referenceLine)}</text>`:""}${widget.annotation?`<text x="${x+w-32}" y="${y+300}" text-anchor="end" class="annotation">${xml(widget.annotation.slice(0,90))}</text>`:""}</g>`});
  const totalRows=Math.max(1,row+(column>0?1:0)),height=260+totalRows*(rowHeight+gap)+100;return`<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}" role="img" aria-label="${xml(title)}"><rect width="100%" height="100%" fill="#07111F"/><defs><linearGradient id="brand" x1="0" x2="1"><stop stop-color="${branding.primaryColor}"/><stop offset="1" stop-color="${branding.accentColor}"/></linearGradient><style>text{font-family:Inter,Aptos,Arial,sans-serif}.eyebrow{font-size:17px;font-weight:700;letter-spacing:3px;fill:${branding.primaryColor}}.title{font-size:44px;font-weight:700;fill:#F8FAFC}.subtitle{font-size:19px;fill:#94A3B8}.widget{font-size:23px;font-weight:700;fill:#F8FAFC}.meta,.label{font-size:14px;fill:#94A3B8}.value{font-size:24px;font-weight:700;fill:#E2E8F0}.reference{font-size:13px;fill:#FBBF24}.annotation{font-size:13px;fill:#CBD5E1}.footer{font-size:13px;fill:#64748B}</style></defs><rect x="0" y="0" width="100%" height="10" fill="url(#brand)"/><text x="${margin}" y="72" class="eyebrow">${xml(branding.brandName.toUpperCase())} · ${xml(status.replaceAll("_"," "))}</text><text x="${margin}" y="128" class="title">${xml(title)}</text><text x="${margin}" y="170" class="subtitle">${xml((description||"Governed research intelligence dashboard").slice(0,150))}</text><text x="${width-margin}" y="72" text-anchor="end" class="meta">Generated ${xml(generatedAt)}</text>${cards.join("")}<text x="${margin}" y="${height-40}" class="footer">${xml(branding.footerText||"Senzilytics · Governed research intelligence")}</text><text x="${width-margin}" y="${height-40}" text-anchor="end" class="footer">Human-reviewed analytical output · ${layout.widgets.length} visualization${layout.widgets.length===1?"":"s"}</text></svg>`}

export async function createResearchDashboardPng(svg:string){return sharp(Buffer.from(svg)).png({compressionLevel:9,quality:100}).toBuffer()}

export async function createResearchDashboardPdf(svg:string){const width=1600,height=1000,{data,info}=await sharp(Buffer.from(svg)).flatten({background:"#07111F"}).resize(width,height,{fit:"contain",background:"#07111F"}).removeAlpha().raw().toBuffer({resolveWithObject:true}),compressed=deflateSync(data),content="q 842 0 0 595 0 0 cm /Im0 Do Q",objects=["<< /Type /Catalog /Pages 2 0 R >>","<< /Type /Pages /Kids [3 0 R] /Count 1 >>","<< /Type /Page /Parent 2 0 R /MediaBox [0 0 842 595] /Resources << /XObject << /Im0 5 0 R >> >> /Contents 4 0 R >>",`<< /Length ${Buffer.byteLength(content)} >>\nstream\n${content}\nendstream`,`<< /Type /XObject /Subtype /Image /Width ${info.width} /Height ${info.height} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /FlateDecode /Length ${compressed.length} >>\nstream\n`];const chunks:Buffer[]=[Buffer.from("%PDF-1.4\n%\xFF\xFF\xFF\xFF\n","binary")],offsets=[0];for(let index=0;index<objects.length;index++){offsets.push(Buffer.concat(chunks).length);chunks.push(Buffer.from(`${index+1} 0 obj\n${objects[index]}`));if(index===4){chunks.push(compressed);chunks.push(Buffer.from("\nendstream\nendobj\n"))}else chunks.push(Buffer.from("\nendobj\n"))}const xref=Buffer.concat(chunks).length;chunks.push(Buffer.from(`xref\n0 6\n0000000000 65535 f \n${offsets.slice(1).map(offset=>String(offset).padStart(10,"0")+" 00000 n \n").join("")}trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`));return Buffer.concat(chunks)}
