CREATE TYPE "ResearchSurveyCampaignStatus" AS ENUM ('DRAFT', 'ACTIVE', 'PAUSED', 'CLOSED', 'CANCELLED');
CREATE TYPE "ResearchSurveyInvitationStatus" AS ENUM ('PENDING', 'SENT', 'OPENED', 'COMPLETED', 'FAILED', 'REVOKED');
ALTER TABLE "ResearchPublicResponse" ADD COLUMN "invitationId" TEXT;
CREATE TABLE "ResearchSurveyCampaign" ("id" TEXT NOT NULL,"organizationId" TEXT NOT NULL,"collectionId" TEXT NOT NULL,"publicLinkId" TEXT NOT NULL,"name" TEXT NOT NULL,"channel" TEXT NOT NULL DEFAULT 'EMAIL',"status" "ResearchSurveyCampaignStatus" NOT NULL DEFAULT 'DRAFT',"reminderLimit" INTEGER NOT NULL DEFAULT 2,"createdById" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"activatedAt" TIMESTAMP(3),"closedAt" TIMESTAMP(3),CONSTRAINT "ResearchSurveyCampaign_pkey" PRIMARY KEY ("id"));
CREATE TABLE "ResearchSurveyInvitation" ("id" TEXT NOT NULL,"organizationId" TEXT NOT NULL,"campaignId" TEXT NOT NULL,"token" TEXT NOT NULL,"participantName" TEXT,"participantEmail" TEXT NOT NULL,"status" "ResearchSurveyInvitationStatus" NOT NULL DEFAULT 'PENDING',"remindersSent" INTEGER NOT NULL DEFAULT 0,"sentAt" TIMESTAMP(3),"openedAt" TIMESTAMP(3),"completedAt" TIMESTAMP(3),"lastReminderAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "ResearchSurveyInvitation_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "ResearchPublicResponse_invitationId_key" ON "ResearchPublicResponse"("invitationId");
CREATE INDEX "ResearchSurveyCampaign_organizationId_status_createdAt_idx" ON "ResearchSurveyCampaign"("organizationId","status","createdAt");
CREATE INDEX "ResearchSurveyCampaign_collectionId_status_idx" ON "ResearchSurveyCampaign"("collectionId","status");
CREATE UNIQUE INDEX "ResearchSurveyInvitation_token_key" ON "ResearchSurveyInvitation"("token");
CREATE UNIQUE INDEX "ResearchSurveyInvitation_campaignId_participantEmail_key" ON "ResearchSurveyInvitation"("campaignId","participantEmail");
CREATE INDEX "ResearchSurveyInvitation_organizationId_status_createdAt_idx" ON "ResearchSurveyInvitation"("organizationId","status","createdAt");
CREATE INDEX "ResearchSurveyInvitation_campaignId_status_idx" ON "ResearchSurveyInvitation"("campaignId","status");
ALTER TABLE "ResearchSurveyCampaign" ADD CONSTRAINT "ResearchSurveyCampaign_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ResearchSurveyCampaign" ADD CONSTRAINT "ResearchSurveyCampaign_collectionId_fkey" FOREIGN KEY ("collectionId") REFERENCES "ResearchCollectionWave"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ResearchSurveyCampaign" ADD CONSTRAINT "ResearchSurveyCampaign_publicLinkId_fkey" FOREIGN KEY ("publicLinkId") REFERENCES "ResearchPublicSurveyLink"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "ResearchSurveyCampaign" ADD CONSTRAINT "ResearchSurveyCampaign_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "ResearchSurveyInvitation" ADD CONSTRAINT "ResearchSurveyInvitation_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ResearchSurveyInvitation" ADD CONSTRAINT "ResearchSurveyInvitation_campaignId_fkey" FOREIGN KEY ("campaignId") REFERENCES "ResearchSurveyCampaign"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ResearchPublicResponse" ADD CONSTRAINT "ResearchPublicResponse_invitationId_fkey" FOREIGN KEY ("invitationId") REFERENCES "ResearchSurveyInvitation"("id") ON DELETE SET NULL ON UPDATE CASCADE;
