CREATE TYPE "ComplianceObligationType" AS ENUM ('LEGAL','REGULATORY','PERMIT_CONDITION','STANDARD','CONTRACTUAL','INTERNAL','OTHER');
CREATE TYPE "ComplianceRecurrence" AS ENUM ('ONE_TIME','MONTHLY','QUARTERLY','SEMIANNUAL','ANNUAL','CUSTOM');
CREATE TYPE "PermitStatus" AS ENUM ('DRAFT','ACTIVE','EXPIRING','EXPIRED','SUSPENDED','CLOSED');
ALTER TABLE "ComplianceItem" ADD COLUMN "reference" TEXT;
ALTER TABLE "ComplianceItem" ADD COLUMN "obligationType" "ComplianceObligationType" NOT NULL DEFAULT 'REGULATORY';
ALTER TABLE "ComplianceItem" ADD COLUMN "authority" TEXT;
ALTER TABLE "ComplianceItem" ADD COLUMN "jurisdiction" TEXT;
ALTER TABLE "ComplianceItem" ADD COLUMN "legalReference" TEXT;
ALTER TABLE "ComplianceItem" ADD COLUMN "applicability" TEXT;
ALTER TABLE "ComplianceItem" ADD COLUMN "recurrence" "ComplianceRecurrence" NOT NULL DEFAULT 'ONE_TIME';
ALTER TABLE "ComplianceItem" ADD COLUMN "intervalValue" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "ComplianceItem" ADD COLUMN "evidenceRequired" TEXT;
ALTER TABLE "ComplianceItem" ADD COLUMN "ownerId" TEXT;
ALTER TABLE "ComplianceItem" ADD COLUMN "completedAt" TIMESTAMP(3);
ALTER TABLE "ComplianceItem" ADD COLUMN "lastEvaluatedAt" TIMESTAMP(3);
ALTER TABLE "ComplianceItem" ADD COLUMN "evaluationNotes" TEXT;
CREATE TABLE "Permit" ("id" TEXT NOT NULL,"organizationId" TEXT NOT NULL,"siteId" TEXT NOT NULL,"ownerId" TEXT,"number" TEXT NOT NULL,"name" TEXT NOT NULL,"description" TEXT,"authority" TEXT,"permitType" TEXT,"status" "PermitStatus" NOT NULL DEFAULT 'DRAFT',"effectiveDate" TIMESTAMP(3),"expirationDate" TIMESTAMP(3),"renewalDueDate" TIMESTAMP(3),"conditions" TEXT,"limits" TEXT,"reportingRequirements" TEXT,"notes" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "Permit_pkey" PRIMARY KEY ("id"));
CREATE INDEX "ComplianceItem_ownerId_status_idx" ON "ComplianceItem"("ownerId","status");
CREATE INDEX "ComplianceItem_siteId_dueDate_idx" ON "ComplianceItem"("siteId","dueDate");
CREATE UNIQUE INDEX "Permit_organizationId_number_key" ON "Permit"("organizationId","number");
CREATE INDEX "Permit_organizationId_status_idx" ON "Permit"("organizationId","status");
CREATE INDEX "Permit_siteId_expirationDate_idx" ON "Permit"("siteId","expirationDate");
CREATE INDEX "Permit_ownerId_status_idx" ON "Permit"("ownerId","status");
ALTER TABLE "ComplianceItem" ADD CONSTRAINT "ComplianceItem_ownerId_fkey" FOREIGN KEY ("ownerId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Permit" ADD CONSTRAINT "Permit_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Permit" ADD CONSTRAINT "Permit_siteId_fkey" FOREIGN KEY ("siteId") REFERENCES "Site"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Permit" ADD CONSTRAINT "Permit_ownerId_fkey" FOREIGN KEY ("ownerId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
