import ExcelJS from "exceljs";import { requirePermission } from "@/lib/permissions";import { getCurrentUserTenant } from "@/lib/tenant";import { getResearchDataset } from "@/modules/research/research-dataset.service";import { summarizeVariable } from "@/modules/research/research-analysis";import { PermissionKey } from "@prisma/client";
export const runtime="nodejs";export const dynamic="force-dynamic";const safe=(value:unknown)=>{if(Array.isArray(value))return value.join(" | ");if(typeof value==="string"&&/^[=+\-@\t\r]/.test(value))return `'${value}`;return value??""};
export async function GET(_request:Request,{params}:{params:Promise<{collectionId:string}>}){await requirePermission(PermissionKey.EXPORT_RESEARCH_OUTPUTS);const[{collectionId},{organizationId}]=await Promise.all([params,getCurrentUserTenant()]),dataset=await getResearchDataset(organizationId,collectionId);if(!dataset)return new Response("Dataset not found.",{status:404});const{collection,variables,rows,analysisRows,qualityIssues}=dataset,workbook=new ExcelJS.Workbook();workbook.creator="Senzilytics";workbook.subject=`Governed research dataset ${collection.project.reference}`;
  const metadata=workbook.addWorksheet("Governance");metadata.addRows([["Senzilytics Research Dataset"],["Project",`${collection.project.reference} — ${collection.project.title}`],["Commissioning client",collection.project.client?.name??"Internal research"],["Research purpose",collection.questionnaire.purpose],["Collection wave",collection.name],["Questionnaire version",collection.formVersion.version],["Dataset status",collection.datasetStatus],["Identity mode",collection.questionnaire.identityMode],["Completed responses",rows.length],["Included analytical responses",analysisRows.length],["Generated at",new Date().toISOString()]]);
  const data=workbook.addWorksheet("Clean Data");data.addRow(["response_id","submitted_at",...variables.map(variable=>variable.key)]);for(const row of analysisRows)data.addRow([row.responseId,row.submittedAt,...variables.map(variable=>safe(row.values[variable.key]))]);
  const dictionary=workbook.addWorksheet("Data Dictionary");dictionary.addRow(["Variable key","Label","Type","Required"]);for(const variable of variables)dictionary.addRow([variable.key,variable.label,variable.type,variable.required?"Yes":"No"]);
  const quality=workbook.addWorksheet("Quality Review");quality.addRow(["Response code","Disposition","Automated signals","Reviewer notes","Reviewed by","Reviewed at"]);for(const assignment of collection.assignments)quality.addRow([assignment.id.slice(-8).toUpperCase(),assignment.disposition,(qualityIssues.get(assignment.id)??[]).join(" | "),assignment.qualityNotes??"",assignment.reviewedBy?.name??"",assignment.reviewedAt?.toISOString()??""]);
  const summary=workbook.addWorksheet("Statistics");summary.addRow(["Variable","N","Missing","Unique","Mean","Median","Std deviation","Minimum","Maximum"]);for(const variable of variables){const stats=summarizeVariable(variable,analysisRows);summary.addRow([variable.label,stats.present,stats.missing,stats.unique,stats.mean,stats.median,stats.standardDeviation,stats.min,stats.max])}
  for(const sheet of workbook.worksheets){sheet.views=[{state:"frozen",ySplit:sheet.name==="Governance"?0:1}];sheet.getRow(1).font={bold:true,color:{argb:"FF07111F"}};sheet.getRow(1).fill={type:"pattern",pattern:"solid",fgColor:{argb:"FF67E8F9"}};sheet.columns.forEach(column=>column.width=22);sheet.autoFilter=sheet.rowCount>1&&sheet.columnCount>1?{from:{row:1,column:1},to:{row:sheet.rowCount,column:sheet.columnCount}}:undefined}
  const buffer=await workbook.xlsx.writeBuffer();return new Response(new Uint8Array(buffer),{headers:{"Content-Type":"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","Content-Disposition":`attachment; filename="${collection.project.reference}-research-dataset.xlsx"`,"Cache-Control":"private, no-store"}})}
