CREATE TYPE "IndustryCategory" AS ENUM ('GENERAL', 'RESEARCH_AND_ANALYTICS', 'CONSTRUCTION_AND_ENGINEERING', 'MANUFACTURING', 'ENERGY_AND_MINING', 'HEALTHCARE', 'TRANSPORT_AND_LOGISTICS', 'PUBLIC_SECTOR_AND_EDUCATION', 'PROFESSIONAL_SERVICES', 'OTHER');

ALTER TABLE "Organization" ADD COLUMN "industryCategory" "IndustryCategory" NOT NULL DEFAULT 'GENERAL';
