import{PermissionKey,ResearchDashboardStatus}from"@prisma/client";
import{requirePermission}from"@/lib/permissions";
import{prisma}from"@/lib/prisma";
import{getCurrentUserTenant}from"@/lib/tenant";
import{normalizeDashboardBranding,normalizeDashboardLayout}from"@/modules/research/research-dashboard";
import{createResearchDashboardPdf,createResearchDashboardPng,createResearchDashboardSvg}from"@/modules/research/research-dashboard-export";

export const runtime="nodejs";export const dynamic="force-dynamic";
export async function GET(request:Request,{params}:{params:Promise<{dashboardId:string}>}){await requirePermission(PermissionKey.EXPORT_RESEARCH_OUTPUTS);const[{dashboardId},{organizationId}]=await Promise.all([params,getCurrentUserTenant()]),dashboard=await prisma.researchVisualizationDashboard.findFirst({where:{id:dashboardId,organizationId},include:{project:{include:{client:true}}}});if(!dashboard)return new Response("Dashboard not found.",{status:404});if(dashboard.status!==ResearchDashboardStatus.APPROVED)return new Response("Only independently approved dashboards can be exported.",{status:409});const raw=dashboard.layoutDefinition&&typeof dashboard.layoutDefinition==="object"?dashboard.layoutDefinition as{widgets?:unknown}:{};const requestedIds=Array.isArray(raw.widgets)?raw.widgets.flatMap(item=>item&&typeof item==="object"&&"analysisId"in item?[String(item.analysisId)]:[]):[],analyses=await prisma.researchAnalysis.findMany({where:{organizationId,id:{in:requestedIds},status:"APPROVED",OR:[{collection:{projectId:dashboard.projectId}},{datasetVersion:{dataset:{projectId:dashboard.projectId}}}]},select:{id:true,title:true,method:true,status:true,datasetResponseCount:true,resultSnapshot:true}}),allowed=new Set(analyses.map(item=>item.id)),layout=normalizeDashboardLayout(dashboard.layoutDefinition,allowed);if(!layout.widgets.length)return new Response("The dashboard has no approved analytical widgets to export.",{status:409});const branding=normalizeDashboardBranding(dashboard.branding,dashboard.project.client?.name??dashboard.project.title),svg=createResearchDashboardSvg({title:dashboard.title,description:dashboard.description,status:dashboard.status,layout,branding,analyses,generatedAt:new Date().toISOString()}),format=new URL(request.url).searchParams.get("format")?.toLowerCase(),filename=dashboard.title.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,80)||"research-dashboard";if(format==="svg")return new Response(svg,{headers:{"Content-Type":"image/svg+xml; charset=utf-8","Content-Disposition":`attachment; filename="${filename}.svg"`,"Cache-Control":"private, no-store"}});if(format==="png"){const output=await createResearchDashboardPng(svg);return new Response(new Uint8Array(output),{headers:{"Content-Type":"image/png","Content-Disposition":`attachment; filename="${filename}.png"`,"Cache-Control":"private, no-store"}})}if(format==="pdf"){const output=await createResearchDashboardPdf(svg);return new Response(new Uint8Array(output),{headers:{"Content-Type":"application/pdf","Content-Disposition":`attachment; filename="${filename}.pdf"`,"Cache-Control":"private, no-store"}})}return new Response("Select svg, png, or pdf format.",{status:400})}
