"use server";
import { sendEmail, getApplicationUrl } from "@/core/email/email.service";
import { logActivity } from "@/core/activity-log/activity-log.service";
import { isTenantModuleKey, tenantAssignableModules, tenantModuleCatalog } from "@/core/navigation/tenant-module-catalog";
import { requirePermission } from "@/lib/permissions";
import { requirePlatformAdministrator } from "@/lib/platform-admin";
import { prisma } from "@/lib/prisma";
import { getCurrentUserTenant } from "@/lib/tenant";
import { tenantOnboardingStepDefinitions } from "@/modules/platform/tenant-onboarding-lifecycle";
import { ActivityAction, IndustryCategory, PermissionKey, SubscriptionPlan, TenantInvitationStatus, UserRole } from "@prisma/client";
import bcrypt from "bcryptjs";
import { createHash, randomBytes } from "node:crypto";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";

const value=(d:FormData,k:string)=>{const x=String(d.get(k)||"").trim();if(!x)throw new Error(`${k} is required.`);return x};
const hash=(token:string)=>createHash("sha256").update(token).digest("hex");
const moduleKeys=(d:FormData)=>[...new Set(d.getAll("moduleKeys").map(String).filter(isTenantModuleKey))];
const ownerRoles=new Set<UserRole>([UserRole.SUPER_ADMIN,UserRole.ORG_ADMIN]);
const requireTenantOwner=(role:UserRole)=>{if(!ownerRoles.has(role))throw new Error("Only the tenant owner or super administrator can manage user modules.")};

async function sendInvitation(input:{organizationId:string;email:string;name:string;role:UserRole;departmentId:string|null;invitedById:string;moduleKeys:string[]}) {
  const email=input.email.toLowerCase();
  const domain=email.split("@")[1];
  const organization=await prisma.organization.findUnique({where:{id:input.organizationId},include:{moduleAssignments:{select:{moduleKey:true,enabled:true}}}});
  if(!organization||organization.status!=="ACTIVE")throw new Error("The tenant is not active.");
  if(organization.allowedEmailDomains.length&&!organization.allowedEmailDomains.includes(domain))throw new Error("The email domain is not approved for this tenant.");
  if(await prisma.user.findUnique({where:{email}}))throw new Error("A user with this email already exists.");
  if(input.role===UserRole.SUPER_ADMIN)throw new Error("Platform roles cannot be assigned through tenant invitations.");
  if(input.departmentId&&!await prisma.department.findFirst({where:{id:input.departmentId,site:{organizationId:input.organizationId}}}))throw new Error("Select a department within this tenant.");
  const available=new Set<string>(tenantAssignableModules(organization.industryCategory,organization.moduleAssignments).map(module=>module.key));
  if(!input.moduleKeys.length||input.moduleKeys.some(key=>!available.has(key)))throw new Error("Select at least one module available to this tenant.");
  const token=randomBytes(32).toString("hex");
  await prisma.tenantInvitation.create({data:{...input,email,tokenHash:hash(token),expiresAt:new Date(Date.now()+72*3600000)}});
  const link=`${getApplicationUrl()}/activate?token=${token}`;
  await sendEmail({to:email,subject:`You're invited to ${organization.name} on Senzilytics`,html:`<p>Hello ${input.name},</p><p>You have been invited to ${organization.name} on Senzilytics.</p><p><a href="${link}">Activate your account</a></p><p>This link expires in 72 hours.</p>`,text:`Activate your account: ${link}`});
}

export async function inviteTenantUser(d:FormData){await requirePermission(PermissionKey.MANAGE_USERS);const{organizationId,user}=await getCurrentUserTenant();requireTenantOwner(user.role);await sendInvitation({organizationId,invitedById:user.id,email:value(d,"email"),name:value(d,"name"),role:value(d,"role") as UserRole,departmentId:String(d.get("departmentId")||"").trim()||null,moduleKeys:moduleKeys(d)});revalidatePath("/users")}

export async function setTenantUserActive(d:FormData){await requirePermission(PermissionKey.MANAGE_USERS);const{organizationId,user}=await getCurrentUserTenant();const id=value(d,"id");if(id===user.id)throw new Error("You cannot suspend your own account.");const active=value(d,"active")==="true";if(active)await prisma.user.updateMany({where:{id,organizationId},data:{isActive:true}});else await prisma.$transaction([prisma.user.updateMany({where:{id,organizationId},data:{isActive:false,sessionVersion:{increment:1}}}),prisma.mobileSession.updateMany({where:{userId:id,organizationId,status:"ACTIVE"},data:{status:"REVOKED",revokedAt:new Date()}}),prisma.mobilePushToken.updateMany({where:{userId:id,organizationId},data:{enabled:false}})]);revalidatePath("/users")}

export async function createTenant(d:FormData){const admin=await requirePlatformAdministrator();const name=value(d,"name"),email=value(d,"adminEmail").toLowerCase(),domain=value(d,"domain").toLowerCase(),subscriptionPlan=value(d,"subscriptionPlan") as SubscriptionPlan,industryCategory=value(d,"industryCategory") as IndustryCategory;if(!Object.values(SubscriptionPlan).includes(subscriptionPlan))throw new Error("Select a valid subscription plan.");if(!Object.values(IndustryCategory).includes(industryCategory))throw new Error("Select a valid industry category.");const requestedMinimum=Number(String(d.get("contractedUserMinimum")||"")),contractedUserMinimum=Number.isInteger(requestedMinimum)&&requestedMinimum>0?requestedMinimum:subscriptionPlan===SubscriptionPlan.ESSENTIAL?25:subscriptionPlan===SubscriptionPlan.ENTERPRISE?20:null;const organization=await prisma.organization.create({data:{name,industryCategory,industry:String(d.get("industry")||"").trim()||null,allowedEmailDomains:[domain],subscriptionPlan,contractedUserMinimum,subscriptionNotes:String(d.get("subscriptionNotes")||"").trim()||null,onboardingPlan:{create:{steps:{create:tenantOnboardingStepDefinitions.map(step=>({key:step.key,updatedById:admin.id}))}}}}});await sendInvitation({organizationId:organization.id,invitedById:admin.id,email,name:value(d,"adminName"),role:UserRole.ORG_ADMIN,departmentId:null,moduleKeys:tenantModuleCatalog.map(module=>module.key)});revalidatePath("/platform/tenants")}

export async function updateTenantSubscription(d:FormData){await requirePlatformAdministrator();const id=value(d,"organizationId"),subscriptionPlan=value(d,"subscriptionPlan") as SubscriptionPlan,industryCategory=value(d,"industryCategory") as IndustryCategory;if(!Object.values(SubscriptionPlan).includes(subscriptionPlan))throw new Error("Select a valid subscription plan.");if(!Object.values(IndustryCategory).includes(industryCategory))throw new Error("Select a valid industry category.");const raw=String(d.get("contractedUserMinimum")||"").trim(),minimum=raw?Number(raw):null;if(minimum!==null&&(!Number.isInteger(minimum)||minimum<1))throw new Error("Contracted users must be a positive whole number.");const organizationData={subscriptionPlan,industryCategory,industry:String(d.get("industry")||"").trim()||null,contractedUserMinimum:minimum,subscriptionNotes:String(d.get("subscriptionNotes")||"").trim()||null};if(subscriptionPlan===SubscriptionPlan.PREMIUM)await prisma.organization.update({where:{id},data:organizationData});else await prisma.$transaction([prisma.organization.update({where:{id},data:organizationData}),prisma.mobileSession.updateMany({where:{organizationId:id,status:"ACTIVE"},data:{status:"REVOKED",revokedAt:new Date()}}),prisma.mobilePushToken.updateMany({where:{organizationId:id},data:{enabled:false}})]);revalidatePath("/platform/tenants");revalidatePath("/","layout")}

export async function setTenantModuleAssignment(d:FormData){const admin=await requirePlatformAdministrator();const organizationId=value(d,"organizationId"),moduleKey=value(d,"moduleKey"),enabled=value(d,"enabled")==="true";if(!isTenantModuleKey(moduleKey))throw new Error("Select a valid tenant module.");const organization=await prisma.organization.findUnique({where:{id:organizationId},select:{id:true,name:true}});if(!organization)throw new Error("Tenant not found.");const assignment=await prisma.tenantModuleAssignment.upsert({where:{organizationId_moduleKey:{organizationId,moduleKey}},create:{organizationId,moduleKey,enabled,source:"MANUAL",assignedById:admin.id},update:{enabled,source:"MANUAL",assignedById:admin.id,assignedAt:new Date()}});await logActivity({organizationId,userId:admin.id,action:ActivityAction.UPDATE,entityType:"TenantModuleAssignment",entityId:assignment.id,title:enabled?"Tenant module assigned":"Tenant module disabled",description:`${organization.name}: ${moduleKey}`,metadata:{moduleKey,enabled,source:"MANUAL"}});revalidatePath("/platform/tenants");revalidatePath("/","layout")}

export async function setUserModuleAssignments(d:FormData){await requirePermission(PermissionKey.MANAGE_USERS);const{organizationId,user}=await getCurrentUserTenant();requireTenantOwner(user.role);const targetUserId=value(d,"userId"),selected=new Set(moduleKeys(d));const[target,organization]=await Promise.all([prisma.user.findFirst({where:{id:targetUserId,organizationId},select:{id:true,name:true}}),prisma.organization.findUnique({where:{id:organizationId},include:{moduleAssignments:{select:{moduleKey:true,enabled:true}}}})]);if(!target||!organization)throw new Error("Tenant user not found.");const available=tenantAssignableModules(organization.industryCategory,organization.moduleAssignments);await prisma.$transaction(async tx=>{for(const catalogEntry of available){await tx.userModuleAssignment.upsert({where:{userId_moduleKey:{userId:target.id,moduleKey:catalogEntry.key}},create:{organizationId,userId:target.id,moduleKey:catalogEntry.key,enabled:selected.has(catalogEntry.key),assignedById:user.id},update:{enabled:selected.has(catalogEntry.key),assignedById:user.id,assignedAt:new Date()}})}await tx.activityLog.create({data:{organizationId,userId:user.id,action:ActivityAction.UPDATE,entityType:"UserModuleAssignment",entityId:target.id,title:"User module access updated",description:target.name,metadata:{enabledModuleKeys:[...selected]}}})});revalidatePath("/users");revalidatePath("/","layout")}

export async function activateInvitation(d:FormData){const token=value(d,"token"),password=value(d,"password");if(password.length<12)throw new Error("Password must contain at least 12 characters.");const invitation=await prisma.tenantInvitation.findUnique({where:{tokenHash:hash(token)},include:{organization:true}});if(!invitation||invitation.status!==TenantInvitationStatus.PENDING||invitation.expiresAt<=new Date()||invitation.organization.status!=="ACTIVE")throw new Error("This invitation is invalid or expired.");const user=await prisma.$transaction(async tx=>{const created=await tx.user.create({data:{name:invitation.name,email:invitation.email,password:await bcrypt.hash(password,12),role:invitation.role,organizationId:invitation.organizationId,departmentId:invitation.departmentId,isActive:true,invitedAt:invitation.createdAt,activatedAt:new Date()}});if(invitation.moduleKeys.length)await tx.userModuleAssignment.createMany({data:tenantModuleCatalog.map(catalogEntry=>({organizationId:invitation.organizationId,userId:created.id,moduleKey:catalogEntry.key,enabled:invitation.moduleKeys.includes(catalogEntry.key),assignedById:invitation.invitedById}))});await tx.tenantInvitation.update({where:{id:invitation.id},data:{status:TenantInvitationStatus.ACCEPTED,acceptedById:created.id,acceptedAt:new Date()}});return created});redirect(`/login?activated=${user.id}`)}

export async function configureTenantIdentityProvider(d:FormData){await requirePermission(PermissionKey.MANAGE_ORGANIZATION);const{organizationId}=await getCurrentUserTenant();const type=value(d,"type") as "MICROSOFT_ENTRA"|"OKTA",issuer=value(d,"issuer");if(!["MICROSOFT_ENTRA","OKTA"].includes(type))throw new Error("Select a supported identity provider.");const data={issuer,directoryId:String(d.get("directoryId")||"").trim()||null,emailDomain:String(d.get("emailDomain")||"").trim().toLowerCase()||null,isEnabled:true,enforceSso:d.get("enforceSso")==="on"};const existing=await prisma.organizationIdentityProvider.findFirst({where:{organizationId,type}});if(existing)await prisma.organizationIdentityProvider.update({where:{id:existing.id},data});else await prisma.organizationIdentityProvider.create({data:{organizationId,type,...data}});revalidatePath("/organizations")}
