import { createNotification } from "@/core/notifications/notifications.service";
import { prisma } from "@/lib/prisma";
import { canTransitionAssetStatus, canTransitionMaintenanceStatus, nextAssetDueDate } from "@/modules/assets/asset-lifecycle";
import { createPreparedSubmissions, type PreparedSubmission } from "@/modules/forms/runtime-form.service";
import {
  ActivityAction,
  AssetDefectStatus,
  AssetInspectionResult,
  AssetMaintenanceStatus,
  AssetMaintenanceType,
  AssetStatus,
  AssetType,
  ConfigurableFormModule,
  NotificationType,
  Prisma,
  RiskLevel,
  Status,
} from "@prisma/client";

const reference=(prefix:string)=>`${prefix}-${new Date().getUTCFullYear()}-${Date.now().toString(36).toUpperCase()}`;
const activeDefectStatuses=[AssetDefectStatus.OPEN,AssetDefectStatus.UNDER_REVIEW,AssetDefectStatus.REPAIR_PLANNED,AssetDefectStatus.REPAIRED,AssetDefectStatus.DEFERRED];

type OfflineSubmissionInput = {
  id: string;
  capturedAt: Date;
  payloadHash: string;
};

const defectTransitions: Record<AssetDefectStatus, AssetDefectStatus[]> = {
  OPEN: [AssetDefectStatus.UNDER_REVIEW, AssetDefectStatus.REPAIR_PLANNED, AssetDefectStatus.DEFERRED],
  UNDER_REVIEW: [AssetDefectStatus.REPAIR_PLANNED, AssetDefectStatus.DEFERRED],
  REPAIR_PLANNED: [AssetDefectStatus.REPAIRED, AssetDefectStatus.DEFERRED],
  REPAIRED: [AssetDefectStatus.VERIFIED],
  VERIFIED: [AssetDefectStatus.CLOSED],
  CLOSED: [],
  DEFERRED: [AssetDefectStatus.UNDER_REVIEW, AssetDefectStatus.REPAIR_PLANNED],
};

export const getAssetDefectNextStatuses = (status: AssetDefectStatus) => [
  ...defectTransitions[status],
];

async function recordOfflineSubmission(
  tx: Prisma.TransactionClient,
  input: {
    organizationId: string;
    userId: string;
    offlineSubmission?: OfflineSubmissionInput;
  },
  recordType: string,
  recordId: string
) {
  if (!input.offlineSubmission) return;
  await tx.offlineSubmission.create({
    data: {
      id: input.offlineSubmission.id,
      organizationId: input.organizationId,
      userId: input.userId,
      recordType,
      recordId,
      capturedAt: input.offlineSubmission.capturedAt,
      payloadHash: input.offlineSubmission.payloadHash,
    },
  });
}

async function tenantAsset(organizationId:string,assetId:string){return prisma.asset.findFirst({where:{id:assetId,organizationId},include:{owner:true,site:true}})}

export async function createAssetService(input:{organizationId:string;userId:string;reference:string;name:string;description?:string|null;type:AssetType;criticality:RiskLevel;isSafetyCritical:boolean;manufacturer?:string|null;modelNumber?:string|null;serialNumber?:string|null;siteId:string;departmentId?:string|null;location?:string|null;ownerId?:string|null;commissionedAt?:Date|null;inspectionIntervalDays:number;maintenanceIntervalDays:number;permitRequired:boolean}){
  const[creator,site,department,owner]=await Promise.all([prisma.user.findFirst({where:{id:input.userId,organizationId:input.organizationId,isActive:true}}),prisma.site.findFirst({where:{id:input.siteId,organizationId:input.organizationId}}),input.departmentId?prisma.department.findFirst({where:{id:input.departmentId,site:{organizationId:input.organizationId}}}):null,input.ownerId?prisma.user.findFirst({where:{id:input.ownerId,organizationId:input.organizationId,isActive:true}}):null]);
  if(!creator||!site||(input.departmentId&&!department)||(input.ownerId&&!owner))throw new Error("Select valid tenant asset ownership and scope values.");
  if(department&&department.siteId!==site.id)throw new Error("The selected department does not belong to the asset site.");
  const now=new Date(),nextInspectionDueAt=nextAssetDueDate(now,input.inspectionIntervalDays),nextMaintenanceDueAt=nextAssetDueDate(now,input.maintenanceIntervalDays);
  const asset=await prisma.$transaction(async tx=>{const created=await tx.asset.create({data:{organizationId:input.organizationId,reference:input.reference.toUpperCase(),name:input.name,description:input.description,type:input.type,criticality:input.criticality,isSafetyCritical:input.isSafetyCritical,manufacturer:input.manufacturer,modelNumber:input.modelNumber,serialNumber:input.serialNumber,siteId:site.id,departmentId:input.departmentId,location:input.location,ownerId:input.ownerId,createdById:creator.id,commissionedAt:input.commissionedAt,inspectionIntervalDays:input.inspectionIntervalDays,nextInspectionDueAt,maintenanceIntervalDays:input.maintenanceIntervalDays,nextMaintenanceDueAt,permitRequired:input.permitRequired}});await tx.activityLog.create({data:{organizationId:input.organizationId,userId:creator.id,action:ActivityAction.CREATE,entityType:"Asset",entityId:created.id,title:"Asset registered",description:`${created.reference} — ${created.name}`,metadata:{siteId:created.siteId,type:created.type,criticality:created.criticality,isSafetyCritical:created.isSafetyCritical}}});return created});
  if(asset.ownerId&&asset.ownerId!==creator.id)await createNotification({organizationId:input.organizationId,userId:asset.ownerId,type:NotificationType.ASSIGNMENT,title:"Asset ownership assigned",message:`${asset.reference} — ${asset.name} was assigned to you.`,link:`/assets/${asset.id}`}).catch(()=>undefined);
  return asset;
}

export async function changeAssetStatusService(input:{organizationId:string;userId:string;assetId:string;status:AssetStatus;reason:string;offlineSubmission?:OfflineSubmissionInput}){
  const[asset,user]=await Promise.all([tenantAsset(input.organizationId,input.assetId),prisma.user.findFirst({where:{id:input.userId,organizationId:input.organizationId,isActive:true}})]);if(!asset||!user)throw new Error("Asset not found in this organization.");if(!canTransitionAssetStatus(asset.status,input.status))throw new Error(`An asset cannot move from ${asset.status.replaceAll("_"," ")} to ${input.status.replaceAll("_"," ")}.`);if(!input.reason.trim())throw new Error("Record the reason for the asset status change.");
  if(input.status===AssetStatus.ACTIVE){const unresolved=await prisma.assetDefect.count({where:{organizationId:input.organizationId,assetId:asset.id,status:{notIn:[AssetDefectStatus.VERIFIED,AssetDefectStatus.CLOSED]},severity:{in:[RiskLevel.HIGH,RiskLevel.CRITICAL]}}});if(unresolved)throw new Error(`${unresolved} high or critical defect${unresolved===1?" remains":"s remain"} unresolved. Verify the repair before returning this asset to service.`)}
  return prisma.$transaction(async tx=>{const updated=await tx.asset.update({where:{id:asset.id},data:{status:input.status}});await tx.activityLog.create({data:{organizationId:input.organizationId,userId:user.id,action:ActivityAction.STATUS_CHANGE,entityType:"Asset",entityId:asset.id,title:"Asset status changed",description:`${asset.status} → ${updated.status}: ${input.reason}`,metadata:{previousStatus:asset.status,status:updated.status,reason:input.reason}}});await recordOfflineSubmission(tx,input,"ASSET_STATUS",updated.id);return updated});
}

export async function recordAssetInspectionService(input:{organizationId:string;userId:string;assetId:string;inspectedAt:Date;result:AssetInspectionResult;conditionScore?:number|null;evidenceReference?:string|null;observations?:string|null;immediateAction?:string|null;customSubmissions?:PreparedSubmission[];offlineSubmission?:OfflineSubmissionInput}){
  const[asset,inspector]=await Promise.all([tenantAsset(input.organizationId,input.assetId),prisma.user.findFirst({where:{id:input.userId,organizationId:input.organizationId,isActive:true}})]);if(!asset||!inspector)throw new Error("Asset not found in this organization.");if(Number.isNaN(input.inspectedAt.getTime())||input.inspectedAt>new Date())throw new Error("Inspection date cannot be invalid or in the future.");if(input.conditionScore!==null&&input.conditionScore!==undefined&&(!Number.isInteger(input.conditionScore)||input.conditionScore<1||input.conditionScore>5))throw new Error("Condition score must be between 1 and 5.");if(asset.isSafetyCritical&&input.result===AssetInspectionResult.SATISFACTORY&&!input.evidenceReference)throw new Error("Record an evidence reference before confirming a safety-critical asset is satisfactory.");if((input.result===AssetInspectionResult.DEFECT_FOUND||input.result===AssetInspectionResult.OUT_OF_SERVICE)&&!input.observations)throw new Error("Describe the observed defect or unsafe condition.");
  const nextInspectionDueAt=nextAssetDueDate(input.inspectedAt,asset.inspectionIntervalDays);
  const result=await prisma.$transaction(async tx=>{const inspection=await tx.assetInspection.create({data:{organizationId:input.organizationId,assetId:asset.id,inspectedById:inspector.id,inspectedAt:input.inspectedAt,result:input.result,conditionScore:input.conditionScore,evidenceReference:input.evidenceReference,observations:input.observations,immediateAction:input.immediateAction,nextInspectionDueAt}});await createPreparedSubmissions(tx,{organizationId:input.organizationId,userId:inspector.id,module:ConfigurableFormModule.ASSET_SAFETY,entityId:inspection.id,submissions:input.customSubmissions??[]});await tx.asset.update({where:{id:asset.id},data:{lastInspectionAt:input.inspectedAt,nextInspectionDueAt,inspectionReminderAt:null,inspectionOverdueAt:null,...(input.result===AssetInspectionResult.OUT_OF_SERVICE?{status:AssetStatus.OUT_OF_SERVICE}:{})}});let defect=null;if(input.result===AssetInspectionResult.DEFECT_FOUND||input.result===AssetInspectionResult.OUT_OF_SERVICE){defect=await tx.assetDefect.create({data:{organizationId:input.organizationId,assetId:asset.id,sourceInspectionId:inspection.id,reference:reference("DEF"),title:`${asset.name} inspection defect`,description:input.observations!,severity:input.result===AssetInspectionResult.OUT_OF_SERVICE?RiskLevel.CRITICAL:asset.criticality===RiskLevel.LOW?RiskLevel.MEDIUM:asset.criticality,reportedById:inspector.id,ownerId:asset.ownerId,dueDate:nextAssetDueDate(input.inspectedAt,input.result===AssetInspectionResult.OUT_OF_SERVICE?3:14),immediateControls:input.immediateAction}})}await tx.activityLog.create({data:{organizationId:input.organizationId,userId:inspector.id,action:ActivityAction.CREATE,entityType:"AssetInspection",entityId:inspection.id,title:"Asset safety inspection recorded",description:`${asset.reference} — ${inspection.result}`,metadata:{assetId:asset.id,result:inspection.result,conditionScore:inspection.conditionScore,defectId:defect?.id??null,nextInspectionDueAt}}});await recordOfflineSubmission(tx,input,"ASSET_INSPECTION",inspection.id);return{inspection,defect}});
  if(asset.ownerId&&(result.defect||input.result===AssetInspectionResult.OUT_OF_SERVICE))await createNotification({organizationId:input.organizationId,userId:asset.ownerId,type:input.result===AssetInspectionResult.OUT_OF_SERVICE?NotificationType.CRITICAL:NotificationType.WARNING,title:"Asset inspection requires action",message:`${asset.reference} — ${asset.name}: ${input.result.replaceAll("_"," ")}.`,link:`/assets/${asset.id}`}).catch(()=>undefined);
  return result;
}

export async function createAssetDefectService(input:{organizationId:string;userId:string;assetId:string;title:string;description:string;severity:RiskLevel;ownerId?:string|null;dueDate?:Date|null;immediateControls?:string|null;offlineSubmission?:OfflineSubmissionInput}){
  const[asset,reporter,owner]=await Promise.all([tenantAsset(input.organizationId,input.assetId),prisma.user.findFirst({where:{id:input.userId,organizationId:input.organizationId,isActive:true}}),input.ownerId?prisma.user.findFirst({where:{id:input.ownerId,organizationId:input.organizationId,isActive:true}}):null]);if(!asset||!reporter||(input.ownerId&&!owner))throw new Error("Select a valid tenant asset and defect owner.");if(input.dueDate&&input.dueDate<=new Date())throw new Error("Defect due date must be in the future.");
  const defect=await prisma.$transaction(async tx=>{const created=await tx.assetDefect.create({data:{organizationId:input.organizationId,assetId:asset.id,reference:reference("DEF"),title:input.title,description:input.description,severity:input.severity,reportedById:reporter.id,ownerId:input.ownerId,dueDate:input.dueDate,immediateControls:input.immediateControls}});await tx.activityLog.create({data:{organizationId:input.organizationId,userId:reporter.id,action:ActivityAction.CREATE,entityType:"AssetDefect",entityId:created.id,title:"Asset defect reported",description:`${created.reference} — ${created.title}`,metadata:{assetId:asset.id,severity:created.severity,ownerId:created.ownerId,dueDate:created.dueDate}}});await recordOfflineSubmission(tx,input,"ASSET_DEFECT",created.id);return created});if(defect.ownerId&&defect.ownerId!==reporter.id)await createNotification({organizationId:input.organizationId,userId:defect.ownerId,type:defect.severity===RiskLevel.CRITICAL?NotificationType.CRITICAL:NotificationType.ASSIGNMENT,title:"Asset defect assigned",message:`${defect.reference} — ${defect.title}`,link:`/assets/${asset.id}`}).catch(()=>undefined);return defect;
}

export async function updateAssetDefectService(input:{organizationId:string;userId:string;defectId:string;status:AssetDefectStatus;repairPlan?:string|null;verificationEvidence?:string|null;offlineSubmission?:OfflineSubmissionInput}){
  const[defect,user]=await Promise.all([prisma.assetDefect.findFirst({where:{id:input.defectId,organizationId:input.organizationId},include:{asset:true}}),prisma.user.findFirst({where:{id:input.userId,organizationId:input.organizationId,isActive:true}})]);if(!defect||!user)throw new Error("Asset defect not found in this organization.");if(defect.status!==input.status&&!defectTransitions[defect.status].includes(input.status))throw new Error(`The defect cannot move from ${defect.status.replaceAll("_"," ")} to ${input.status.replaceAll("_"," ")}.`);if(input.status===AssetDefectStatus.REPAIR_PLANNED&&!input.repairPlan)throw new Error("Record the repair plan before moving the defect to repair planned.");if(input.status===AssetDefectStatus.VERIFIED&&!input.verificationEvidence)throw new Error("Record independent verification evidence before verifying the repair.");
  return prisma.$transaction(async tx=>{const updated=await tx.assetDefect.update({where:{id:defect.id},data:{status:input.status,repairPlan:input.repairPlan??defect.repairPlan,...(input.status===AssetDefectStatus.VERIFIED?{verificationEvidence:input.verificationEvidence,verifiedById:user.id,verifiedAt:new Date()}:{})}});await tx.activityLog.create({data:{organizationId:input.organizationId,userId:user.id,action:ActivityAction.STATUS_CHANGE,entityType:"AssetDefect",entityId:defect.id,title:"Asset defect status changed",description:`${defect.reference}: ${defect.status} → ${updated.status}`,metadata:{assetId:defect.assetId,previousStatus:defect.status,status:updated.status}}});await recordOfflineSubmission(tx,input,"ASSET_DEFECT_STATUS",updated.id);return updated});
}

export async function scheduleAssetMaintenanceService(input:{organizationId:string;userId:string;assetId:string;defectId?:string|null;type:AssetMaintenanceType;title:string;scheduledAt:Date;dueAt:Date;technicianId?:string|null;serviceProvider?:string|null;workOrderReference?:string|null}){
  const[asset,creator,technician,defect]=await Promise.all([tenantAsset(input.organizationId,input.assetId),prisma.user.findFirst({where:{id:input.userId,organizationId:input.organizationId,isActive:true}}),input.technicianId?prisma.user.findFirst({where:{id:input.technicianId,organizationId:input.organizationId,isActive:true}}):null,input.defectId?prisma.assetDefect.findFirst({where:{id:input.defectId,organizationId:input.organizationId,assetId:input.assetId}}):null]);if(!asset||!creator||(input.technicianId&&!technician)||(input.defectId&&!defect))throw new Error("Select a valid tenant asset, defect, and technician.");if([input.scheduledAt,input.dueAt].some(value=>Number.isNaN(value.getTime()))||input.dueAt<input.scheduledAt)throw new Error("Maintenance due date must be on or after its scheduled date.");
  const record=await prisma.$transaction(async tx=>{const created=await tx.assetMaintenanceRecord.create({data:{organizationId:input.organizationId,assetId:asset.id,defectId:input.defectId,type:input.type,title:input.title,scheduledAt:input.scheduledAt,dueAt:input.dueAt,technicianId:input.technicianId,serviceProvider:input.serviceProvider,workOrderReference:input.workOrderReference}});if(defect&&defect.status!==AssetDefectStatus.REPAIR_PLANNED)await tx.assetDefect.update({where:{id:defect.id},data:{status:AssetDefectStatus.REPAIR_PLANNED,repairPlan:input.title}});await tx.activityLog.create({data:{organizationId:input.organizationId,userId:creator.id,action:ActivityAction.CREATE,entityType:"AssetMaintenanceRecord",entityId:created.id,title:"Asset maintenance scheduled",description:`${asset.reference} — ${created.title}`,metadata:{assetId:asset.id,type:created.type,dueAt:created.dueAt,technicianId:created.technicianId,defectId:created.defectId}}});return created});if(record.technicianId&&record.technicianId!==creator.id)await createNotification({organizationId:input.organizationId,userId:record.technicianId,type:NotificationType.ASSIGNMENT,title:"Asset maintenance assigned",message:`${asset.reference} — ${record.title} is due ${record.dueAt.toLocaleDateString("en-US")}.`,link:`/assets/${asset.id}`}).catch(()=>undefined);return record;
}

export async function completeAssetMaintenanceService(input:{organizationId:string;userId:string;recordId:string;completedAt:Date;workSummary:string;evidenceReference:string;downtimeHours?:number|null;offlineSubmission?:OfflineSubmissionInput}){
  const[record,user]=await Promise.all([prisma.assetMaintenanceRecord.findFirst({where:{id:input.recordId,organizationId:input.organizationId},include:{asset:true,defect:true}}),prisma.user.findFirst({where:{id:input.userId,organizationId:input.organizationId,isActive:true}})]);if(!record||!user)throw new Error("Maintenance record not found in this organization.");if(!canTransitionMaintenanceStatus(record.status,AssetMaintenanceStatus.COMPLETED))throw new Error("This maintenance record cannot be completed from its current status.");if(Number.isNaN(input.completedAt.getTime())||input.completedAt>new Date())throw new Error("Completion date cannot be invalid or in the future.");if(input.downtimeHours!==null&&input.downtimeHours!==undefined&&(input.downtimeHours<0||input.downtimeHours>100000))throw new Error("Downtime hours must be a valid non-negative value.");const nextMaintenanceDueAt=nextAssetDueDate(input.completedAt,record.asset.maintenanceIntervalDays);
  return prisma.$transaction(async tx=>{const completed=await tx.assetMaintenanceRecord.update({where:{id:record.id},data:{status:AssetMaintenanceStatus.COMPLETED,completedAt:input.completedAt,workSummary:input.workSummary,evidenceReference:input.evidenceReference,downtimeHours:input.downtimeHours,nextMaintenanceDueAt}});await tx.asset.update({where:{id:record.assetId},data:{lastMaintenanceAt:input.completedAt,nextMaintenanceDueAt,maintenanceReminderAt:null,maintenanceOverdueAt:null}});if(record.defectId&&record.defect&&record.defect.status===AssetDefectStatus.REPAIR_PLANNED)await tx.assetDefect.update({where:{id:record.defectId},data:{status:AssetDefectStatus.REPAIRED,repairPlan:record.defect.repairPlan??input.workSummary}});await tx.activityLog.create({data:{organizationId:input.organizationId,userId:user.id,action:ActivityAction.UPDATE,entityType:"AssetMaintenanceRecord",entityId:completed.id,title:"Asset maintenance completed",description:`${record.asset.reference} — ${completed.title}`,metadata:{assetId:record.assetId,completedAt:completed.completedAt,nextMaintenanceDueAt,downtimeHours:input.downtimeHours}}});await recordOfflineSubmission(tx,input,"ASSET_MAINTENANCE_COMPLETE",completed.id);return completed});
}

export async function changeAssetMaintenanceStatusService(input:{organizationId:string;userId:string;recordId:string;status:AssetMaintenanceStatus;reason:string;offlineSubmission?:OfflineSubmissionInput}){
  const[record,user]=await Promise.all([prisma.assetMaintenanceRecord.findFirst({where:{id:input.recordId,organizationId:input.organizationId},include:{asset:true}}),prisma.user.findFirst({where:{id:input.userId,organizationId:input.organizationId,isActive:true}})]);if(!record||!user)throw new Error("Maintenance record not found in this organization.");if(!canTransitionMaintenanceStatus(record.status,input.status))throw new Error(`Maintenance cannot move from ${record.status.replaceAll("_"," ")} to ${input.status.replaceAll("_"," ")}.`);if(input.status!==AssetMaintenanceStatus.IN_PROGRESS&&input.status!==AssetMaintenanceStatus.CANCELLED)throw new Error("Use the completion workflow to complete maintenance work.");if(!input.reason.trim())throw new Error("Record the reason for the maintenance status change.");
  return prisma.$transaction(async tx=>{const updated=await tx.assetMaintenanceRecord.update({where:{id:record.id},data:{status:input.status,...(input.status===AssetMaintenanceStatus.IN_PROGRESS?{startedAt:new Date()}: {})}});if(input.status===AssetMaintenanceStatus.IN_PROGRESS)await tx.asset.update({where:{id:record.assetId},data:{status:AssetStatus.UNDER_MAINTENANCE}});await tx.activityLog.create({data:{organizationId:input.organizationId,userId:user.id,action:ActivityAction.STATUS_CHANGE,entityType:"AssetMaintenanceRecord",entityId:record.id,title:"Asset maintenance status changed",description:`${record.asset.reference}: ${record.status} → ${updated.status}: ${input.reason}`,metadata:{assetId:record.assetId,previousStatus:record.status,status:updated.status,reason:input.reason}}});await recordOfflineSubmission(tx,input,"ASSET_MAINTENANCE_STATUS",updated.id);return updated});
}

export async function createCapaFromAssetDefectService(input:{organizationId:string;userId:string;defectId:string;title:string;description?:string|null;assignedToId:string;dueDate:Date}){
  const[defect,creator,assignee]=await Promise.all([prisma.assetDefect.findFirst({where:{id:input.defectId,organizationId:input.organizationId},include:{asset:true}}),prisma.user.findFirst({where:{id:input.userId,organizationId:input.organizationId,isActive:true}}),prisma.user.findFirst({where:{id:input.assignedToId,organizationId:input.organizationId,isActive:true}})]);if(!defect||!creator||!assignee)throw new Error("Select a valid tenant defect and corrective-action owner.");if(defect.correctiveActionId)throw new Error("This defect already has a linked corrective action.");if(input.dueDate<=new Date())throw new Error("Corrective-action due date must be in the future.");const action=await prisma.$transaction(async tx=>{const created=await tx.correctiveAction.create({data:{title:input.title,description:input.description,status:Status.OPEN,riskLevel:defect.severity,dueDate:input.dueDate,assignedToId:assignee.id}});await tx.assetDefect.update({where:{id:defect.id},data:{correctiveActionId:created.id}});await tx.activityLog.create({data:{organizationId:input.organizationId,userId:creator.id,action:ActivityAction.CREATE,entityType:"CorrectiveAction",entityId:created.id,title:"Asset-defect CAPA created",description:`${defect.reference} — ${created.title}`,metadata:{assetId:defect.assetId,defectId:defect.id,assignedToId:assignee.id,dueDate:created.dueDate}}});return created});await createNotification({organizationId:input.organizationId,userId:assignee.id,type:NotificationType.ASSIGNMENT,title:"Asset corrective action assigned",message:`${defect.asset.reference} — ${action.title}`,link:`/actions/${action.id}`}).catch(()=>undefined);return action;
}

export async function getAssetDashboardService(organizationId:string,now=new Date()){
  const assets=await prisma.asset.findMany({where:{organizationId},include:{site:true,owner:true,inspections:{orderBy:{inspectedAt:"desc"},take:1},defects:{where:{status:{in:activeDefectStatuses}}},maintenanceRecords:{where:{status:{in:[AssetMaintenanceStatus.SCHEDULED,AssetMaintenanceStatus.IN_PROGRESS,AssetMaintenanceStatus.OVERDUE]}}}},orderBy:{name:"asc"}});const active=assets.filter(asset=>asset.status!==AssetStatus.RETIRED);return{assets,metrics:{total:assets.length,safetyCritical:active.filter(asset=>asset.isSafetyCritical).length,outOfService:active.filter(asset=>asset.status===AssetStatus.OUT_OF_SERVICE||asset.status===AssetStatus.QUARANTINED).length,inspectionOverdue:active.filter(asset=>asset.nextInspectionDueAt<now).length,maintenanceOverdue:active.filter(asset=>asset.nextMaintenanceDueAt<now||asset.maintenanceRecords.some(record=>record.dueAt<now)).length,openDefects:active.reduce((sum,asset)=>sum+asset.defects.length,0)}};
}

export async function processAssetMonitoring(now=new Date()){
  const horizon=nextAssetDueDate(now,14);const[assets,maintenance]=await Promise.all([prisma.asset.findMany({where:{status:{not:AssetStatus.RETIRED},OR:[{nextInspectionDueAt:{lte:horizon}},{nextMaintenanceDueAt:{lte:horizon}}]},include:{owner:true}}),prisma.assetMaintenanceRecord.findMany({where:{status:{in:[AssetMaintenanceStatus.SCHEDULED,AssetMaintenanceStatus.IN_PROGRESS]},dueAt:{lt:now}},include:{asset:true,technician:true}})]);const result={assetsChecked:assets.length,maintenanceChecked:maintenance.length,notificationsSent:0,maintenanceOverdue:0};for(const asset of assets){if(!asset.ownerId)continue;for(const kind of ["inspection","maintenance"] as const){const dueAt=kind==="inspection"?asset.nextInspectionDueAt:asset.nextMaintenanceDueAt;if(dueAt>horizon)continue;const overdue=dueAt<now,reminderAt=kind==="inspection"?asset.inspectionReminderAt:asset.maintenanceReminderAt,overdueAt=kind==="inspection"?asset.inspectionOverdueAt:asset.maintenanceOverdueAt;if((overdue&&overdueAt)||(!overdue&&reminderAt))continue;const notification=await createNotification({organizationId:asset.organizationId,userId:asset.ownerId,type:overdue?NotificationType.CRITICAL:NotificationType.DUE_DATE,title:`Asset ${kind} ${overdue?"overdue":"due soon"}`,message:`${asset.reference} — ${asset.name} is due ${dueAt.toLocaleDateString("en-US")}.`,link:`/assets/${asset.id}`}).catch(()=>null);if(!notification)continue;await prisma.asset.update({where:{id:asset.id},data:kind==="inspection"?(overdue?{inspectionOverdueAt:now}:{inspectionReminderAt:now}):(overdue?{maintenanceOverdueAt:now}:{maintenanceReminderAt:now})});result.notificationsSent++}}for(const record of maintenance){const updated=await prisma.assetMaintenanceRecord.updateMany({where:{id:record.id,status:{in:[AssetMaintenanceStatus.SCHEDULED,AssetMaintenanceStatus.IN_PROGRESS]}},data:{status:AssetMaintenanceStatus.OVERDUE}});if(!updated.count)continue;result.maintenanceOverdue++;const recipient=record.technicianId??record.asset.ownerId;if(recipient&&!record.overdueNotifiedAt){const sent=await createNotification({organizationId:record.organizationId,userId:recipient,type:NotificationType.CRITICAL,title:"Asset maintenance work overdue",message:`${record.asset.reference} — ${record.title} was due ${record.dueAt.toLocaleDateString("en-US")}.`,link:`/assets/${record.assetId}`}).catch(()=>null);if(sent){await prisma.assetMaintenanceRecord.update({where:{id:record.id},data:{overdueNotifiedAt:now}});result.notificationsSent++}}}return result;
}
