CREATE TYPE "ResearchPanelStatus" AS ENUM ('ACTIVE','PAUSED','ARCHIVED');
CREATE TYPE "ResearchPanelMemberStatus" AS ENUM ('ACTIVE','OPTED_OUT','SUPPRESSED','INACTIVE');
CREATE TYPE "ResearchConsentEventType" AS ENUM ('GRANTED','RENEWED','WITHDRAWN','EXPIRED');
CREATE TYPE "ResearchCampaignQuotaStatus" AS ENUM ('OPEN','FILLED','CLOSED');
CREATE TABLE "ResearchPanel" ("id" TEXT NOT NULL,"organizationId" TEXT NOT NULL,"name" TEXT NOT NULL,"description" TEXT,"lawfulPurpose" TEXT NOT NULL,"status" "ResearchPanelStatus" NOT NULL DEFAULT 'ACTIVE',"createdById" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "ResearchPanel_pkey" PRIMARY KEY ("id"));
CREATE TABLE "ResearchPanelMember" ("id" TEXT NOT NULL,"organizationId" TEXT NOT NULL,"panelId" TEXT NOT NULL,"email" TEXT NOT NULL,"name" TEXT,"externalRef" TEXT,"attributes" JSONB NOT NULL,"status" "ResearchPanelMemberStatus" NOT NULL DEFAULT 'ACTIVE',"consentExpiresAt" TIMESTAMP(3),"qualityScore" DOUBLE PRECISION NOT NULL DEFAULT 100,"managedById" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "ResearchPanelMember_pkey" PRIMARY KEY ("id"));
CREATE TABLE "ResearchPanelConsentEvent" ("id" TEXT NOT NULL,"organizationId" TEXT NOT NULL,"panelMemberId" TEXT NOT NULL,"type" "ResearchConsentEventType" NOT NULL,"statement" TEXT NOT NULL,"lawfulBasis" TEXT NOT NULL,"effectiveAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"expiresAt" TIMESTAMP(3),"recordedById" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "ResearchPanelConsentEvent_pkey" PRIMARY KEY ("id"));
CREATE TABLE "ResearchCampaignQuota" ("id" TEXT NOT NULL,"organizationId" TEXT NOT NULL,"campaignId" TEXT NOT NULL,"name" TEXT NOT NULL,"attributeKey" TEXT NOT NULL,"attributeValue" TEXT NOT NULL,"target" INTEGER NOT NULL,"status" "ResearchCampaignQuotaStatus" NOT NULL DEFAULT 'OPEN',"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"filledAt" TIMESTAMP(3),CONSTRAINT "ResearchCampaignQuota_pkey" PRIMARY KEY ("id"));
ALTER TABLE "ResearchSurveyInvitation" ADD COLUMN "panelMemberId" TEXT, ADD COLUMN "quotaId" TEXT;
CREATE UNIQUE INDEX "ResearchPanel_organizationId_name_key" ON "ResearchPanel"("organizationId","name");
CREATE INDEX "ResearchPanel_organizationId_status_createdAt_idx" ON "ResearchPanel"("organizationId","status","createdAt");
CREATE UNIQUE INDEX "ResearchPanelMember_panelId_email_key" ON "ResearchPanelMember"("panelId","email");
CREATE INDEX "ResearchPanelMember_organizationId_status_consentExpiresAt_idx" ON "ResearchPanelMember"("organizationId","status","consentExpiresAt");
CREATE INDEX "ResearchPanelMember_panelId_status_qualityScore_idx" ON "ResearchPanelMember"("panelId","status","qualityScore");
CREATE INDEX "ResearchPanelConsentEvent_organizationId_type_effectiveAt_idx" ON "ResearchPanelConsentEvent"("organizationId","type","effectiveAt");
CREATE INDEX "ResearchPanelConsentEvent_panelMemberId_effectiveAt_idx" ON "ResearchPanelConsentEvent"("panelMemberId","effectiveAt");
CREATE UNIQUE INDEX "ResearchCampaignQuota_campaignId_attributeKey_attributeValue_key" ON "ResearchCampaignQuota"("campaignId","attributeKey","attributeValue");
CREATE INDEX "ResearchCampaignQuota_organizationId_status_createdAt_idx" ON "ResearchCampaignQuota"("organizationId","status","createdAt");
CREATE INDEX "ResearchCampaignQuota_campaignId_status_idx" ON "ResearchCampaignQuota"("campaignId","status");
CREATE INDEX "ResearchSurveyInvitation_panelMemberId_status_idx" ON "ResearchSurveyInvitation"("panelMemberId","status");
CREATE INDEX "ResearchSurveyInvitation_quotaId_status_idx" ON "ResearchSurveyInvitation"("quotaId","status");
ALTER TABLE "ResearchPanel" ADD CONSTRAINT "ResearchPanel_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ResearchPanel" ADD CONSTRAINT "ResearchPanel_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "ResearchPanelMember" ADD CONSTRAINT "ResearchPanelMember_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ResearchPanelMember" ADD CONSTRAINT "ResearchPanelMember_panelId_fkey" FOREIGN KEY ("panelId") REFERENCES "ResearchPanel"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ResearchPanelMember" ADD CONSTRAINT "ResearchPanelMember_managedById_fkey" FOREIGN KEY ("managedById") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "ResearchPanelConsentEvent" ADD CONSTRAINT "ResearchPanelConsentEvent_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ResearchPanelConsentEvent" ADD CONSTRAINT "ResearchPanelConsentEvent_panelMemberId_fkey" FOREIGN KEY ("panelMemberId") REFERENCES "ResearchPanelMember"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ResearchPanelConsentEvent" ADD CONSTRAINT "ResearchPanelConsentEvent_recordedById_fkey" FOREIGN KEY ("recordedById") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "ResearchCampaignQuota" ADD CONSTRAINT "ResearchCampaignQuota_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ResearchCampaignQuota" ADD CONSTRAINT "ResearchCampaignQuota_campaignId_fkey" FOREIGN KEY ("campaignId") REFERENCES "ResearchSurveyCampaign"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ResearchSurveyInvitation" ADD CONSTRAINT "ResearchSurveyInvitation_panelMemberId_fkey" FOREIGN KEY ("panelMemberId") REFERENCES "ResearchPanelMember"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "ResearchSurveyInvitation" ADD CONSTRAINT "ResearchSurveyInvitation_quotaId_fkey" FOREIGN KEY ("quotaId") REFERENCES "ResearchCampaignQuota"("id") ON DELETE SET NULL ON UPDATE CASCADE;
