ALTER TABLE "ResearchSamplingExecution"
ADD COLUMN "minimumInterviewMinutes" DOUBLE PRECISION NOT NULL DEFAULT 2,
ADD COLUMN "maximumSyncDelayHours" INTEGER NOT NULL DEFAULT 72,
ADD COLUMN "maximumLocationAccuracyM" DOUBLE PRECISION NOT NULL DEFAULT 250,
ADD COLUMN "locationClusterRadiusM" DOUBLE PRECISION NOT NULL DEFAULT 25;
