import { EntityCustomFormSubmissions } from "@/features/forms/entity-custom-form-submissions";
import { CriticalControlCapaForm, CriticalControlVerificationForm } from "@/features/assurance/sif-forms";
import { getCurrentUserPermissions, requirePermission } from "@/lib/permissions";
import { prisma } from "@/lib/prisma";
import { hasSubscriptionFeature } from "@/lib/subscription";
import { getCurrentUserTenant } from "@/lib/tenant";
import { getPublishedRuntimeForms } from "@/modules/forms/runtime-form.service";
import { ConfigurableFormModule, CriticalControlVerificationResult, DocumentEntityType, PermissionKey } from "@prisma/client";
import { ArrowLeft, ShieldCheck } from "lucide-react";
import Link from "next/link";
import { notFound } from "next/navigation";

export default async function CriticalControlDetailPage({params}:{params:Promise<{id:string}>}){
  await requirePermission(PermissionKey.VIEW_SIF_INTELLIGENCE);const[{id},{organizationId,user},permissions]=await Promise.all([params,getCurrentUserTenant(),getCurrentUserPermissions()]);const canManage=permissions.includes(PermissionKey.MANAGE_CRITICAL_CONTROLS),canCreateCapa=permissions.includes(PermissionKey.CREATE_CAPA);
  const[control,users,forms,uploadEnabled]=await Promise.all([prisma.criticalControlStandard.findFirst({where:{id,organizationId},include:{site:true,department:true,owner:true,createdBy:true,verifications:{include:{verifiedBy:true,correctiveAction:true},orderBy:{verifiedAt:"desc"}}}}),prisma.user.findMany({where:{organizationId,isActive:true},select:{id:true,name:true},orderBy:{name:"asc"}}),getPublishedRuntimeForms(organizationId,ConfigurableFormModule.SIF_ASSURANCE),hasSubscriptionFeature(organizationId,"DOCUMENT_UPLOAD")]);if(!control)notFound();const latest=control.verifications[0]??null;
  return <div><Link href="/assurance/sif/controls" className="inline-flex items-center gap-2 text-sm text-slate-400"><ArrowLeft size={16}/>Critical Control Library</Link><div className="mt-6 flex flex-wrap justify-between gap-4"><div><p className="flex items-center gap-2 text-sm text-cyan-300"><ShieldCheck size={17}/>{control.code} · {control.category.replaceAll("_"," ")}</p><h1 className="mt-2 text-4xl font-bold">{control.name}</h1><p className="mt-2 text-slate-400">{control.site?.name||"Organization-wide"}{control.department?` · ${control.department.name}`:""} · Owner {control.owner?.name||"unassigned"}</p></div><span className={`h-fit rounded-full px-4 py-2 text-sm ${latest?.result===CriticalControlVerificationResult.FAILED?"bg-red-400/15 text-red-300":latest?.result===CriticalControlVerificationResult.DEGRADED?"bg-amber-400/15 text-amber-300":latest?.result===CriticalControlVerificationResult.EFFECTIVE?"bg-emerald-400/15 text-emerald-300":"bg-white/5 text-slate-400"}`}>{latest?.result.replaceAll("_"," ")||"NOT VERIFIED"}</span></div>
    <div className="mt-7 grid gap-4 sm:grid-cols-4"><Metric label="Frequency" value={`${control.verificationFrequencyDays} days`}/><Metric label="Next due" value={control.nextVerificationDueAt.toLocaleDateString()} danger={control.nextVerificationDueAt<new Date()}/><Metric label="Verifications" value={String(control.verifications.length)}/><Metric label="Created by" value={control.createdBy.name}/></div>
    <section className="mt-8 rounded-3xl border border-white/10 bg-white/5 p-6"><h2 className="text-xl font-semibold">Control performance definition</h2>{control.description&&<p className="mt-3 text-sm text-slate-400">{control.description}</p>}<Text label="Performance standard" value={control.performanceStandard}/><Text label="Field verification prompt" value={control.verificationPrompt}/></section>
    {canManage&&<div className="mt-8"><CriticalControlVerificationForm controlId={control.id} forms={forms}/></div>}
    {latest&&<EntityCustomFormSubmissions organizationId={organizationId} userId={user.id} module={ConfigurableFormModule.SIF_ASSURANCE} entityType={DocumentEntityType.SIF_ASSURANCE} entityId={latest.id} canUpload={canManage&&uploadEnabled} className="mt-8 space-y-6"/>}
    {latest&&canManage&&canCreateCapa&&!latest.correctiveActionId&&latest.result!==CriticalControlVerificationResult.EFFECTIVE&&<div className="mt-8"><CriticalControlCapaForm verificationId={latest.id} controlId={control.id} controlName={control.name} users={users}/></div>}
    <section className="mt-8 rounded-3xl border border-white/10 bg-white/5 p-6"><h2 className="text-xl font-semibold">Verification history</h2><div className="mt-5 space-y-4">{control.verifications.map(verification=><article key={verification.id} className="rounded-2xl border border-white/10 bg-slate-950/40 p-5"><div className="flex flex-wrap justify-between gap-3"><div><p className="font-semibold">{verification.result.replaceAll("_"," ")}</p><p className="mt-1 text-xs text-slate-500">{verification.verifiedAt.toLocaleDateString()} · {verification.verifiedBy.name} · Next due {verification.nextDueAt.toLocaleDateString()}</p></div>{verification.correctiveAction&&<Link href={`/actions/${verification.correctiveAction.id}`} className="text-sm text-cyan-300">Linked CAPA →</Link>}</div>{verification.evidenceReference&&<Text label="Evidence" value={verification.evidenceReference}/>} {verification.findings&&<Text label="Findings" value={verification.findings}/>} {verification.immediateAction&&<Text label="Immediate action" value={verification.immediateAction}/>}</article>)}{!control.verifications.length&&<p className="text-sm text-slate-500">No field verification has been recorded.</p>}</div></section>
  </div>;
}
function Metric({label,value,danger=false}:{label:string;value:string;danger?:boolean}){return <div className="rounded-2xl border border-white/10 bg-white/5 p-5"><p className="text-xs uppercase text-slate-500">{label}</p><p className={`mt-2 font-semibold ${danger?"text-red-300":""}`}>{value}</p></div>}
function Text({label,value}:{label:string;value:string}){return <div className="mt-5"><p className="text-xs uppercase text-slate-500">{label}</p><p className="mt-1 whitespace-pre-wrap text-sm text-slate-200">{value}</p></div>}
