import { ArrowRight, Menu } from "lucide-react";
import Image from "next/image";
import Link from "next/link";
import type { ReactNode } from "react";

export const marketingNavigation = [
  ["Home", "/"],
  ["About Us", "/about"],
  ["Solutions", "/solutions"],
  ["Industries", "/industries"],
  ["Why Senzilytics", "/why-senzilytics"],
  ["Pricing", "/pricing"],
  ["Contact Us", "/contact"],
] as const;

export function MarketingHeader(){return <header className="sticky top-0 z-50 border-b border-cyan-100/10 bg-[#071421]/88 backdrop-blur-2xl"><div className="mx-auto flex max-w-[90rem] items-center justify-between gap-5 px-5 py-4 sm:px-8 xl:px-10"><Link href="/" aria-label="Senzilytics home" className="group flex items-center gap-3 transition hover:-translate-y-0.5"><Image src="/brand/senzilytics-mark.png" alt="" width={42} height={42} className="rounded-2xl shadow-[0_8px_30px_rgba(34,211,238,.18)]" priority/><span><strong className="block text-lg tracking-tight">Senzilytics</strong><span className="block text-[10px] uppercase tracking-[.22em] text-cyan-200">EHS Intelligence</span></span></Link><nav aria-label="Primary navigation" className="hidden items-center gap-5 xl:flex">{marketingNavigation.map(([label,href])=><Link key={href} href={href} className="text-sm text-slate-200 transition hover:text-cyan-200">{label}</Link>)}</nav><div className="flex items-center gap-2"><Link href="/login" className="hidden rounded-xl px-4 py-2 text-sm text-slate-200 hover:bg-white/5 sm:block">Sign in</Link><Link href="/demo" className="rounded-xl bg-cyan-300 px-4 py-2 text-sm font-semibold text-slate-950 shadow-[0_0_30px_rgba(34,211,238,.18)] transition hover:bg-cyan-200">Try Demo</Link><details className="relative xl:hidden"><summary aria-label="Open navigation" className="list-none rounded-xl border border-white/15 p-2 text-slate-200"><Menu size={20}/></summary><nav aria-label="Mobile navigation" className="absolute right-0 top-12 w-64 space-y-1 rounded-2xl border border-white/10 bg-[#0b1b2c] p-3 shadow-2xl">{marketingNavigation.map(([label,href])=><Link key={href} href={href} className="block rounded-xl px-4 py-3 text-sm hover:bg-white/5">{label}</Link>)}<Link href="/login" className="block rounded-xl px-4 py-3 text-sm hover:bg-white/5">Tenant sign in</Link></nav></details></div></div></header>}

export function MarketingFooter(){return <footer className="border-t border-white/10 bg-[#06111d] px-5 py-12 text-sm sm:px-8"><div className="mx-auto max-w-[90rem]"><div className="grid gap-10 md:grid-cols-[1.3fr_1fr_1fr]"><div><Link href="/" aria-label="Senzilytics home" className="inline-flex items-center gap-3"><Image src="/brand/senzilytics-mark.png" alt="" width={46} height={46} className="rounded-2xl"/><span><strong className="block text-xl tracking-tight text-white">Senzilytics</strong><span className="block text-xs uppercase tracking-[.18em] text-cyan-300">EHS Intelligence</span></span></Link><p className="mt-4 max-w-sm leading-6 text-slate-400">Connected environmental, health, safety, ESG, compliance and risk intelligence for modern organizations.</p></div><div><p className="font-semibold text-white">Company</p><nav className="mt-4 grid gap-3 text-slate-300">{marketingNavigation.slice(1,5).map(([label,href])=><Link key={href} href={href} className="hover:text-cyan-300">{label}</Link>)}</nav></div><div><p className="font-semibold text-white">Explore</p><nav className="mt-4 grid gap-3 text-slate-300"><Link href="/pricing" className="hover:text-cyan-300">Pricing</Link><Link href="/contact" className="hover:text-cyan-300">Contact Us</Link><Link href="/demo" className="hover:text-cyan-300">Interactive Demo</Link><Link href="/privacy" className="hover:text-cyan-300">Privacy Policy</Link><Link href="/support" className="hover:text-cyan-300">Support Center</Link><Link href="/login" className="hover:text-cyan-300">Tenant Sign In</Link></nav></div></div><div className="mt-10 flex flex-wrap justify-between gap-3 border-t border-white/10 pt-6 text-slate-400"><p>© {new Date().getFullYear()} Senzilytics. All rights reserved.</p><p>Safer work. Stronger decisions. Sustainable performance.</p></div></div></footer>}

export function MarketingShell({children}:{children:ReactNode}){return <main className="landing-canvas min-h-screen overflow-hidden text-white"><MarketingHeader/>{children}<MarketingFooter/></main>}

export function MarketingPageHero({eyebrow,title,description,children}:{eyebrow:string;title:string;description:string;children?:ReactNode}){return <section className="relative overflow-hidden border-b border-white/10 px-5 py-20 sm:px-8 lg:py-28 xl:px-10"><div className="landing-grid absolute inset-0 opacity-60"/><div className="landing-orb absolute -right-32 -top-32 h-96 w-96 rounded-full bg-cyan-400/20 blur-3xl"/><div className="relative mx-auto max-w-[90rem]"><p className="text-sm font-semibold uppercase tracking-[.2em] text-cyan-200">{eyebrow}</p><h1 className="mt-5 max-w-5xl text-5xl font-bold tracking-[-.04em] sm:text-6xl lg:text-7xl">{title}</h1><p className="mt-7 max-w-3xl text-lg leading-8 text-slate-200 sm:text-xl">{description}</p>{children}</div></section>}

export function MarketingCta(){return <section className="px-5 py-20 sm:px-8 xl:px-10"><div className="mx-auto grid max-w-[90rem] gap-8 rounded-[2rem] border border-cyan-200/20 bg-[radial-gradient(circle_at_top_right,rgba(34,211,238,.14),transparent_42%)] p-8 sm:p-12 lg:grid-cols-[1fr_auto] lg:items-center"><div><p className="text-sm font-semibold uppercase tracking-[.2em] text-cyan-200">See the system in action</p><h2 className="mt-4 text-3xl font-bold sm:text-5xl">Turn operational activity into confident decisions.</h2><p className="mt-4 max-w-2xl text-slate-300">Explore Senzilytics or talk with us about your organization’s EHS, ESG, compliance and risk priorities.</p></div><div className="flex flex-col gap-3 sm:flex-row lg:flex-col"><Link href="/demo" className="inline-flex items-center justify-center gap-2 rounded-2xl bg-cyan-300 px-7 py-3.5 font-semibold text-slate-950">Try Demo <ArrowRight size={18}/></Link><Link href="/contact" className="rounded-2xl border border-white/20 px-7 py-3.5 text-center font-semibold hover:border-cyan-200/50">Contact Us</Link></div></div></section>}
