import { requirePermission } from "@/lib/permissions";
import { getCurrentUserTenant } from "@/lib/tenant";
import { findTenantAuditProtocols } from "@/modules/audit/audit-governance.repository";
import { PermissionKey } from "@prisma/client";
import { ArrowLeft, FileCheck2, Plus } from "lucide-react";
import Link from "next/link";
import { hasPermission } from "@/lib/permissions";

export default async function AuditProtocolsPage() {
  await requirePermission(PermissionKey.VIEW_AUDITS); const [{ organizationId }, canManage] = await Promise.all([getCurrentUserTenant(), hasPermission(PermissionKey.MANAGE_AUDITS)]); const protocols = await findTenantAuditProtocols(organizationId);
  return <div><Link href="/audits" className="inline-flex items-center gap-2 text-sm text-slate-400 hover:text-white"><ArrowLeft size={16} /> Back to audits</Link><div className="mt-6 flex flex-wrap items-start justify-between gap-5"><div><p className="flex items-center gap-2 text-sm text-cyan-300"><FileCheck2 size={16} /> Controlled Content</p><h1 className="mt-2 text-4xl font-bold">Audit Protocols</h1><p className="mt-2 max-w-3xl text-slate-400">Author and control versioned audit criteria, evidence requirements, scoring logic, and automated finding triggers.</p></div>{canManage && <Link href="/audits/protocols/new" className="inline-flex items-center gap-2 rounded-2xl bg-cyan-300 px-5 py-3 text-sm font-semibold text-slate-950"><Plus size={17} /> Create Protocol</Link>}</div>
    <div className="mt-8 grid gap-5">{protocols.length === 0 ? <p className="rounded-3xl border border-dashed border-white/15 p-12 text-center text-slate-500">No audit protocols yet.</p> : protocols.map((protocol) => { const questions = protocol.sections.reduce((total, section) => total + section._count.questions, 0); return <Link key={protocol.id} href={`/audits/protocols/${protocol.id}`} className="rounded-3xl border border-white/10 bg-white/5 p-6 transition hover:border-cyan-400/30"><div className="flex flex-wrap justify-between gap-4"><div><p className="text-xs text-cyan-300">{protocol.code || "NO CODE"} · VERSION {protocol.version}</p><h2 className="mt-2 text-xl font-semibold">{protocol.name}</h2><p className="mt-2 text-sm text-slate-400">{protocol.description || protocol.standardName || "No description provided."}</p></div><Badge value={protocol.status} /></div><div className="mt-6 grid gap-4 md:grid-cols-4"><Info label="Sections" value={String(protocol._count.sections)} /><Info label="Questions" value={String(questions)} /><Info label="Audit usage" value={String(protocol._count.enterpriseAudits)} /><Info label="Schedule usage" value={String(protocol._count.schedules)} /></div></Link>; })}</div>
  </div>;
}
function pretty(value: string) { return value.replaceAll("_", " "); } function Badge({ value }: { value: string }) { return <span className="h-fit rounded-full border border-cyan-400/30 bg-cyan-400/10 px-3 py-1 text-xs text-cyan-200">{pretty(value)}</span>; } function Info({ label, value }: { label: string; value: string }) { return <div className="rounded-2xl bg-slate-950/40 p-4"><p className="text-xs uppercase text-slate-500">{label}</p><p className="mt-2 text-sm">{value}</p></div>; }
