import { CompetencyAssessmentForm, CompetencyDecisionForm } from "@/features/training/competency-forms";
import { getCurrentUserPermissions, requirePermission } from "@/lib/permissions";
import { prisma } from "@/lib/prisma";
import { getCurrentUserTenant } from "@/lib/tenant";
import { getCompetencyMatrixService } from "@/modules/training/competency.service";
import { CompetencyAssessmentStatus, PermissionKey } from "@prisma/client";
import { ArrowLeft, Grid3X3 } from "lucide-react";
import Link from "next/link";

export default async function CompetencyMatrixPage(){
  await requirePermission(PermissionKey.VIEW_TRAINING);
  const[{organizationId,user},permissions]=await Promise.all([getCurrentUserTenant(),getCurrentUserPermissions()]);
  const canManage=permissions.includes(PermissionKey.MANAGE_TRAINING);
  const[matrix,pending,users,competencies]=await Promise.all([
    getCompetencyMatrixService(organizationId),
    prisma.competencyAssessment.findMany({where:{organizationId,status:CompetencyAssessmentStatus.PENDING_VERIFICATION},include:{competency:true,user:true,assessor:true},orderBy:{createdAt:"asc"}}),
    prisma.user.findMany({where:{organizationId,isActive:true},select:{id:true,name:true,jobTitle:true},orderBy:{name:"asc"}}),
    prisma.competencyDefinition.findMany({where:{organizationId,isActive:true},select:{id:true,code:true,name:true},orderBy:{name:"asc"}}),
  ]);
  return <div><Link href="/training/competencies" className="inline-flex items-center gap-2 text-sm text-slate-400"><ArrowLeft size={16}/>Competency Library</Link><div className="mt-6 flex flex-wrap justify-between gap-4"><div><p className="flex items-center gap-2 text-sm text-cyan-300"><Grid3X3 size={17}/>Workforce Capability Intelligence</p><h1 className="mt-2 text-4xl font-bold">Competency Readiness Matrix</h1><p className="mt-2 max-w-3xl text-slate-400">Compare required and verified proficiency without creating duplicate score or gap records. Readiness is calculated from current evidence.</p></div></div>
    <div className="mt-8 grid gap-4 sm:grid-cols-3 xl:grid-cols-6"><Metric label="Requirements" value={matrix.total}/><Metric label="Ready" value={matrix.satisfied}/><Metric label="Expiring" value={matrix.expiring} warning={matrix.expiring>0}/><Metric label="Gaps" value={matrix.gaps} danger={matrix.gaps>0}/><Metric label="Overdue gaps" value={matrix.overdueGaps} danger={matrix.overdueGaps>0}/><Metric label="Critical gaps" value={matrix.criticalGaps} danger={matrix.criticalGaps>0}/></div>
    <section className="mt-8 overflow-x-auto rounded-3xl border border-white/10 bg-white/5 p-6"><h2 className="text-xl font-semibold">Workforce matrix</h2><table className="mt-5 w-full min-w-[1180px] text-left text-sm"><thead className="text-xs uppercase text-slate-500"><tr><th className="p-3">Person</th><th className="p-3">Site / department</th><th className="p-3">Competency</th><th className="p-3">Required</th><th className="p-3">Verified</th><th className="p-3">Expiry</th><th className="p-3">Gap due</th><th className="p-3">Status</th><th className="p-3">Development path</th></tr></thead><tbody>{matrix.rows.map(row=><tr key={row.id} className="border-t border-white/5"><td className="p-3"><strong>{row.user.name}</strong><span className="block text-xs text-slate-500">{row.user.jobTitle||row.user.role}</span></td><td className="p-3">{row.user.department?.site.name||"Unassigned"}<span className="block text-xs text-slate-500">{row.user.department?.name||"No department"}</span></td><td className="p-3">{row.requirement.competency.name}{row.requirement.competency.isCritical&&<span className="ml-2 text-xs text-red-300">Critical</span>}</td><td className="p-3">{row.requirement.requiredLevel}</td><td className="p-3">{row.actualLevel||"None"}</td><td className="p-3">{row.expiresAt?.toLocaleDateString()||"—"}</td><td className={`p-3 ${row.isOverdue?"font-semibold text-red-300":""}`}>{row.gapDueAt?.toLocaleDateString()||"—"}</td><td className={`p-3 font-semibold ${row.status==="SATISFIED"?"text-emerald-300":row.status==="EXPIRING"?"text-amber-300":"text-red-300"}`}>{row.status}</td><td className="p-3 text-xs text-slate-400">{row.recommendedCourses.length?row.recommendedCourses.map(course=><span key={course.id} className="mr-2 inline-block">{canManage&&row.gapDueAt?<Link className="text-cyan-300 hover:underline" href={`/training/assign?courseId=${encodeURIComponent(course.id)}&userId=${encodeURIComponent(row.user.id)}&dueDate=${row.gapDueAt.toISOString().slice(0,10)}`}>{course.code}</Link>:course.code}</span>):"Assessment required"}</td></tr>)}</tbody></table>{!matrix.rows.length&&<p className="mt-5 text-sm text-slate-500">No scoped competency requirements exist.</p>}</section>
    {canManage&&<div className="mt-8 grid gap-6 xl:grid-cols-2"><CompetencyAssessmentForm users={users} competencies={competencies}/><section className="rounded-3xl border border-white/10 bg-white/5 p-6"><h2 className="text-xl font-semibold">Pending independent verification</h2><p className="mt-1 text-sm text-slate-400">Evidence must be verified by a training manager other than the assessor.</p><div className="mt-5 space-y-4">{pending.map(x=><article key={x.id} className="rounded-2xl border border-white/10 bg-slate-950/40 p-4"><p className="font-medium">{x.user.name} — {x.competency.name}</p><p className="mt-1 text-xs text-slate-500">{x.assessedLevel} · {x.evidenceType.replaceAll("_"," ")} · Assessed by {x.assessor.name}{x.assessorId===user.id?" (requires another manager)":""}</p>{x.evidenceReference&&<p className="mt-2 text-sm text-slate-300">Reference: {x.evidenceReference}</p>}<CompetencyDecisionForm assessmentId={x.id}/></article>)}{!pending.length&&<p className="text-sm text-slate-500">No evidence is awaiting verification.</p>}</div></section></div>}
  </div>;
}
function Metric({label,value,danger=false,warning=false}:{label:string;value:number;danger?:boolean;warning?:boolean}){return <div className="rounded-2xl border border-white/10 bg-white/5 p-5"><p className="text-xs uppercase text-slate-500">{label}</p><p className={`mt-2 text-3xl font-bold ${danger?"text-red-300":warning?"text-amber-300":"text-white"}`}>{value}</p></div>}
