import { createComplianceCalendarTask } from "@/features/compliance/calendar.actions";
import { requirePermission } from "@/lib/permissions";
import { prisma } from "@/lib/prisma";
import { getCurrentUserTenant } from "@/lib/tenant";
import { ComplianceRecurrence, PermissionKey } from "@prisma/client";

const input = "mt-2 w-full rounded-xl border border-white/10 bg-slate-950 px-4 py-3 text-sm outline-none focus:border-cyan-400";
export default async function NewComplianceCalendarTaskPage() {
  await requirePermission(PermissionKey.MANAGE_COMPLIANCE); const { organizationId } = await getCurrentUserTenant();
  const [sites, users, departments] = await Promise.all([prisma.site.findMany({ where: { organizationId }, orderBy: { name: "asc" } }), prisma.user.findMany({ where: { organizationId, isActive: true }, orderBy: { name: "asc" } }), prisma.department.findMany({ where: { site: { organizationId } }, include: { site: true }, orderBy: { name: "asc" } })]);
  return <div className="mx-auto max-w-5xl"><p className="text-sm text-cyan-300">Compliance Calendar</p><h1 className="mt-2 text-4xl font-bold">Create recurring task</h1><form action={createComplianceCalendarTask} className="mt-8 space-y-6 rounded-3xl border border-white/10 bg-white/5 p-7"><div className="grid gap-5 md:grid-cols-2"><Field label="Task title"><input name="title" required className={input}/></Field><Field label="Category"><select name="category" className={input}>{["REGULATORY", "PERMIT", "SAFETY", "ENVIRONMENTAL", "INSPECTION", "TRAINING", "MAINTENANCE", "ESG", "INTERNAL_POLICY"].map(x=><option key={x}>{x.replaceAll("_"," ")}</option>)}</select></Field><Field label="Site"><select name="siteId" required className={input}>{sites.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field><Field label="Department (optional)"><select name="departmentId" className={input}><option value="">All departments</option>{departments.map(x=><option key={x.id} value={x.id}>{x.site.name} — {x.name}</option>)}</select></Field><Field label="Responsible owner"><select name="ownerId" required className={input}>{users.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field><Field label="Escalation owner"><select name="escalationOwnerId" className={input}><option value="">Same as owner</option>{users.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field><Field label="Recurrence"><select name="recurrence" className={input}>{Object.values(ComplianceRecurrence).map(x=><option key={x}>{x.replaceAll("_"," ")}</option>)}</select></Field><Field label="Interval"><input type="number" name="intervalValue" min="1" defaultValue="1" className={input}/></Field><Field label="Start date"><input type="date" name="startDate" required className={input}/></Field><Field label="End date (optional)"><input type="date" name="endDate" className={input}/></Field><Field label="Due time"><input type="time" name="dueTime" className={input}/></Field><Field label="Regulatory reference"><input name="regulatoryReference" className={input}/></Field><Field label="Reminder days before"><input type="number" min="0" name="reminderDaysBefore" defaultValue="7" className={input}/></Field><Field label="Escalation days after"><input type="number" min="0" name="escalationDaysAfter" defaultValue="1" className={input}/></Field></div><Field label="Description"><textarea name="description" rows={3} className={input}/></Field><Field label="Completion instructions"><textarea name="instructions" rows={4} className={input}/></Field><div className="flex flex-wrap gap-6 text-sm"><label><input type="checkbox" name="evidenceRequired" className="mr-2"/>Require evidence</label><label><input type="checkbox" name="approvalRequired" className="mr-2"/>Require supervisor approval</label></div><button className="rounded-xl bg-cyan-300 px-5 py-3 font-semibold text-slate-950">Create Calendar Task</button></form></div>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block text-sm text-slate-300">{label}{children}</label>; }
