import { logActivity } from "@/core/activity-log/activity-log.service";
import { getOpenAIClient, getOpenAIModel } from "@/core/ai/openai.service";
import { prisma } from "@/lib/prisma";
import { findTenantAuditById } from "./audit.repository";
import type { AuditAiDraft, AuditAiStage } from "./audit-ai.types";
import { ActivityAction } from "@prisma/client";

const schema = { type:"object", additionalProperties:false, required:["executiveSummary","focusAreas","evidenceGaps","recommendedQuestions","findingImprovements","managementPriorities","confidence","limitations"], properties:{ executiveSummary:{type:"string"}, focusAreas:{type:"array",items:{type:"object",additionalProperties:false,required:["title","rationale","priority"],properties:{title:{type:"string"},rationale:{type:"string"},priority:{type:"string",enum:["LOW","MEDIUM","HIGH","CRITICAL"]}}}}, evidenceGaps:{type:"array",items:{type:"string"}}, recommendedQuestions:{type:"array",items:{type:"string"}}, findingImprovements:{type:"array",items:{type:"string"}}, managementPriorities:{type:"array",items:{type:"string"}}, confidence:{type:"object",additionalProperties:false,required:["level","rationale"],properties:{level:{type:"string",enum:["LOW","MEDIUM","HIGH"]},rationale:{type:"string"}}}, limitations:{type:"string"} } } as const;

export async function generateAuditAiDraftService(input:{organizationId:string;userId:string;auditId:string;stage:AuditAiStage;advisorContext?:string|null}) {
  const audit = await findTenantAuditById(input.auditId,input.organizationId); if(!audit) throw new Error("Audit not found.");
  const priorFindings = await prisma.enterpriseAuditFinding.findMany({where:{organizationId:input.organizationId,auditId:{not:audit.id},audit:{siteId:audit.siteId}},select:{reference:true,title:true,category:true,severity:true,status:true,isRepeatFinding:true,rootCause:true,dueDate:true},orderBy:{createdAt:"desc"},take:30});
  const context={stage:input.stage,audit:{reference:audit.reference,title:audit.title,status:audit.status,type:audit.auditType,site:audit.site.name,department:audit.department?.name,objectives:audit.objectives,scope:audit.scope,criteria:audit.criteria,scheduledAt:audit.scheduledAt,dueDate:audit.dueDate,score:audit.scorePercentage==null?null:Number(audit.scorePercentage),questionProgress:{total:audit.totalQuestionCount,answered:audit.answeredQuestionCount,failed:audit.failedQuestionCount},sections:audit.sections.map(s=>({title:s.title,questions:s.questions.map(q=>({text:q.questionText,clause:q.standardClause,status:q.status,response:q.response&&{result:q.response.result,comments:q.response.comments},evidenceCount:q.evidence.length}))})),findings:audit.findings.map(f=>({reference:f.reference,title:f.title,severity:f.severity,category:f.category,status:f.status,description:f.description,evidence:f.objectiveEvidence,rootCause:f.rootCause,isRepeat:f.isRepeatFinding,capaLinks:f.correctiveActionLinks.length,riskLinks:f.riskLinks.length}))},priorSiteFindings:priorFindings,advisorContext:input.advisorContext??null};
  const response=await getOpenAIClient().responses.create({model:getOpenAIModel(),instructions:`You are a review-only enterprise Audit assistant. Analyze only supplied tenant-authorized facts. Never invent evidence, standards, events, findings, scores, or conclusions. Never create, approve, assign, close, or modify records. Clearly identify missing evidence and limitations. BEFORE: prioritize prior findings, overdue exposure, focus areas and extra questions. DURING: identify evidence gaps, follow-up questions, and clearer finding language without changing facts. AFTER: draft an executive summary, themes, positive practices only when supported, repeat issues, risk priorities and overall management priorities. Recommendations require qualified human review.`,input:[{role:"user",content:[{type:"input_text",text:`Prepare a ${input.stage} Audit advisory analysis from this context:\n${JSON.stringify(context,null,2)}`}]}],text:{format:{type:"json_schema",name:"enterprise_audit_assistant",strict:true,schema}}});
  if(!response.output_text) throw new Error("The AI service did not return an Audit analysis."); const draft=JSON.parse(response.output_text) as AuditAiDraft;
  await logActivity({organizationId:input.organizationId,userId:input.userId,action:ActivityAction.SYSTEM,entityType:"EnterpriseAuditAI",entityId:audit.id,title:"AI Audit analysis generated",description:`Review-only ${input.stage.toLowerCase()} analysis for ${audit.reference}.`,metadata:{stage:input.stage,model:getOpenAIModel(),responseId:response.id,confidence:draft.confidence.level,automaticallyApplied:false}}); return draft;
}
