import { createAuditProtocol } from "@/features/audits/governance.actions";
import { requirePermission } from "@/lib/permissions";
import { PermissionKey } from "@prisma/client";
import { ArrowLeft, FileCheck2 } from "lucide-react";
import Link from "next/link";

export default async function NewAuditProtocolPage() {
  await requirePermission(PermissionKey.MANAGE_AUDITS);
  return <div className="mx-auto max-w-4xl"><Link href="/audits/protocols" className="inline-flex items-center gap-2 text-sm text-slate-400 hover:text-white"><ArrowLeft size={16} /> Back to protocols</Link><div className="mt-6"><p className="flex items-center gap-2 text-sm text-cyan-300"><FileCheck2 size={16} /> Controlled Content</p><h1 className="mt-2 text-4xl font-bold">Create Audit Protocol</h1><p className="mt-2 text-slate-400">Create the controlled header first, then add sections and questions in the protocol builder.</p></div><form action={createAuditProtocol} className="mt-8 space-y-7 rounded-3xl border border-white/10 bg-white/5 p-7"><div className="grid gap-5 md:grid-cols-2"><Field label="Protocol name"><input name="name" required className={inputClass} /></Field><Field label="Protocol code"><input name="code" className={inputClass} placeholder="ISO45K-INT" /></Field></div><Field label="Description"><textarea name="description" rows={4} className={inputClass} /></Field><div className="grid gap-5 md:grid-cols-3"><Field label="Standard"><input name="standardName" className={inputClass} placeholder="ISO 45001" /></Field><Field label="Standard version"><input name="standardVersion" className={inputClass} /></Field><Field label="Framework"><input name="framework" className={inputClass} /></Field></div><div className="grid gap-5 md:grid-cols-2"><Field label="Effective from"><input type="date" name="effectiveFrom" className={inputClass} /></Field><Field label="Effective to"><input type="date" name="effectiveTo" className={inputClass} /></Field></div><div className="flex justify-end"><button className="rounded-2xl bg-cyan-300 px-6 py-3 text-sm font-semibold text-slate-950">Create and Open Builder</button></div></form></div>;
}
const inputClass = "mt-2 w-full rounded-2xl border border-white/10 bg-slate-950/70 px-4 py-3 text-sm outline-none focus:border-cyan-400/50"; function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block text-sm font-medium text-slate-300">{label}{children}</label>; }
