import { ArrowRight, BarChart3, CheckCircle2, ClipboardCheck, Leaf, SearchCheck, ShieldAlert, Sparkles } from "lucide-react";
import Link from "next/link";

const capabilities = [
  [ShieldAlert, "Operational risk", "Connect observations, incidents, investigations, CAPA, risk and change management."],
  [SearchCheck, "Assurance", "Plan and execute audits and inspections with evidence, findings and verification."],
  [ClipboardCheck, "Compliance", "Control training, obligations, permits, chemicals, documents, workflows and SLAs."],
  [Leaf, "ESG intelligence", "Govern environmental source data, targets, initiatives and disclosure operations."],
];

export default function HomePage() {
  return <main className="min-h-screen bg-slate-950 text-white">
    <header className="border-b border-white/10"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5 sm:px-8"><Link href="/" className="text-xl font-bold">Senzilytics <span className="text-cyan-300">EHS Intelligence</span></Link><nav className="flex items-center gap-3"><Link href="/login" className="rounded-xl px-4 py-2 text-sm text-slate-300 hover:bg-white/5">Sign in</Link><Link href="/demo" className="rounded-xl bg-cyan-300 px-4 py-2 text-sm font-semibold text-slate-950">Try Demo</Link></nav></div></header>
    <section className="relative overflow-hidden px-5 py-20 sm:px-8 lg:py-28"><div className="absolute inset-0 bg-[radial-gradient(circle_at_75%_20%,rgba(34,211,238,.14),transparent_35%)]"/><div className="relative mx-auto grid max-w-7xl gap-12 lg:grid-cols-[1.15fr_.85fr] lg:items-center"><div><p className="text-sm font-semibold uppercase tracking-[.22em] text-cyan-300">EHS, ESG, compliance and risk—connected</p><h1 className="mt-5 max-w-4xl text-5xl font-bold tracking-tight sm:text-7xl">Turn operational signals into safer, stronger business decisions.</h1><p className="mt-7 max-w-3xl text-lg leading-8 text-slate-300">Senzilytics gives organizations one governed platform to prevent harm, strengthen accountability, reduce compliance exposure and deliver credible executive intelligence.</p><div className="mt-9 flex flex-wrap gap-4"><Link href="/demo" className="inline-flex items-center gap-2 rounded-2xl bg-cyan-300 px-6 py-3 font-semibold text-slate-950">Try Interactive Demo <ArrowRight size={18}/></Link><Link href="/login" className="rounded-2xl border border-white/15 px-6 py-3 font-semibold">Tenant Sign In</Link></div></div><div className="rounded-3xl border border-cyan-400/20 bg-white/[.06] p-7 shadow-2xl"><div className="flex items-center gap-3"><Sparkles className="text-cyan-300"/><p className="font-semibold">Executive attention, grounded in operational evidence</p></div><div className="mt-6 grid grid-cols-2 gap-4">{[["Open exposure","Prioritized"],["Cross-module","Connected"],["Tenant data","Isolated"],["Decisions","Auditable"]].map(([a,b])=><div key={a} className="rounded-2xl bg-slate-950/70 p-5"><p className="text-xs text-slate-500">{a}</p><p className="mt-2 text-xl font-semibold text-cyan-200">{b}</p></div>)}</div></div></div></section>
    <section className="border-y border-white/10 bg-white/[.025] px-5 py-20 sm:px-8"><div className="mx-auto max-w-7xl"><p className="text-sm text-cyan-300">One enterprise operating system</p><h2 className="mt-3 max-w-3xl text-3xl font-bold sm:text-5xl">Build maturity without losing traceability.</h2><div className="mt-10 grid gap-5 md:grid-cols-2 xl:grid-cols-4">{capabilities.map(([Icon,title,text])=>{const I=Icon as typeof BarChart3;return <article key={String(title)} className="rounded-3xl border border-white/10 bg-slate-950 p-6"><I className="text-cyan-300"/><h3 className="mt-5 text-xl font-semibold">{String(title)}</h3><p className="mt-3 text-sm leading-6 text-slate-400">{String(text)}</p></article>})}</div></div></section>
    <section className="px-5 py-20 sm:px-8"><div className="mx-auto grid max-w-7xl gap-10 rounded-3xl border border-cyan-400/20 bg-cyan-400/[.06] p-8 lg:grid-cols-[1fr_auto] lg:items-center"><div><h2 className="text-3xl font-bold">Experience Senzilytics before creating your tenant.</h2><p className="mt-3 text-slate-300">Explore realistic, fictional EHS and ESG records in a time-limited, read-only workspace.</p><div className="mt-5 flex flex-wrap gap-4 text-sm text-slate-300">{["No payment required","No customer data","Two-hour access"].map(x=><span key={x} className="inline-flex items-center gap-2"><CheckCircle2 size={16} className="text-cyan-300"/>{x}</span>)}</div></div><Link href="/demo" className="inline-flex items-center justify-center gap-2 rounded-2xl bg-cyan-300 px-6 py-3 font-semibold text-slate-950">Start Demo <ArrowRight size={18}/></Link></div></section>
    <footer className="border-t border-white/10 px-5 py-8 text-sm text-slate-500 sm:px-8"><div className="mx-auto flex max-w-7xl flex-wrap justify-between gap-3"><p>© {new Date().getFullYear()} Senzilytics. EHS Intelligence.</p><div className="flex gap-5"><Link href="/login">Tenant sign in</Link><Link href="/demo">Try demo</Link></div></div></footer>
  </main>;
}
