import { ArrowRight, BarChart3, CalendarCheck, CheckCircle2, ClipboardCheck, CloudCog, GraduationCap, Leaf, Mail, Menu, Radar, SearchCheck, ShieldAlert, Sparkles, Workflow } from "lucide-react";
import Link from "next/link";

const solutions = [
  [ShieldAlert, "Safety & Incident Management", "Capture observations, investigate incidents, identify causes and move corrective actions through verified closure."],
  [SearchCheck, "Audits & Inspections", "Plan programs, build protocols, collect evidence, manage findings and measure assurance performance."],
  [CalendarCheck, "Compliance Calendar", "Operationalize recurring legal and business obligations with ownership, reminders, evidence and escalation."],
  [BarChart3, "Risk & Change", "Connect enterprise risk, JSA/JHA, controls and management of change to the work happening in the field."],
  [GraduationCap, "Training Intelligence", "Define requirements, assign learning, monitor competency and prevent certification gaps."],
  [Leaf, "Environment & ESG", "Govern environmental metrics, targets and disclosure evidence with transparent data lineage."],
  [Workflow, "CAPA & Workflows", "Standardize accountability with approvals, SLAs, notifications and cross-module traceability."],
  [CloudCog, "Connected Field Data", "Collect operational information online or offline and synchronize it safely when connectivity returns."],
];

const navigation = [["About Us", "#about"], ["Senzilytics Solutions", "#solutions"], ["Why Senzilytics", "#why"], ["Contact Us", "#contact"]];

export default function HomePage() {
  return <main className="min-h-screen overflow-hidden bg-slate-950 text-white">
    <header className="sticky top-0 z-50 border-b border-white/10 bg-slate-950/80 backdrop-blur-2xl"><div className="mx-auto flex max-w-7xl items-center justify-between gap-5 px-5 py-4 sm:px-8"><Link href="/" className="group flex items-center gap-3"><span className="relative flex h-10 w-10 items-center justify-center rounded-2xl border border-cyan-300/30 bg-cyan-300/10"><Radar size={22} className="text-cyan-300"/><span className="absolute inset-0 animate-ping rounded-2xl border border-cyan-300/20 [animation-duration:3s]"/></span><span><strong className="block text-lg tracking-tight">Senzilytics</strong><span className="block text-[10px] uppercase tracking-[.22em] text-cyan-300">EHS Intelligence</span></span></Link><nav className="hidden items-center gap-6 lg:flex">{navigation.map(([label,href])=><a key={href} href={href} className="text-sm text-slate-300 transition hover:text-cyan-300">{label}</a>)}</nav><div className="flex items-center gap-2"><Link href="/login" className="hidden rounded-xl px-4 py-2 text-sm text-slate-300 hover:bg-white/5 sm:block">Sign in</Link><Link href="/demo" className="rounded-xl bg-cyan-300 px-4 py-2 text-sm font-semibold text-slate-950 shadow-[0_0_30px_rgba(34,211,238,.18)] transition hover:bg-cyan-200">Try Demo</Link><details className="relative lg:hidden"><summary aria-label="Open navigation" className="list-none rounded-xl border border-white/10 p-2 text-slate-300"><Menu size={20}/></summary><nav className="absolute right-0 top-12 w-64 space-y-1 rounded-2xl border border-white/10 bg-slate-900 p-3 shadow-2xl">{navigation.map(([label,href])=><a key={href} href={href} className="block rounded-xl px-4 py-3 text-sm hover:bg-white/5">{label}</a>)}<Link href="/login" className="block rounded-xl px-4 py-3 text-sm hover:bg-white/5">Tenant sign in</Link></nav></details></div></div></header>

    <section className="relative px-5 pb-24 pt-20 sm:px-8 lg:pb-32 lg:pt-28"><div className="landing-grid absolute inset-0 opacity-40"/><div className="landing-orb absolute -left-40 top-20 h-96 w-96 rounded-full bg-cyan-400/20 blur-3xl"/><div className="landing-orb-reverse absolute -right-32 top-0 h-[30rem] w-[30rem] rounded-full bg-blue-600/20 blur-3xl"/><div className="relative mx-auto grid max-w-7xl gap-16 lg:grid-cols-[1.08fr_.92fr] lg:items-center"><div className="landing-rise"><p className="inline-flex items-center gap-2 rounded-full border border-cyan-300/20 bg-cyan-300/[.07] px-4 py-2 text-xs font-semibold uppercase tracking-[.18em] text-cyan-200"><Sparkles size={15}/>Connected operational intelligence</p><h1 className="mt-7 max-w-5xl text-5xl font-bold tracking-[-.04em] sm:text-7xl lg:text-[5.3rem] lg:leading-[.98]">See risk sooner.<br/><span className="bg-gradient-to-r from-cyan-300 via-sky-300 to-emerald-300 bg-clip-text text-transparent">Act with confidence.</span></h1><p className="mt-7 max-w-2xl text-lg leading-8 text-slate-300">Senzilytics unifies EHS, ESG, compliance and enterprise risk—turning field activity into governed workflows and decision-ready executive intelligence.</p><div className="mt-9 flex flex-wrap gap-4"><Link href="/demo" className="inline-flex items-center gap-2 rounded-2xl bg-cyan-300 px-6 py-3.5 font-semibold text-slate-950 shadow-[0_0_45px_rgba(34,211,238,.2)] transition hover:-translate-y-0.5 hover:bg-cyan-200">Explore Interactive Demo <ArrowRight size={18}/></Link><a href="#solutions" className="rounded-2xl border border-white/15 bg-white/[.03] px-6 py-3.5 font-semibold backdrop-blur transition hover:border-cyan-300/40">Explore Solutions</a></div><div className="mt-10 flex flex-wrap gap-x-7 gap-y-3 text-sm text-slate-400">{["Tenant-isolated", "Evidence-driven", "Mobile-ready", "Online + offline"].map(item=><span key={item} className="inline-flex items-center gap-2"><CheckCircle2 size={16} className="text-emerald-300"/>{item}</span>)}</div></div>
      <div className="landing-float relative"><div className="absolute -inset-8 rounded-[2.5rem] bg-gradient-to-r from-cyan-400/10 to-blue-500/10 blur-2xl"/><div className="relative overflow-hidden rounded-[2rem] border border-cyan-300/20 bg-slate-900/80 p-5 shadow-[0_30px_100px_rgba(0,0,0,.45)] backdrop-blur-xl"><div className="flex items-center justify-between border-b border-white/10 pb-4"><div><p className="text-xs uppercase tracking-[.18em] text-slate-500">Executive Risk Overview</p><p className="mt-1 font-semibold">Enterprise Intelligence</p></div><span className="flex items-center gap-2 text-xs text-emerald-300"><span className="h-2 w-2 animate-pulse rounded-full bg-emerald-300"/>Live signals</span></div><div className="mt-5 grid grid-cols-2 gap-3">{[["Open exposure","Prioritized","text-amber-300"],["Compliance","94%","text-emerald-300"],["Audit assurance","Strong","text-cyan-300"],["Actions overdue","7","text-red-300"]].map(([a,b,c])=><div key={a} className="rounded-2xl border border-white/5 bg-slate-950/70 p-4"><p className="text-xs text-slate-500">{a}</p><p className={`mt-2 text-xl font-semibold ${c}`}>{b}</p></div>)}</div><div className="mt-4 rounded-2xl border border-white/5 bg-slate-950/70 p-5"><div className="flex justify-between text-xs"><span className="text-slate-400">12-month assurance trend</span><span className="text-cyan-300">+18%</span></div><div className="mt-5 flex h-28 items-end gap-2">{[32,45,40,58,52,67,62,72,69,82,78,91].map((height,index)=><span key={index} className="landing-bar flex-1 rounded-t bg-gradient-to-t from-cyan-600 to-cyan-300" style={{height:`${height}%`,animationDelay:`${index*70}ms`}}/>)}</div></div><div className="mt-4 grid grid-cols-3 gap-3 text-center text-xs text-slate-400">{["Field signals","Governed workflows","Executive action"].map((item,index)=><div key={item} className="rounded-xl bg-white/[.04] p-3"><span className="mb-2 block text-cyan-300">0{index+1}</span>{item}</div>)}</div></div></div>
    </div></section>

    <section id="about" className="scroll-mt-24 border-y border-white/10 bg-white/[.025] px-5 py-24 sm:px-8"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><div><p className="text-sm font-semibold uppercase tracking-[.2em] text-cyan-300">About Us</p><h2 className="mt-4 text-4xl font-bold tracking-tight sm:text-5xl">Technology for safer work and stronger organizations.</h2></div><div className="space-y-5 text-lg leading-8 text-slate-300"><p>Senzilytics is a cloud-based EHS, ESG, compliance and risk-management platform designed to connect frontline activity with accountable leadership.</p><p>We help organizations replace fragmented spreadsheets and disconnected systems with one secure operating environment for reporting, assurance, compliance, learning and continuous improvement.</p></div></div></section>

    <section id="solutions" className="scroll-mt-24 px-5 py-24 sm:px-8"><div className="mx-auto max-w-7xl"><div className="max-w-3xl"><p className="text-sm font-semibold uppercase tracking-[.2em] text-cyan-300">Senzilytics Solutions</p><h2 className="mt-4 text-4xl font-bold sm:text-5xl">One connected system. Every operational signal.</h2><p className="mt-5 text-lg leading-8 text-slate-400">Modular enough to meet teams where they are, integrated enough to reveal what isolated tools cannot.</p></div><div className="mt-12 grid gap-5 md:grid-cols-2 xl:grid-cols-4">{solutions.map(([Icon,title,text],index)=>{const I=Icon as typeof ShieldAlert;return <article key={String(title)} className="landing-card group relative overflow-hidden rounded-3xl border border-white/10 bg-white/[.035] p-6"><span className="absolute right-5 top-4 text-xs text-slate-700">0{index+1}</span><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-cyan-300/10 text-cyan-300 transition group-hover:bg-cyan-300 group-hover:text-slate-950"><I size={22}/></div><h3 className="mt-5 text-lg font-semibold">{String(title)}</h3><p className="mt-3 text-sm leading-6 text-slate-400">{String(text)}</p></article>})}</div></div></section>

    <section id="why" className="scroll-mt-24 border-y border-white/10 bg-gradient-to-b from-cyan-400/[.04] to-transparent px-5 py-24 sm:px-8"><div className="mx-auto max-w-7xl"><div className="grid gap-12 lg:grid-cols-2"><div><p className="text-sm font-semibold uppercase tracking-[.2em] text-cyan-300">Why Senzilytics</p><h2 className="mt-4 text-4xl font-bold sm:text-5xl">From compliance activity to business intelligence.</h2><p className="mt-6 text-lg leading-8 text-slate-300">Senzilytics preserves the chain from a frontline observation to corrective action, risk escalation, assurance evidence and executive insight.</p></div><div className="grid gap-4 sm:grid-cols-2">{[["Connected by design","Every module contributes to a shared operational picture."],["Accountability built in","Ownership, approvals, SLAs and escalation are explicit."],["Evidence you can trust","Tenant isolation, audit trails and controlled records support assurance."],["Built for the field","Responsive workflows and offline capture keep work moving anywhere."]].map(([title,text])=><div key={title} className="rounded-3xl border border-white/10 bg-slate-950/60 p-6"><h3 className="font-semibold text-cyan-200">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-400">{text}</p></div>)}</div></div><div className="mt-16 grid gap-4 border-t border-white/10 pt-10 sm:grid-cols-2 lg:grid-cols-4">{[["01","Capture"],["02","Connect"],["03","Understand"],["04","Improve"]].map(([n,label])=><div key={n} className="flex items-center gap-4"><span className="text-3xl font-light text-cyan-300">{n}</span><span className="text-lg font-semibold">{label}</span></div>)}</div></div></section>

    <section id="contact" className="scroll-mt-24 px-5 py-24 sm:px-8"><div className="mx-auto grid max-w-7xl gap-8 rounded-[2rem] border border-cyan-300/20 bg-[radial-gradient(circle_at_top_right,rgba(34,211,238,.12),transparent_40%)] p-8 sm:p-12 lg:grid-cols-[1fr_auto] lg:items-center"><div><p className="text-sm font-semibold uppercase tracking-[.2em] text-cyan-300">Contact Us</p><h2 className="mt-4 text-3xl font-bold sm:text-5xl">Ready to see your EHS data differently?</h2><p className="mt-4 max-w-2xl text-slate-300">Explore the interactive environment or speak with us about your organization’s operational assurance goals.</p><a href="mailto:info@senzilytics.com" className="mt-5 inline-flex items-center gap-2 text-cyan-300"><Mail size={17}/>info@senzilytics.com</a></div><div className="flex flex-col gap-3 sm:flex-row lg:flex-col"><Link href="/demo" className="inline-flex items-center justify-center gap-2 rounded-2xl bg-cyan-300 px-7 py-3.5 font-semibold text-slate-950">Try Demo <ArrowRight size={18}/></Link><a href="mailto:info@senzilytics.com" className="rounded-2xl border border-white/15 px-7 py-3.5 text-center font-semibold">Contact Sales</a></div></div></section>

    <footer className="border-t border-white/10 bg-slate-950 px-5 py-12 text-sm sm:px-8"><div className="mx-auto max-w-7xl"><div className="grid gap-10 md:grid-cols-[1.3fr_1fr_1fr]"><div><Link href="/" className="text-xl font-bold">Senzilytics <span className="text-cyan-300">EHS Intelligence</span></Link><p className="mt-4 max-w-sm leading-6 text-slate-500">Connected environmental, health, safety, ESG, compliance and risk intelligence for modern organizations.</p></div><div><p className="font-semibold text-white">Explore</p><nav className="mt-4 grid gap-3 text-slate-400">{navigation.slice(0,3).map(([label,href])=><a key={href} href={href} className="hover:text-cyan-300">{label}</a>)}<Link href="/demo" className="hover:text-cyan-300">Try Interactive Demo</Link></nav></div><div><p className="font-semibold text-white">Help & Legal</p><nav className="mt-4 grid gap-3 text-slate-400"><Link href="/privacy" className="hover:text-cyan-300">Privacy Policy</Link><Link href="/support" className="hover:text-cyan-300">Support Center</Link><a href="mailto:info@senzilytics.com" className="hover:text-cyan-300">Contact Us</a><Link href="/login" className="hover:text-cyan-300">Tenant Sign In</Link></nav></div></div><div className="mt-10 flex flex-wrap justify-between gap-3 border-t border-white/10 pt-6 text-slate-600"><p>© {new Date().getFullYear()} Senzilytics. All rights reserved.</p><p>Safer work. Stronger decisions. Sustainable performance.</p></div></div></footer>
  </main>;
}
