import { getCurrentUserPermissions, requirePermission } from "@/lib/permissions";
import { getCurrentUserTenant } from "@/lib/tenant";
import { listResearchPortfolio } from "@/modules/research/research.service";
import { PermissionKey } from "@prisma/client";
import { ArrowRight, ClipboardList, Plus } from "lucide-react";
import Link from "next/link";

export const dynamic = "force-dynamic";
export default async function ResearchProjectsPage(){await requirePermission(PermissionKey.VIEW_RESEARCH);const [{organizationId},permissions]=await Promise.all([getCurrentUserTenant(),getCurrentUserPermissions()]);const {projects}=await listResearchPortfolio(organizationId);return <div><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="flex items-center gap-2 text-sm text-cyan-300"><ClipboardList size={17}/>Research Operations</p><h1 className="mt-2 text-4xl font-bold">Research Projects</h1><p className="mt-2 max-w-3xl text-slate-400">One tenant-scoped register for internal studies and client-commissioned research.</p></div>{permissions.includes(PermissionKey.CREATE_RESEARCH_PROJECT)?<Link href="/research/projects/new" className="inline-flex items-center gap-2 rounded-xl bg-cyan-300 px-5 py-3 font-semibold text-slate-950"><Plus size={17}/>New project</Link>:null}</div><div className="mt-8 overflow-hidden rounded-3xl border border-white/10 bg-white/[.035]"><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-white/[.04] text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-4">Project</th><th className="px-5 py-4">Client / owner</th><th className="px-5 py-4">Methodology</th><th className="px-5 py-4">Status</th><th className="px-5 py-4">Due</th><th className="px-5 py-4"></th></tr></thead><tbody className="divide-y divide-white/10">{projects.map(project=><tr key={project.id}><td className="px-5 py-4"><strong>{project.title}</strong><span className="mt-1 block text-xs text-slate-500">{project.reference}</span></td><td className="px-5 py-4 text-slate-300">{project.client?.name??"Internal research"}<span className="mt-1 block text-xs text-slate-500">{project.projectManager.name}</span></td><td className="px-5 py-4 text-slate-300">{pretty(project.methodology)}</td><td className="px-5 py-4"><span className="rounded-full bg-cyan-400/10 px-2.5 py-1 text-xs text-cyan-200">{pretty(project.status)}</span></td><td className="px-5 py-4 text-slate-400">{project.dueDate?.toLocaleDateString()??"Not set"}</td><td className="px-5 py-4"><Link href={`/research/projects/${project.id}`} aria-label={`Open ${project.title}`}><ArrowRight size={18} className="text-cyan-300"/></Link></td></tr>)}</tbody></table></div>{!projects.length?<div className="p-12 text-center text-sm text-slate-400">No projects found.</div>:null}</div></div>}
function pretty(value:string){return value.replaceAll("_"," ").toLowerCase().replace(/\b\w/g,letter=>letter.toUpperCase());}
