import { reviewComplianceOccurrence, submitComplianceOccurrence } from "@/features/compliance/calendar.actions";
import { hasPermission, requirePermission } from "@/lib/permissions";
import { prisma } from "@/lib/prisma";
import { getCurrentUserTenant } from "@/lib/tenant";
import { ComplianceCalendarOccurrenceStatus, PermissionKey } from "@prisma/client";
import Link from "next/link";
import { notFound } from "next/navigation";

const input = "mt-2 w-full rounded-xl border border-white/10 bg-slate-950 px-4 py-3 text-sm outline-none focus:border-cyan-400";
export default async function ComplianceOccurrencePage({ params }: { params: Promise<{ id: string }> }) {
  await requirePermission(PermissionKey.VIEW_COMPLIANCE); const [{ id }, { organizationId, user }, canManage] = await Promise.all([params, getCurrentUserTenant(), hasPermission(PermissionKey.MANAGE_COMPLIANCE)]);
  const item = await prisma.complianceCalendarOccurrence.findFirst({ where: { id, organizationId }, include: { task: true, site: true, department: true, assignedTo: true, completedBy: true, reviewedBy: true } }); if (!item) notFound();
  const canComplete = canManage || item.assignedToId === user.id; const closedStatuses = new Set<ComplianceCalendarOccurrenceStatus>([ComplianceCalendarOccurrenceStatus.COMPLETED, ComplianceCalendarOccurrenceStatus.CANCELLED, ComplianceCalendarOccurrenceStatus.SUBMITTED]); const open = !closedStatuses.has(item.status);
  return <div className="mx-auto max-w-5xl"><Link href="/compliance/calendar" className="text-sm text-cyan-300">← Compliance Calendar</Link><div className="mt-6 flex flex-wrap justify-between gap-4"><div><p className="text-sm text-cyan-300">{item.task.category.replaceAll("_"," ")} · {item.status.replaceAll("_"," ")}</p><h1 className="mt-2 text-4xl font-bold">{item.task.title}</h1><p className="mt-2 text-slate-400">Due {item.dueAt.toLocaleString()} · {item.site.name}{item.department ? ` · ${item.department.name}` : ""}</p></div></div><div className="mt-8 grid gap-6 lg:grid-cols-2"><section className="rounded-3xl border border-white/10 bg-white/5 p-6"><h2 className="text-xl font-semibold">Task requirements</h2><p className="mt-4 leading-7 text-slate-300">{item.task.description || "No description provided."}</p><p className="mt-5 text-sm text-slate-400">{item.task.instructions || "Follow the applicable organizational procedure."}</p><dl className="mt-6 space-y-3 text-sm"><Row label="Assigned to" value={item.assignedTo.name}/><Row label="Recurrence" value={item.task.recurrence.replaceAll("_"," ")}/><Row label="Reference" value={item.task.regulatoryReference || "Not specified"}/><Row label="Evidence" value={item.task.evidenceRequired ? "Required" : "Optional"}/><Row label="Approval" value={item.task.approvalRequired ? "Required" : "Not required"}/></dl>{item.completedAt && <div className="mt-6 rounded-2xl bg-slate-950/50 p-4 text-sm"><p>Submitted by {item.completedBy?.name || "Unknown"} on {item.completedAt.toLocaleString()}</p><p className="mt-2 text-slate-400">{item.completionNotes || "No completion notes."}</p>{item.evidenceUrl && <a href={item.evidenceUrl} target="_blank" rel="noreferrer" className="mt-2 block text-cyan-300">View evidence</a>}</div>}</section>
      <section className="rounded-3xl border border-white/10 bg-white/5 p-6">{canComplete && open ? <form action={submitComplianceOccurrence}><input type="hidden" name="occurrenceId" value={item.id}/><h2 className="text-xl font-semibold">Record completion</h2><label className="mt-5 block text-sm">Completion notes<textarea name="completionNotes" rows={5} className={input}/></label><label className="mt-5 block text-sm">Evidence URL<input type="url" name="evidenceUrl" className={input}/></label><button className="mt-5 rounded-xl bg-cyan-300 px-5 py-3 font-semibold text-slate-950">{item.task.approvalRequired ? "Submit for approval" : "Complete task"}</button></form> : item.status === ComplianceCalendarOccurrenceStatus.SUBMITTED && canManage ? <form action={reviewComplianceOccurrence}><input type="hidden" name="occurrenceId" value={item.id}/><h2 className="text-xl font-semibold">Supervisor review</h2><label className="mt-5 block text-sm">Review notes<textarea name="reviewNotes" rows={5} className={input}/></label><div className="mt-5 flex gap-3"><button name="decision" value="approve" className="rounded-xl bg-emerald-400 px-5 py-3 font-semibold text-slate-950">Approve</button><button name="decision" value="reject" className="rounded-xl border border-red-400/30 px-5 py-3 text-red-200">Reject</button></div></form> : <div><h2 className="text-xl font-semibold">Completion status</h2><p className="mt-5 text-slate-400">This occurrence is {item.status.replaceAll("_"," ").toLowerCase()}.</p>{item.reviewedBy && <p className="mt-3 text-sm">Reviewed by {item.reviewedBy.name}{item.reviewNotes ? ` — ${item.reviewNotes}` : ""}</p>}</div>}</section></div></div>;
}
function Row({ label, value }: { label: string; value: string }) { return <div className="flex justify-between gap-4 border-b border-white/5 pb-3"><dt className="text-slate-500">{label}</dt><dd className="text-right">{value}</dd></div>; }
