import { getCurrentUserPermissions, requirePermission } from "@/lib/permissions";
import { getCurrentUserTenant } from "@/lib/tenant";
import { getCertificationPortfolioService } from "@/modules/assurance/certification-readiness.service";
import { PermissionKey } from "@prisma/client";
import { Award, ClipboardCheck, FileCheck2, ShieldCheck } from "lucide-react";
import Link from "next/link";

export const dynamic="force-dynamic";
export default async function CertificationReadinessPortfolioPage(){
  await requirePermission(PermissionKey.VIEW_CERTIFICATION_READINESS);const[{organizationId},permissions]=await Promise.all([getCurrentUserTenant(),getCurrentUserPermissions()]);const programs=await getCertificationPortfolioService(organizationId);const canManage=permissions.includes(PermissionKey.MANAGE_CERTIFICATION_READINESS),ready=programs.filter(row=>row.readiness.band==="READY_FOR_FORMAL_REVIEW").length,attention=programs.filter(row=>row.readiness.band!=="READY_FOR_FORMAL_REVIEW").length,openGaps=programs.reduce((sum,row)=>sum+row.gaps.length,0);
  return <div><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="flex items-center gap-2 text-sm text-cyan-300"><Award size={17}/>Management Systems Assurance</p><h1 className="mt-2 text-4xl font-bold">Certification Readiness</h1><p className="mt-2 max-w-3xl text-slate-400">Use live audit, evidence, CAPA, risk, compliance, training, critical-control, and management-review records to prepare for formal certification assessment.</p></div><Link href="/audits/programs" className="rounded-xl border border-cyan-400/20 px-4 py-2 text-sm text-cyan-300">Audit Programs</Link></div>
    <div className="mt-7 grid gap-4 sm:grid-cols-4"><Metric icon={FileCheck2} label="Standard programs" value={programs.length}/><Metric icon={ShieldCheck} label="Formal-review ready" value={ready}/><Metric icon={ClipboardCheck} label="Need attention" value={attention} warning={attention>0}/><Metric icon={Award} label="Open readiness gaps" value={openGaps} warning={openGaps>0}/></div>
    <section className="mt-8 rounded-3xl border border-cyan-400/15 bg-cyan-400/[.04] p-6"><h2 className="text-lg font-semibold">Decision-support boundary</h2><p className="mt-2 text-sm text-slate-400">The readiness score is a transparent internal preparation indicator. It does not certify conformity or replace the judgment of a qualified auditor or accredited certification body.</p></section>
    <section className="mt-8"><h2 className="text-xl font-semibold">Certification program portfolio</h2><div className="mt-5 grid gap-5 lg:grid-cols-2">{programs.map(({program,readiness,evidence,gaps})=><Link key={program.id} href={`/assurance/certification/${program.id}`} className="rounded-3xl border border-white/10 bg-white/5 p-6 transition hover:border-cyan-400/30"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-wide text-cyan-300">{program.standardName||program.framework}{program.standardVersion?` · ${program.standardVersion}`:""}</p><h3 className="mt-1 text-xl font-semibold">{program.name}</h3><p className="mt-1 text-sm text-slate-400">{program.scope||"Scope recorded in Audit Management 2.0"}</p></div><div className="text-right"><strong className="text-4xl">{readiness.total}%</strong><p className={`mt-1 text-xs ${readiness.band==="READY_FOR_FORMAL_REVIEW"?"text-emerald-300":readiness.band==="NEEDS_ATTENTION"?"text-amber-300":"text-red-300"}`}>{readiness.band.replaceAll("_"," ")}</p></div></div><div className="mt-5 h-2 overflow-hidden rounded-full bg-slate-950"><div className={`h-full ${readiness.total>=85?"bg-emerald-300":readiness.total>=65?"bg-amber-300":"bg-red-300"}`} style={{width:`${readiness.total}%`}}/></div><div className="mt-5 grid grid-cols-3 gap-2 text-center"><Small label="Sites audited" value={`${evidence.auditedSites}/${evidence.scopedSites}`}/><Small label="Open findings" value={evidence.openFindings}/><Small label="Priority gaps" value={gaps.length}/></div></Link>)}{!programs.length&&<div className="rounded-3xl border border-dashed border-white/10 p-10 text-center text-slate-400"><p>No audit program currently identifies a standard or framework.</p>{canManage&&<Link href="/audits/programs/new" className="mt-4 inline-block text-cyan-300">Create a standards-based audit program →</Link>}</div>}</div></section>
  </div>;
}
function Metric({icon:Icon,label,value,warning=false}:{icon:typeof Award;label:string;value:number;warning?:boolean}){return <div className="rounded-2xl border border-white/10 bg-white/5 p-5"><div className="flex items-center justify-between"><div><p className="text-xs uppercase text-slate-500">{label}</p><p className={`mt-2 text-3xl font-bold ${warning?"text-amber-300":""}`}>{value}</p></div><Icon className="text-cyan-300"/></div></div>}
function Small({label,value}:{label:string;value:number|string}){return <div className="rounded-xl bg-slate-950/50 p-3"><p className="text-[10px] uppercase text-slate-500">{label}</p><p className="mt-1 text-sm font-semibold">{value}</p></div>}
