import { EmployeePerformanceGoalStatus, EmployeePerformanceReviewStatus } from "@prisma/client";
import type { getEmployeePerformanceGovernance } from "@/modules/employee-performance/employee-performance-governance.service";
import {
  closeEmployeePerformanceReview,
  createEmployeePerformanceGoal,
  createEmployeePerformanceReview,
  resolveEmployeePerformanceContext,
  respondToEmployeePerformanceReview,
  shareEmployeePerformanceReview,
  updateEmployeePerformanceGoal,
} from "./employee-performance-governance.actions";

type Governance = Awaited<ReturnType<typeof getEmployeePerformanceGovernance>>;
const inputClass = "w-full rounded-xl border border-white/10 bg-slate-950/60 px-3 py-2 text-sm";
const buttonClass = "rounded-xl bg-cyan-300 px-4 py-2 text-sm font-semibold text-slate-950";

export function EmployeePerformanceGovernance({ governance, employeeId, employeeName, days, canManage, isEmployee }: { governance: Governance; employeeId: string; employeeName: string; days: number; canManage: boolean; isEmployee: boolean }) {
  return <section className="mt-8 space-y-6">
    <div><h2 className="text-2xl font-semibold">Goals and governed reviews</h2><p className="mt-2 text-sm text-slate-400">Set measurable expectations and preserve an evidence snapshot, employee response, and accountable closure.</p></div>
    {canManage && <div className="grid gap-5 xl:grid-cols-2">
      <form action={createEmployeePerformanceGoal} className="rounded-3xl border border-white/10 bg-white/5 p-5 space-y-3"><h3 className="font-semibold">Assign a goal</h3><input type="hidden" name="employeeId" value={employeeId}/><input className={inputClass} name="title" placeholder="Goal title" required/><textarea className={inputClass} name="description" placeholder="Scope and evidence expected"/><div className="grid grid-cols-2 gap-3"><input className={inputClass} name="metric" placeholder="Metric" required/><input className={inputClass} name="unit" placeholder="Unit" required/><input className={inputClass} type="number" min="0.01" step="any" name="targetValue" placeholder="Target" required/><input className={inputClass} type="date" name="dueAt" required/></div><button className={buttonClass}>Assign goal</button></form>
      <form action={createEmployeePerformanceReview} className="rounded-3xl border border-white/10 bg-white/5 p-5 space-y-3"><h3 className="font-semibold">Draft evidence-based review</h3><input type="hidden" name="employeeId" value={employeeId}/><input type="hidden" name="days" value={days}/><textarea className={inputClass} name="managerNarrative" placeholder="Manager assessment" required/><textarea className={inputClass} name="strengths" placeholder="Strengths"/><textarea className={inputClass} name="supportNeeds" placeholder="Support or development needs"/><button className={buttonClass}>Create draft review</button></form>
    </div>}
    <div className="grid gap-5 xl:grid-cols-2">
      <div className="space-y-3"><h3 className="font-semibold">Goals</h3>{governance.goals.map((goal) => <article key={goal.id} className="rounded-2xl border border-white/10 bg-white/5 p-4"><div className="flex justify-between gap-3"><div><p className="font-medium">{goal.title}</p><p className="mt-1 text-xs text-slate-500">{goal.currentValue.toString()} / {goal.targetValue.toString()} {goal.unit} · due {goal.dueAt.toLocaleDateString()}</p></div><span className="text-xs text-cyan-300">{goal.status}</span></div>{goal.description && <p className="mt-3 text-sm text-slate-400">{goal.description}</p>}{canManage && goal.status === EmployeePerformanceGoalStatus.ACTIVE && <form action={updateEmployeePerformanceGoal} className="mt-4 flex flex-wrap gap-2"><input type="hidden" name="employeeId" value={employeeId}/><input type="hidden" name="goalId" value={goal.id}/><input className={`${inputClass} max-w-32`} type="number" min="0" step="any" name="currentValue" defaultValue={goal.currentValue.toString()} required/><select className={`${inputClass} max-w-40`} name="status" defaultValue={goal.status}>{Object.values(EmployeePerformanceGoalStatus).map((status) => <option key={status}>{status}</option>)}</select><button className={buttonClass}>Update</button></form>}</article>)}{!governance.goals.length && <Empty text="No goals have been assigned."/>}</div>
      <div className="space-y-3"><h3 className="font-semibold">Review history</h3>{governance.reviews.map((review) => <article key={review.id} className="rounded-2xl border border-white/10 bg-white/5 p-4"><div className="flex justify-between gap-3"><div><p className="font-medium">{review.periodStart.toLocaleDateString()}–{review.periodEnd.toLocaleDateString()}</p><p className="mt-1 text-xs text-slate-500">Reviewer: {review.reviewer.name || "Manager"}</p></div><span className="text-xs text-violet-300">{review.status.replaceAll("_", " ")}</span></div><p className="mt-3 text-sm text-slate-300">{review.managerNarrative}</p>{review.strengths && <p className="mt-2 text-xs text-slate-400"><b>Strengths:</b> {review.strengths}</p>}{review.supportNeeds && <p className="mt-2 text-xs text-slate-400"><b>Support:</b> {review.supportNeeds}</p>}{review.employeeComment && <p className="mt-3 rounded-xl bg-slate-950/50 p-3 text-xs text-slate-300"><b>{employeeName}:</b> {review.employeeComment}</p>}{review.managerResponse && <p className="mt-2 rounded-xl bg-cyan-300/5 p-3 text-xs text-cyan-100"><b>Manager response:</b> {review.managerResponse}</p>}
        {canManage && review.status === EmployeePerformanceReviewStatus.DRAFT && <ActionForm action={shareEmployeePerformanceReview} employeeId={employeeId} reviewId={review.id} label="Share with employee"/>}
        {canManage && review.status === EmployeePerformanceReviewStatus.CONTEXT_REQUESTED && <form action={resolveEmployeePerformanceContext} className="mt-4 space-y-2"><input type="hidden" name="employeeId" value={employeeId}/><input type="hidden" name="reviewId" value={review.id}/><textarea className={inputClass} name="managerResponse" placeholder="Address the employee's context" required/><button className={buttonClass}>Respond and reshare</button></form>}
        {isEmployee && review.status === EmployeePerformanceReviewStatus.SHARED && <form action={respondToEmployeePerformanceReview} className="mt-4 space-y-2"><input type="hidden" name="reviewId" value={review.id}/><textarea className={inputClass} name="comment" placeholder="Optional acknowledgement comment, or required context request"/><div className="flex gap-2"><button className={buttonClass} name="decision" value="acknowledge">Acknowledge</button><button className="rounded-xl border border-amber-300/30 px-4 py-2 text-sm text-amber-200" name="decision" value="context">Request context</button></div></form>}
        {canManage && review.status === EmployeePerformanceReviewStatus.ACKNOWLEDGED && <ActionForm action={closeEmployeePerformanceReview} employeeId={employeeId} reviewId={review.id} label="Close review"/>}
      </article>)}{!governance.reviews.length && <Empty text="No governed reviews have been created."/>}</div>
    </div>
  </section>;
}

function ActionForm({ action, employeeId, reviewId, label }: { action: (data: FormData) => Promise<void>; employeeId: string; reviewId: string; label: string }) { return <form action={action} className="mt-4"><input type="hidden" name="employeeId" value={employeeId}/><input type="hidden" name="reviewId" value={reviewId}/><button className={buttonClass}>{label}</button></form>; }
function Empty({ text }: { text: string }) { return <p className="rounded-2xl border border-dashed border-white/10 p-5 text-sm text-slate-500">{text}</p>; }
