import ExcelJS from "exceljs";
import { PermissionKey } from "@prisma/client";

import { requirePermission } from "@/lib/permissions";
import { prisma } from "@/lib/prisma";
import { getCurrentUserTenant } from "@/lib/tenant";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

const safe = (value: unknown) =>
  typeof value === "string" && /^[=+\-@\t\r]/.test(value)
    ? `'${value}`
    : (value ?? "");

export async function GET(
  _request: Request,
  { params }: { params: Promise<{ executionId: string }> },
) {
  await requirePermission(PermissionKey.EXPORT_RESEARCH_OUTPUTS);
  const [{ executionId }, { organizationId }] = await Promise.all([
    params,
    getCurrentUserTenant(),
  ]);
  const execution = await prisma.researchSamplingExecution.findFirst({
    where: { id: executionId, organizationId },
    include: {
      project: { include: { client: true } },
      samplingDesign: true,
      samplingFrame: true,
      generatedBy: { select: { name: true, email: true } },
      approvedBy: { select: { name: true, email: true } },
      units: { orderBy: { selectionOrder: "asc" } },
    },
  });
  if (!execution)
    return new Response("Sampling execution not found.", { status: 404 });
  const workbook = new ExcelJS.Workbook();
  workbook.creator = "Senzilytics";
  workbook.subject = `Governed sampling selection certificate ${execution.project.reference}`;
  const governance = workbook.addWorksheet("Selection Certificate");
  governance.addRows([
    ["Senzilytics Governed Sampling Selection Certificate"],
    ["Project", `${execution.project.reference} — ${execution.project.title}`],
    [
      "Commissioning client",
      execution.project.client?.name ?? "Internal research",
    ],
    [
      "Sampling design",
      `${execution.samplingDesign.name} v${execution.samplingDesign.version}`,
    ],
    ["Design type", execution.samplingDesign.type],
    [
      "Sampling frame",
      `${execution.samplingFrame.name} v${execution.samplingFrame.version}`,
    ],
    ["Frame source", execution.samplingFrame.sourceFileName],
    ["Frame units", execution.samplingFrame.rowCount],
    ["Execution version", execution.version],
    ["Execution status", execution.status],
    ["Primary selected", execution.selectedSampleSize],
    ["Reserve selected", execution.reserveSampleSize],
    ["Reproducibility seed", safe(execution.seed)],
    [
      "Generated by",
      `${execution.generatedBy.name} · ${execution.generatedBy.email}`,
    ],
    ["Generated at", execution.generatedAt.toISOString()],
    [
      "Approved by",
      execution.approvedBy
        ? `${execution.approvedBy.name} · ${execution.approvedBy.email}`
        : "Not approved",
    ],
    ["Approved at", execution.approvedAt?.toISOString() ?? ""],
  ]);
  const register = workbook.addWorksheet("Selection Register");
  register.addRow([
    "selection_order",
    "unit_reference",
    "frame_row",
    "stratum",
    "cluster",
    "inclusion_probability",
    "base_weight",
    "sample_role",
    "status",
  ]);
  for (const unit of execution.units)
    register.addRow([
      unit.selectionOrder,
      safe(unit.unitReference),
      unit.frameRowNumber,
      safe(unit.stratum),
      safe(unit.cluster),
      unit.inclusionProbability,
      unit.baseWeight,
      unit.isReserve ? "RESERVE" : "PRIMARY",
      unit.status,
    ]);
  const allocation = workbook.addWorksheet("Allocation Evidence");
  allocation.addRow(["evidence_path", "value"]);
  for (const [path, value] of flatten(execution.algorithmSnapshot))
    allocation.addRow([path, safe(value)]);
  for (const sheet of workbook.worksheets) {
    sheet.getRow(1).font = { bold: true, color: { argb: "FF07111F" } };
    sheet.getRow(1).fill = {
      type: "pattern",
      pattern: "solid",
      fgColor: { argb: "FF67E8F9" },
    };
    sheet.columns.forEach((column) => {
      column.width = 24;
    });
    sheet.views = [
      {
        state: "frozen",
        ySplit: sheet.name === "Selection Certificate" ? 0 : 1,
      },
    ];
  }
  const buffer = await workbook.xlsx.writeBuffer();
  return new Response(new Uint8Array(buffer), {
    headers: {
      "Content-Type":
        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
      "Content-Disposition": `attachment; filename="${execution.project.reference}-sampling-selection-v${execution.version}.xlsx"`,
      "Cache-Control": "private, no-store",
    },
  });
}

function flatten(value: unknown, path = "algorithm"): Array<[string, unknown]> {
  if (value === null || typeof value !== "object") return [[path, value]];
  if (Array.isArray(value))
    return value.flatMap((item, index) => flatten(item, `${path}[${index}]`));
  return Object.entries(value as Record<string, unknown>).flatMap(
    ([key, item]) => flatten(item, `${path}.${key}`),
  );
}
