import { requirePermission } from "@/lib/permissions";
import { getCurrentUserTenant } from "@/lib/tenant";
import { getAssetDashboardService } from "@/modules/assets/asset.service";
import { PermissionKey } from "@prisma/client";
import { ArrowLeft, BarChart3 } from "lucide-react";
import Link from "next/link";

export default async function AssetDashboardPage() {
  await requirePermission(PermissionKey.VIEW_ASSETS); const { organizationId } = await getCurrentUserTenant(); const { assets, metrics } = await getAssetDashboardService(organizationId); const now = new Date();
  const bySite = Array.from(assets.reduce((map, asset) => map.set(asset.site.name, (map.get(asset.site.name) ?? 0) + 1), new Map<string, number>()).entries()).sort((a, b) => b[1] - a[1]);
  const attention = assets.filter(asset => asset.status === "OUT_OF_SERVICE" || asset.status === "QUARANTINED" || asset.nextInspectionDueAt < now || asset.nextMaintenanceDueAt < now || asset.defects.length);
  return <div><Link href="/assets" className="inline-flex items-center gap-2 text-sm text-slate-400"><ArrowLeft size={16} />Asset Register</Link><p className="mt-6 flex items-center gap-2 text-sm text-cyan-300"><BarChart3 size={17} />Asset assurance</p><h1 className="mt-2 text-4xl font-bold">Asset Safety Dashboard</h1><p className="mt-2 text-slate-400">Leading indicators for inspection discipline, maintenance exposure, equipment availability, and unresolved defects.</p><div className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-6">{Object.entries(metrics).map(([label, value]) => <div key={label} className="rounded-2xl border border-white/10 bg-white/5 p-5"><p className="text-xs uppercase tracking-wide text-slate-500">{label.replace(/([A-Z])/g, " $1")}</p><p className="mt-2 text-3xl font-bold">{value}</p></div>)}</div><div className="mt-8 grid gap-6 xl:grid-cols-2"><section className="rounded-3xl border border-white/10 bg-white/5 p-6"><h2 className="text-xl font-semibold">Assets by site</h2><div className="mt-5 space-y-4">{bySite.map(([site, count]) => <div key={site}><div className="flex justify-between text-sm"><span>{site}</span><span>{count}</span></div><div className="mt-2 h-2 rounded-full bg-white/10"><div className="h-2 rounded-full bg-cyan-300" style={{ width: `${Math.max(4, count / Math.max(assets.length, 1) * 100)}%` }} /></div></div>)}</div></section><section className="rounded-3xl border border-white/10 bg-white/5 p-6"><h2 className="text-xl font-semibold">Management attention</h2><div className="mt-4 space-y-3">{attention.slice(0, 12).map(asset => <Link key={asset.id} href={`/assets/${asset.id}`} className="block rounded-2xl border border-white/10 p-4 hover:bg-white/5"><div className="flex justify-between gap-4"><span className="font-semibold text-cyan-200">{asset.reference} — {asset.name}</span><span className="text-xs text-slate-400">{asset.site.name}</span></div><p className="mt-2 text-xs text-slate-400">{asset.status.replaceAll("_", " ")} · {asset.defects.length} open defects · Inspection {asset.nextInspectionDueAt.toLocaleDateString()}</p></Link>)}{!attention.length && <p className="text-sm text-emerald-300">No current asset exceptions require management attention.</p>}</div></section></div></div>;
}
