import ExcelJS from "exceljs";
import { PermissionKey } from "@prisma/client";

import { requirePermission } from "@/lib/permissions";
import { prisma } from "@/lib/prisma";
import { getCurrentUserTenant } from "@/lib/tenant";
import { buildFieldworkAnalytics } from "@/modules/research/research-fieldwork-analytics";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

export async function GET(
  _request: Request,
  { params }: { params: Promise<{ executionId: string }> },
) {
  await requirePermission(PermissionKey.EXPORT_RESEARCH_OUTPUTS);
  const [{ executionId }, { organizationId }] = await Promise.all([
    params,
    getCurrentUserTenant(),
  ]);
  const execution = await prisma.researchSamplingExecution.findFirst({
    where: { id: executionId, organizationId },
    include: {
      project: true,
      samplingDesign: true,
      samplingFrame: true,
      generatedBy: { select: { name: true } },
      approvedBy: { select: { name: true } },
      units: {
        include: {
          assignedTo: { select: { name: true } },
          replacementFor: { select: { unitReference: true } },
        },
        orderBy: { selectionOrder: "asc" },
      },
    },
  });
  if (!execution)
    return new Response("Sampling execution not found.", { status: 404 });
  const analytics = buildFieldworkAnalytics(execution.units),
    workbook = new ExcelJS.Workbook();
  const summary = workbook.addWorksheet("Fieldwork Summary");
  summary.addRows(
    [
      ["Senzilytics Governed Fieldwork Operations"],
      ["Project", execution.project.reference],
      ["Execution", `v${execution.version}`],
      ["Status", execution.status],
      ["Sampling method", execution.samplingDesign.type],
      ["Validated frame", execution.samplingFrame.name],
      ["Generated by", execution.generatedBy.name],
      ["Approved by", execution.approvedBy?.name ?? ""],
      ["Selected primary", analytics.selected],
      ["Assigned", analytics.assigned],
      ["Completed", analytics.completed],
      ["Response rate", analytics.responseRate],
      ["Cooperation rate", analytics.cooperationRate],
      ["Overdue", analytics.overdue],
      ["Average attempts", analytics.averageAttempts],
    ].map((row) => row.map(safe)),
  );
  addGrouped(workbook, "Researcher Performance", analytics.researchers);
  addGrouped(workbook, "Strata Performance", analytics.strata);
  addGrouped(workbook, "Cluster Performance", analytics.clusters);
  addGrouped(workbook, "Dispositions", analytics.dispositions);
  const register = workbook.addWorksheet("Fieldwork Register");
  register.addRow([
    "Order",
    "Unit reference",
    "Stratum",
    "Cluster",
    "Status",
    "Researcher",
    "Due",
    "Attempts",
    "Last contacted",
    "Completed",
    "Replacement for",
    "Escalation level",
    "Disposition note",
  ]);
  for (const unit of execution.units)
    register.addRow([
      unit.selectionOrder,
      safe(unit.unitReference),
      safe(unit.stratum ?? ""),
      safe(unit.cluster ?? ""),
      unit.status,
      safe(unit.assignedTo?.name ?? ""),
      unit.dueAt?.toISOString() ?? "",
      unit.contactAttempts,
      unit.lastContactedAt?.toISOString() ?? "",
      unit.completedAt?.toISOString() ?? "",
      safe(unit.replacementFor?.unitReference ?? ""),
      unit.escalationLevel,
      safe(unit.dispositionNote ?? ""),
    ]);
  for (const sheet of workbook.worksheets) {
    sheet.getRow(1).font = { bold: true, color: { argb: "FF07111F" } };
    sheet.getRow(1).fill = {
      type: "pattern",
      pattern: "solid",
      fgColor: { argb: "FF67E8F9" },
    };
    sheet.views = [{ state: "frozen", ySplit: 1 }];
    sheet.columns.forEach((column) => (column.width = 24));
    sheet.autoFilter =
      sheet.rowCount > 1
        ? {
            from: { row: 1, column: 1 },
            to: { row: 1, column: sheet.columnCount },
          }
        : undefined;
  }
  const buffer = await workbook.xlsx.writeBuffer();
  return new Response(new Uint8Array(buffer), {
    headers: {
      "Content-Type":
        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
      "Content-Disposition": `attachment; filename="${execution.project.reference}-fieldwork-v${execution.version}.xlsx"`,
      "Cache-Control": "private, no-store",
    },
  });
}
function addGrouped(
  workbook: ExcelJS.Workbook,
  name: string,
  rows: Array<{
    name: string;
    value: number;
    total: number;
    completed: number;
    overdue: number;
  }>,
) {
  const sheet = workbook.addWorksheet(name);
  sheet.addRow(["Group", "Metric", "Total", "Completed", "Overdue"]);
  rows.forEach((row) =>
    sheet.addRow([
      safe(row.name),
      row.value,
      row.total,
      row.completed,
      row.overdue,
    ]),
  );
}
function safe(value: string | number) {
  return typeof value === "string" && /^[=+\-@\t\r]/.test(value)
    ? `'${value}`
    : value;
}
