-- CreateEnum
CREATE TYPE "PermissionKey" AS ENUM ('MANAGE_ORGANIZATION', 'MANAGE_USERS', 'VIEW_USERS', 'VIEW_DASHBOARD', 'VIEW_REPORTS', 'CREATE_INCIDENT', 'VIEW_INCIDENT', 'UPDATE_INCIDENT', 'DELETE_INCIDENT', 'CREATE_CAPA', 'UPDATE_CAPA', 'CLOSE_CAPA', 'VIEW_AUDITS', 'MANAGE_AUDITS', 'VIEW_INSPECTIONS', 'MANAGE_INSPECTIONS', 'VIEW_COMPLIANCE', 'MANAGE_COMPLIANCE', 'VIEW_TRAINING', 'MANAGE_TRAINING', 'USE_AI', 'MANAGE_WORKFLOWS', 'VIEW_ACTIVITY_LOG', 'MANAGE_NOTIFICATIONS', 'MANAGE_DOCUMENTS');

-- CreateTable
CREATE TABLE "RolePermission" (
    "id" TEXT NOT NULL,
    "role" "UserRole" NOT NULL,
    "permission" "PermissionKey" NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "RolePermission_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "RolePermission_role_permission_key" ON "RolePermission"("role", "permission");
