"use client";

import { RiskLevel, SafetyObservationType } from "@prisma/client";
import { useCallback, useEffect, useState } from "react";

type Site = { id: string; name: string };
type QueuedItem = { id: string; type: "SAFETY_OBSERVATION"; capturedAt: string; payload: Record<string, unknown> };
const DB = "senzilytics-field-data", STORE = "outbox";

function database() { return new Promise<IDBDatabase>((resolve, reject) => { const request = indexedDB.open(DB, 1); request.onupgradeneeded = () => request.result.createObjectStore(STORE, { keyPath: "id" }); request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error); }); }
async function allItems() { const db = await database(); return new Promise<QueuedItem[]>((resolve, reject) => { const request = db.transaction(STORE).objectStore(STORE).getAll(); request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error); }); }
async function saveItem(item: QueuedItem) { const db = await database(); return new Promise<void>((resolve, reject) => { const request = db.transaction(STORE, "readwrite").objectStore(STORE).put(item); request.onsuccess = () => resolve(); request.onerror = () => reject(request.error); }); }
async function removeItem(id: string) { const db = await database(); return new Promise<void>((resolve, reject) => { const request = db.transaction(STORE, "readwrite").objectStore(STORE).delete(id); request.onsuccess = () => resolve(); request.onerror = () => reject(request.error); }); }

const input = "mt-2 w-full rounded-xl border border-white/10 bg-slate-950 px-4 py-3 text-sm outline-none focus:border-cyan-400";
export function OfflineObservationForm({ sites }: { sites: Site[] }) {
  const [online, setOnline] = useState(true), [pending, setPending] = useState(0), [message, setMessage] = useState("");
  const refresh = useCallback(async () => setPending((await allItems()).length), []);
  const synchronize = useCallback(async () => { if (!navigator.onLine) return; const items = await allItems(); if (!items.length) return; const response = await fetch("/api/offline/sync", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ items }) }); if (!response.ok) { setMessage("Synchronization is waiting for a valid signed-in connection."); return; } const body = await response.json(); for (const result of body.results) if (result.status === "synced" || result.status === "already_synced") await removeItem(result.id); await refresh(); setMessage("Saved field records synchronized successfully."); }, [refresh]);
  useEffect(() => { setOnline(navigator.onLine); refresh(); const onOnline=()=>{setOnline(true); synchronize()}; const onOffline=()=>setOnline(false); window.addEventListener("online",onOnline); window.addEventListener("offline",onOffline); return()=>{window.removeEventListener("online",onOnline);window.removeEventListener("offline",onOffline)}; }, [refresh,synchronize]);
  async function submit(formData: FormData) { const observedAt = new Date(String(formData.get("observedAt"))).toISOString(); const item: QueuedItem = { id: crypto.randomUUID(), type: "SAFETY_OBSERVATION", capturedAt: new Date().toISOString(), payload: { siteId: formData.get("siteId"), title: formData.get("title"), description: formData.get("description"), type: formData.get("type"), riskLevel: formData.get("riskLevel"), location: formData.get("location") || undefined, immediateAction: formData.get("immediateAction") || undefined, observedAt, isAnonymous: formData.get("isAnonymous") === "on" } }; await saveItem(item); await refresh(); setMessage(navigator.onLine ? "Record saved securely. Synchronizing…" : "Record saved on this device and will synchronize when online."); if (navigator.onLine) await synchronize(); }
  return <div><div className={`mb-5 rounded-xl border p-3 text-sm ${online ? "border-emerald-400/20 bg-emerald-400/10 text-emerald-200" : "border-amber-400/20 bg-amber-400/10 text-amber-200"}`}>{online ? "Online" : "Offline collection active"} · {pending} record(s) waiting to synchronize {pending > 0 && online && <button onClick={synchronize} className="ml-2 underline">Sync now</button>}</div>{message && <p role="status" className="mb-5 rounded-xl bg-white/5 p-3 text-sm text-cyan-200">{message}</p>}<form action={submit} className="space-y-5 rounded-3xl border border-white/10 bg-white/5 p-7"><div className="grid gap-5 md:grid-cols-2"><Field label="Site"><select name="siteId" required className={input}>{sites.map(site=><option key={site.id} value={site.id}>{site.name}</option>)}</select></Field><Field label="Observed date and time"><input name="observedAt" type="datetime-local" required defaultValue={new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16)} className={input}/></Field><Field label="Observation type"><select name="type" className={input}>{Object.values(SafetyObservationType).map(x=><option key={x}>{x.replaceAll("_"," ")}</option>)}</select></Field><Field label="Risk level"><select name="riskLevel" className={input}>{Object.values(RiskLevel).map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Title"><input name="title" required minLength={2} className={input}/></Field><Field label="Location"><input name="location" className={input}/></Field></div><Field label="What did you observe?"><textarea name="description" required rows={5} className={input}/></Field><Field label="Immediate action taken"><textarea name="immediateAction" rows={3} className={input}/></Field><label className="text-sm"><input type="checkbox" name="isAnonymous" className="mr-2"/>Hide my identity in operational views</label><button className="rounded-xl bg-cyan-300 px-5 py-3 font-semibold text-slate-950">Save Field Observation</button></form><p className="mt-4 text-xs leading-5 text-slate-500">Offline records are stored only in this browser until synchronization. Use a managed device, protect it with a passcode, and synchronize before signing out or clearing browser data.</p></div>;
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block text-sm text-slate-300">{label}{children}</label>}
