import { SupportAccessStatus } from "@prisma/client";
import { enterSupportAccess, requestSupportAccess } from "@/features/platform/support-access.actions";
import { requirePlatformAdministrator } from "@/lib/platform-admin";
import { prisma } from "@/lib/prisma";
import { tenantAssignableModules } from "@/core/navigation/tenant-module-catalog";
import { supportAccessDurations } from "@/modules/platform/support-access.service";

const input = "mt-2 w-full rounded-xl border border-white/10 bg-slate-950 px-4 py-3";
export default async function PlatformSupportAccessPage() {
  const admin = await requirePlatformAdministrator();
  const [organizations, grants] = await Promise.all([
    prisma.organization.findMany({ where: { status: "ACTIVE", id: { not: admin.organizationId ?? undefined } }, include: { moduleAssignments: { select: { moduleKey: true, enabled: true } } }, orderBy: { name: "asc" } }),
    prisma.supportAccessGrant.findMany({ where: { requestedById: admin.id }, include: { organization: { select: { name: true } }, approvedBy: { select: { name: true } } }, orderBy: { requestedAt: "desc" }, take: 50 }),
  ]);
  return <div><p className="text-sm text-cyan-300">Platform support governance</p><h1 className="mt-2 text-4xl font-bold">Tenant support access</h1><p className="mt-2 max-w-3xl text-slate-400">Request tenant-approved, time-limited, read-only access. Never request or use a tenant user&apos;s password.</p>
    <div className="mt-8 grid gap-6 xl:grid-cols-[.8fr_1.2fr]"><div className="space-y-4">{organizations.map(organization=>{const modules=tenantAssignableModules(organization.industryCategory,organization.moduleAssignments);return <details key={organization.id} className="rounded-3xl border border-white/10 bg-white/5 p-5"><summary className="cursor-pointer font-semibold text-cyan-200">Request access to {organization.name}</summary><form action={requestSupportAccess} className="mt-4 space-y-4"><input type="hidden" name="organizationId" value={organization.id}/><label className="block text-sm">Business reason<textarea name="reason" required rows={4} placeholder="Describe the tenant-reported issue and diagnostic purpose." className={input}/></label><label className="block text-sm">Duration<select name="durationMinutes" defaultValue="60" className={input}>{supportAccessDurations.map(minutes=><option key={minutes} value={minutes}>{minutes<60?`${minutes} minutes`:`${minutes/60} hours`}</option>)}</select></label><fieldset><legend className="text-sm">Requested module scope</legend><div className="mt-3 grid gap-2 sm:grid-cols-2">{modules.map(entry=><label key={entry.key} className="flex items-center gap-2 rounded-xl border border-white/10 p-3 text-xs"><input type="checkbox" name="moduleKeys" value={entry.key} className="accent-cyan-300"/>{entry.label}</label>)}</div></fieldset><button className="rounded-xl bg-cyan-300 px-4 py-3 font-semibold text-slate-950">Send approval request</button></form></details>})}</div>
      <section className="space-y-3"><h2 className="text-xl font-semibold">My support requests</h2>{grants.map(grant=><article key={grant.id} className="rounded-2xl border border-white/10 bg-white/5 p-5"><div className="flex justify-between gap-4"><div><p className="font-medium">{grant.organization.name}</p><p className="mt-1 text-sm text-slate-400">{grant.reason}</p></div><span className="text-xs text-cyan-300">{grant.status}</span></div><p className="mt-3 text-xs text-slate-500">{grant.durationMinutes} minutes · {grant.moduleKeys.length} modules · requested {grant.requestedAt.toLocaleString()}</p>{grant.expiresAt&&<p className="mt-1 text-xs text-slate-500">Expires {grant.expiresAt.toLocaleString()}</p>}{grant.status===SupportAccessStatus.APPROVED&&grant.expiresAt&&grant.expiresAt>new Date()?<form action={enterSupportAccess} className="mt-4"><input type="hidden" name="grantId" value={grant.id}/><button className="rounded-xl bg-emerald-300 px-4 py-2 text-sm font-semibold text-slate-950">Enter read-only tenant session</button></form>:null}</article>)}{!grants.length&&<p className="rounded-2xl border border-dashed border-white/10 p-6 text-sm text-slate-500">No support access has been requested.</p>}</section>
    </div></div>;
}
