import Link from "next/link";

export default function PrivacyPolicyPage() {
  return <main className="min-h-screen bg-slate-950 px-5 py-10 text-white sm:px-8"><article className="mx-auto max-w-4xl"><Link href="/" className="text-sm text-cyan-300">← Back to Senzilytics</Link><p className="mt-10 text-sm font-semibold uppercase tracking-[.2em] text-cyan-300">Privacy and data protection</p><h1 className="mt-3 text-4xl font-bold">Privacy Policy</h1><p className="mt-3 text-sm text-slate-500">Last updated July 21, 2026</p><div className="mt-10 space-y-8 text-slate-300">
    <Section title="Scope and organizational roles">This policy applies to the Senzilytics website, tenant platform, demonstration environment, and native mobile applications. For tenant workspace data, the subscribing organization generally determines why its workforce and operational data is processed, while Senzilytics operates the platform on that organization&apos;s instructions. Contact your organization&apos;s administrator first for requests concerning employer-managed records.</Section>
    <Section title="Information we process">We may process account and identity information such as name, work email, organization, role, permissions, and authentication provider; tenant-entered EHS, ESG, audit, risk, compliance, training, incident, observation, and workflow records; device and session information such as device identifier, device name, platform, push token, and security-session status; and technical information such as IP address, user agent, timestamps, diagnostics, and security events. Demo and commercial inquiries may also include company, job title, country, phone number, and communication preferences.</Section>
    <Section title="How information is used">Information is used to authenticate users, enforce tenant isolation and permissions, provide contracted platform functions, synchronize authorized field records, deliver requested notifications, protect the service, investigate misuse, provide support, maintain auditability, improve reliability, and comply with applicable obligations. Senzilytics does not use tenant operational data for third-party advertising.</Section>
    <Section title="Mobile and offline data">The native application stores rotating credentials in the iOS Keychain or Android Keystore. Offline workspace information and queued submissions are stored in an encrypted database and separated by organization and user. Cached workspace authorization is time limited and server permissions are checked when records synchronize. Signing out removes the local credential and workspace cache; encrypted queued submissions may remain scoped to the same account so authorized work can resume after reauthentication. Removing the application clears application-controlled local storage according to the device operating system.</Section>
    <Section title="Sharing and service providers">Authorized users and administrators of the applicable tenant may access information according to configured roles. We may use service providers for cloud hosting, databases, authentication, email, push delivery, file storage, security, support, and tenant-enabled intelligence functions. Providers are permitted to process information only for the services they supply and are expected to apply appropriate protections. We do not sell personal information or share it for cross-context behavioral advertising.</Section>
    <Section title="Retention and deletion">Tenant records are retained according to the customer agreement, tenant instructions, configured lifecycle rules, security needs, and applicable legal or regulatory requirements. Security and transaction records may be retained for a reasonable period to protect the service and demonstrate compliance. Demo access is time limited. Requests for access, correction, export, restriction, or deletion can be submitted through the <Link className="text-cyan-300 underline" href="/account-deletion">account and data request page</Link>. Some workplace safety or compliance records may need to be preserved by the tenant or by law.</Section>
    <Section title="Security">We use administrative, technical, and organizational safeguards designed to protect information, including encrypted transport, scoped authorization, tenant filtering, protected credentials, session revocation, and activity records. No method of storage or transmission can be guaranteed completely secure.</Section>
    <Section title="International processing">Senzilytics and its service providers may process information in countries other than the user&apos;s location. Where required, appropriate contractual or other legal safeguards should be used for cross-border processing.</Section>
    <Section title="Children">Senzilytics is an enterprise workplace platform and is not directed to children. Tenant administrators should provision only authorized workforce or business users permitted to use the service.</Section>
    <Section title="Your choices and rights">You can decline optional marketing communications and change device notification permissions in operating-system settings. Depending on applicable law, you may have rights to request access, correction, deletion, portability, objection, or withdrawal of consent. Tenant-managed requests should normally be directed to your organization first.</Section>
    <Section title="Changes and contact">We may update this policy as the platform or legal requirements change and will revise the date above. For privacy questions or requests, email <a className="text-cyan-300 underline" href="mailto:privacy@senzilytics.com">privacy@senzilytics.com</a>. For product support, visit the <Link className="text-cyan-300 underline" href="/support">Support Center</Link>.</Section>
  </div></article></main>;
}

function Section({ title, children }: { title: string; children: React.ReactNode }) { return <section><h2 className="text-xl font-semibold text-white">{title}</h2><p className="mt-3 leading-7">{children}</p></section>; }
