import { AuditActionForm } from "@/features/audits/audit-action-form";
import { AuditEvidenceUpload } from "@/features/audits/audit-evidence-upload";
import {
  addAuditFindingEvidence,
  createAuditFinding,
  createCapaFromAuditFindingWithFeedback,
  createRiskFromAuditFinding,
  reviewCapaProposal,
  reviewRiskProposal,
  transitionAuditFinding,
  verifyAuditFinding,
} from "@/features/audits/finding.actions";
import { findTenantAuditById } from "@/modules/audit/audit.repository";
import {
  EnterpriseAuditEvidenceType,
  EnterpriseAuditFindingCategory,
  EnterpriseAuditFindingStatus,
  EnterpriseAuditFindingType,
  EnterpriseAuditLinkStatus,
  EnterpriseAuditSeverity,
  RiskCategory,
  RiskImpact,
  RiskLikelihood,
} from "@prisma/client";

type Audit = NonNullable<Awaited<ReturnType<typeof findTenantAuditById>>>;
type User = { id: string; name: string; jobTitle: string | null };
const nextFindingStatuses: Record<EnterpriseAuditFindingStatus, EnterpriseAuditFindingStatus[]> = {
  DRAFT: [EnterpriseAuditFindingStatus.OPEN, EnterpriseAuditFindingStatus.CANCELLED],
  OPEN: [EnterpriseAuditFindingStatus.UNDER_REVIEW, EnterpriseAuditFindingStatus.ACTION_REQUIRED, EnterpriseAuditFindingStatus.CANCELLED],
  UNDER_REVIEW: [EnterpriseAuditFindingStatus.OPEN, EnterpriseAuditFindingStatus.ACTION_REQUIRED, EnterpriseAuditFindingStatus.REJECTED],
  ACTION_REQUIRED: [EnterpriseAuditFindingStatus.IN_PROGRESS, EnterpriseAuditFindingStatus.CANCELLED],
  IN_PROGRESS: [EnterpriseAuditFindingStatus.PENDING_VERIFICATION, EnterpriseAuditFindingStatus.CANCELLED],
  PENDING_VERIFICATION: [EnterpriseAuditFindingStatus.IN_PROGRESS],
  VERIFIED: [EnterpriseAuditFindingStatus.CLOSED, EnterpriseAuditFindingStatus.IN_PROGRESS],
  CLOSED: [EnterpriseAuditFindingStatus.OPEN],
  REJECTED: [EnterpriseAuditFindingStatus.OPEN],
  CANCELLED: [EnterpriseAuditFindingStatus.OPEN],
};

export function AuditFindingManagement({ audit, users }: { audit: Audit; users: User[] }) {
  const questions = audit.sections.flatMap((section) => section.questions.map((question) => ({ id: question.id, label: `${section.sequence}.${question.sequence} ${question.questionText}` })));
  return <div className="space-y-5">
    <details className="rounded-2xl border border-cyan-400/20 bg-cyan-400/[0.04] p-4"><summary className="cursor-pointer text-sm font-semibold text-cyan-300">Create Manual Finding</summary><form action={createAuditFinding} className="mt-5 space-y-4"><input type="hidden" name="auditId" value={audit.id} /><div className="grid gap-4 md:grid-cols-2"><Field label="Finding title"><input name="title" required className={inputClass} /></Field><Field label="Related question"><select name="questionId" defaultValue="" className={inputClass}><option value="">Audit-level finding</option>{questions.map((question) => <option key={question.id} value={question.id}>{question.label}</option>)}</select></Field></div><div className="grid gap-4 md:grid-cols-3"><EnumSelect label="Type" name="findingType" values={Object.values(EnterpriseAuditFindingType)} defaultValue={EnterpriseAuditFindingType.NONCONFORMITY} /><EnumSelect label="Category" name="category" values={Object.values(EnterpriseAuditFindingCategory)} defaultValue={EnterpriseAuditFindingCategory.OTHER} /><EnumSelect label="Severity" name="severity" values={Object.values(EnterpriseAuditSeverity)} defaultValue={EnterpriseAuditSeverity.MEDIUM} /></div><Field label="Description"><textarea name="description" rows={3} className={inputClass} /></Field><Field label="Objective evidence"><textarea name="objectiveEvidence" rows={3} className={inputClass} /></Field><div className="grid gap-4 md:grid-cols-2"><Field label="Standard clause"><input name="standardClause" className={inputClass} /></Field><Field label="Regulatory reference"><input name="regulatoryRef" className={inputClass} /></Field><Field label="Immediate correction"><textarea name="immediateCorrection" rows={2} className={inputClass} /></Field><Field label="Containment action"><textarea name="containmentAction" rows={2} className={inputClass} /></Field><UserSelect label="Owner" name="ownerId" users={users} /><Field label="Due date"><input type="date" name="dueDate" className={inputClass} /></Field></div><div className="flex flex-wrap gap-5 text-sm"><Check name="requiresCapa" label="Requires CAPA" /><Check name="requiresRiskReview" label="Requires risk review" /></div><div className="flex justify-end"><Button>Create Finding</Button></div></form></details>
    {audit.findings.length === 0 ? <p className="rounded-2xl border border-dashed border-white/10 p-5 text-sm text-slate-500">No findings recorded.</p> : audit.findings.map((finding) => <article key={finding.id} className="rounded-2xl border border-white/10 bg-slate-950/40 p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs text-cyan-300">{finding.reference} · {pretty(finding.findingType)}</p><h3 className="mt-2 font-semibold">{finding.title}</h3><p className="mt-2 text-sm text-slate-400">{finding.description || "No finding description."}</p></div><span className="rounded-full bg-cyan-400/10 px-3 py-1 text-xs text-cyan-200">{pretty(finding.status)} · {pretty(finding.severity)}</span></div><div className="mt-4 grid gap-3 md:grid-cols-3"><Info label="Owner" value={finding.owner?.name || "Not assigned"} /><Info label="Due" value={finding.dueDate?.toLocaleDateString() || "Not set"} /><Info label="Evidence" value={String(finding.evidence.length)} /></div>
      <div className="mt-5 grid gap-4 xl:grid-cols-2"><details className={detailClass}><summary className={summaryClass}>Lifecycle, ownership, and root cause</summary><form action={transitionAuditFinding} className="mt-4 space-y-4"><Hidden auditId={audit.id} findingId={finding.id} /><EnumSelect label="Next status" name="status" values={nextFindingStatuses[finding.status]} defaultValue={nextFindingStatuses[finding.status][0]} /><div className="grid gap-4 md:grid-cols-2"><UserSelect label="Owner" name="ownerId" users={users} defaultValue={finding.ownerId ?? ""} /><Field label="Due date"><input type="date" name="dueDate" defaultValue={finding.dueDate?.toISOString().slice(0, 10) ?? ""} className={inputClass} /></Field></div><Field label="Root cause"><textarea name="rootCause" rows={2} defaultValue={finding.rootCause ?? ""} className={inputClass} /></Field><Field label="Root-cause category"><input name="rootCauseCategory" defaultValue={finding.rootCauseCategory ?? ""} className={inputClass} /></Field><Field label="Closure summary"><textarea name="closureSummary" rows={2} className={inputClass} /></Field><Button>Update Finding</Button></form></details>
      <details className={detailClass}><summary className={summaryClass}>Add evidence</summary><form action={addAuditFindingEvidence} className="mt-4 space-y-4"><Hidden auditId={audit.id} findingId={finding.id} /><EnumSelect label="Evidence type" name="evidenceType" values={Object.values(EnterpriseAuditEvidenceType)} defaultValue={EnterpriseAuditEvidenceType.NOTE} /><Field label="Title"><input name="title" required className={inputClass} /></Field><Field label="Description"><textarea name="description" rows={2} className={inputClass} /></Field><Field label="External URL"><input type="url" name="externalUrl" className={inputClass} /></Field><Button>Add Evidence Note or Link</Button></form><div className="my-4 border-t border-white/10"/><AuditEvidenceUpload auditId={audit.id} findingId={finding.id}/>{finding.evidence.length > 0 && <div className="mt-4 space-y-2">{finding.evidence.map((evidence)=><a key={evidence.id} href={evidence.fileUrl ? `/api/audits/evidence/${evidence.id}` : evidence.externalUrl || "#"} target="_blank" rel="noreferrer" className="block text-xs text-cyan-300">{evidence.title}{evidence.fileName ? ` — ${evidence.fileName}` : ""}</a>)}</div>}</details>
      {finding.status === EnterpriseAuditFindingStatus.PENDING_VERIFICATION && <details className={detailClass} open><summary className={summaryClass}>Independent verification</summary><form action={verifyAuditFinding} className="mt-4 space-y-4"><Hidden auditId={audit.id} findingId={finding.id} /><Field label="Decision"><select name="decision" className={inputClass}><option value="ACCEPT">Accept verification</option><option value="REJECT">Reject and return</option></select></Field><Field label="Verification method"><input name="verificationMethod" required className={inputClass} /></Field><Field label="Verification evidence"><textarea name="verificationEvidence" rows={2} className={inputClass} /></Field><Field label="Comments"><textarea name="comments" rows={2} className={inputClass} /></Field><Button>Record Verification</Button></form></details>}
      {finding.correctiveActionLinks.every((link) => !link.correctiveAction) && <details className={detailClass}><summary className={summaryClass}>Create linked CAPA</summary><AuditActionForm action={createCapaFromAuditFindingWithFeedback} className="mt-4 space-y-4"><Hidden auditId={audit.id} findingId={finding.id} /><Field label="Action title"><input name="title" required defaultValue={`Corrective action — ${finding.title}`} className={inputClass} /></Field><Field label="Description"><textarea name="description" rows={2} defaultValue={finding.description ?? ""} className={inputClass} /></Field><UserSelect label="Assigned to" name="assignedToId" users={users} required /><Field label="Due date (must be in the future)"><input type="date" name="dueDate" required className={inputClass} /></Field><Button>Create CAPA</Button></AuditActionForm></details>}
      {finding.riskLinks.every((link) => !link.risk) && <details className={detailClass}><summary className={summaryClass}>Create linked risk</summary><form action={createRiskFromAuditFinding} className="mt-4 space-y-4"><Hidden auditId={audit.id} findingId={finding.id} /><Field label="Risk title"><input name="title" required defaultValue={finding.title} className={inputClass} /></Field><Field label="Risk description"><textarea name="description" required rows={2} defaultValue={finding.description ?? finding.title} className={inputClass} /></Field><EnumSelect label="Category" name="riskCategory" values={Object.values(RiskCategory)} defaultValue={RiskCategory.SAFETY} /><Field label="Hazard type"><input name="hazardType" className={inputClass} /></Field><UserSelect label="Risk owner" name="ownerId" users={users} /><div className="grid gap-4 md:grid-cols-2"><EnumSelect label="Likelihood" name="likelihood" values={Object.values(RiskLikelihood)} defaultValue={RiskLikelihood.POSSIBLE} /><EnumSelect label="Impact" name="impact" values={Object.values(RiskImpact)} defaultValue={RiskImpact.MODERATE} /></div><Field label="Next review"><input type="date" name="nextReviewDate" className={inputClass} /></Field><Button>Create Risk</Button></form></details>}</div>
      {(finding.correctiveActionLinks.some((link) => link.correctiveAction) || finding.riskLinks.some((link) => link.risk)) && <div className="mt-5 flex flex-wrap gap-2">{finding.correctiveActionLinks.map((link) => link.correctiveAction && <span key={link.id} className="rounded-full bg-amber-400/10 px-3 py-1 text-xs text-amber-200">CAPA: {link.correctiveAction.title} · {pretty(link.correctiveAction.status)}</span>)}{finding.riskLinks.map((link) => link.risk && <a key={link.id} href={`/risks/${link.risk.id}`} className="rounded-full bg-purple-400/10 px-3 py-1 text-xs text-purple-200">Risk: {link.risk.reference} · {pretty(link.risk.status)}</a>)}</div>}
      {(finding.correctiveActionLinks.some((link) => link.status === EnterpriseAuditLinkStatus.PROPOSED) || finding.riskLinks.some((link) => link.status === EnterpriseAuditLinkStatus.PROPOSED)) && <div className="mt-5 space-y-3 rounded-2xl border border-amber-400/20 bg-amber-400/5 p-4"><p className="text-sm font-semibold text-amber-200">Recommendations awaiting authorized review</p>{finding.correctiveActionLinks.filter((link) => link.status === EnterpriseAuditLinkStatus.PROPOSED).map((link) => <Proposal key={link.id} auditId={audit.id} findingId={finding.id} linkId={link.id} title={link.recommendationTitle || "CAPA recommendation"} kind="CAPA" action={reviewCapaProposal} />)}{finding.riskLinks.filter((link) => link.status === EnterpriseAuditLinkStatus.PROPOSED).map((link) => <Proposal key={link.id} auditId={audit.id} findingId={finding.id} linkId={link.id} title={link.proposedRiskTitle || "Risk recommendation"} kind="RISK" action={reviewRiskProposal} />)}</div>}
    </article>)}
  </div>;
}

const inputClass = "mt-2 w-full rounded-xl border border-white/10 bg-slate-950/80 px-3 py-2 text-sm outline-none focus:border-cyan-400/50"; const detailClass = "rounded-xl border border-white/10 p-4"; const summaryClass = "cursor-pointer text-sm font-medium text-cyan-300";
function pretty(value: string) { return value.replaceAll("_", " "); }
function Hidden({ auditId, findingId }: { auditId: string; findingId: string }) { return <><input type="hidden" name="auditId" value={auditId} /><input type="hidden" name="findingId" value={findingId} /></>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block text-xs font-medium text-slate-400">{label}{children}</label>; }
function EnumSelect({ label, name, values, defaultValue }: { label: string; name: string; values: string[]; defaultValue: string }) { return <Field label={label}><select name={name} defaultValue={defaultValue} className={inputClass}>{values.map((value) => <option key={value} value={value}>{pretty(value)}</option>)}</select></Field>; }
function UserSelect({ label, name, users, required = false, defaultValue = "" }: { label: string; name: string; users: User[]; required?: boolean; defaultValue?: string }) { return <Field label={label}><select name={name} required={required} defaultValue={defaultValue} className={inputClass}><option value="">{required ? "Select user" : "Not assigned"}</option>{users.map((user) => <option key={user.id} value={user.id}>{user.name}{user.jobTitle ? ` — ${user.jobTitle}` : ""}</option>)}</select></Field>; }
function Check({ name, label }: { name: string; label: string }) { return <label className="flex gap-2"><input type="checkbox" name={name} />{label}</label>; }
function Button({ children }: { children: React.ReactNode }) { return <button className="rounded-xl bg-cyan-300 px-4 py-2 text-sm font-semibold text-slate-950">{children}</button>; }
function Info({ label, value }: { label: string; value: string }) { return <div className="rounded-xl bg-white/[0.03] p-3"><p className="text-xs text-slate-500">{label}</p><p className="mt-1 text-sm">{value}</p></div>; }
function Proposal({ auditId, findingId, linkId, title, kind, action }: { auditId: string; findingId: string; linkId: string; title: string; kind: string; action: (formData: FormData) => Promise<void> }) { return <div className="flex flex-wrap items-center justify-between gap-3 rounded-xl bg-slate-950/50 p-3"><div><p className="text-sm font-medium">{title}</p><p className="text-xs text-slate-500">{kind} proposal</p></div><form action={action} className="flex gap-2"><Hidden auditId={auditId} findingId={findingId} /><input type="hidden" name="linkId" value={linkId} /><button name="decision" value="REJECT" className="rounded-lg border border-red-400/30 px-3 py-1 text-xs text-red-200">Reject</button><button name="decision" value="APPROVE" className="rounded-lg bg-emerald-400 px-3 py-1 text-xs font-semibold text-slate-950">Approve</button></form></div>; }
