"use client";
import { EnterpriseAuditEvidenceType } from "@prisma/client";
import { upload } from "@vercel/blob/client";
import { Camera, LoaderCircle, Upload } from "lucide-react";
import { useRouter } from "next/navigation";
import { useState } from "react";

export function AuditEvidenceUpload({ auditId, findingId, questionId }: { auditId: string; findingId?: string; questionId?: string }) {
  const router = useRouter(); const [pending, setPending] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  async function submit(formData: FormData) { const file = formData.get("file"); const title = String(formData.get("title") || "").trim(); if (!(file instanceof File) || !file.size || !title) { setError("Enter a title and select an evidence file."); return; } setPending(true); setError(""); setMessage(""); try { const pathname = `audit-evidence/${auditId}/${file.name}`; await upload(pathname, file, { access: "private", handleUploadUrl: "/api/audits/evidence/upload", clientPayload: JSON.stringify({ auditId, findingId, questionId, title, description: String(formData.get("description") || ""), evidenceType: file.type.startsWith("image/") ? EnterpriseAuditEvidenceType.PHOTO : file.type.startsWith("video/") ? EnterpriseAuditEvidenceType.VIDEO : EnterpriseAuditEvidenceType.DOCUMENT, fileName: file.name, fileSize: file.size }) }); setMessage("Evidence uploaded and linked successfully."); router.refresh(); } catch (value) { setError(value instanceof Error ? value.message : "Evidence upload failed."); } finally { setPending(false); } }
  return <form action={submit} className="space-y-3 rounded-2xl border border-white/10 p-4"><div className="flex items-center gap-2 text-sm font-semibold text-cyan-300"><Camera size={16}/> Upload evidence or photo</div><input name="title" required placeholder="Evidence title" className={input}/><textarea name="description" rows={2} placeholder="Description or context" className={input}/><input name="file" type="file" required accept="image/*,video/mp4,application/pdf,.doc,.docx,.txt,.csv" className="block w-full text-xs text-slate-400 file:mr-3 file:rounded-lg file:border-0 file:bg-cyan-300 file:px-3 file:py-2 file:font-semibold file:text-slate-950"/><button disabled={pending} className="inline-flex items-center gap-2 rounded-xl bg-cyan-300 px-4 py-2 text-sm font-semibold text-slate-950 disabled:opacity-50">{pending?<LoaderCircle className="animate-spin" size={16}/>:<Upload size={16}/>} Upload</button>{error&&<p role="alert" className="text-sm text-red-300">{error}</p>}{message&&<p role="status" className="text-sm text-emerald-300">{message}</p>}</form>;
}
const input="w-full rounded-xl border border-white/10 bg-slate-950/70 px-3 py-2 text-sm outline-none focus:border-cyan-400/50";
