import { createAuditSchedule } from "@/features/audits/schedule.actions";
import { requirePermission } from "@/lib/permissions";
import { prisma } from "@/lib/prisma";
import { getCurrentUserTenant } from "@/lib/tenant";
import { EnterpriseAuditFrequency, EnterpriseAuditProgramStatus, EnterpriseAuditProtocolStatus, PermissionKey } from "@prisma/client";
import { ArrowLeft, CalendarClock } from "lucide-react";
import Link from "next/link";

export default async function NewAuditSchedulePage() {
  await requirePermission(PermissionKey.MANAGE_AUDITS); const { organizationId } = await getCurrentUserTenant();
  const [programs, protocols, sites, users] = await Promise.all([
    prisma.auditProgram.findMany({ where: { organizationId, status: EnterpriseAuditProgramStatus.ACTIVE, isActive: true }, select: { id: true, name: true, code: true, defaultProtocolId: true }, orderBy: { name: "asc" } }),
    prisma.auditProtocol.findMany({ where: { organizationId, status: EnterpriseAuditProtocolStatus.ACTIVE, isActive: true }, select: { id: true, name: true, version: true }, orderBy: { name: "asc" } }),
    prisma.site.findMany({ where: { organizationId }, include: { departments: { orderBy: { name: "asc" } } }, orderBy: { name: "asc" } }),
    prisma.user.findMany({ where: { organizationId }, select: { id: true, name: true, jobTitle: true }, orderBy: { name: "asc" } }),
  ]);
  return <div className="mx-auto max-w-5xl"><Link href="/audits/schedules" className="inline-flex items-center gap-2 text-sm text-slate-400 hover:text-white"><ArrowLeft size={16} /> Back to schedules</Link><div className="mt-6"><p className="flex items-center gap-2 text-sm text-cyan-300"><CalendarClock size={16} /> Recurring Audit Planning</p><h1 className="mt-2 text-4xl font-bold">Create Audit Schedule</h1></div>
    {programs.length === 0 ? <div className="mt-8 rounded-3xl border border-amber-400/20 bg-amber-400/5 p-6 text-sm text-amber-200">Activate an Audit Program with an active default protocol before creating a schedule.</div> : <form action={createAuditSchedule} className="mt-8 space-y-7 rounded-3xl border border-white/10 bg-white/5 p-7"><div className="grid gap-5 md:grid-cols-2"><Field label="Schedule name"><input name="name" required className={inputClass} /></Field><Field label="Audit program"><select name="programId" required defaultValue="" className={inputClass}><option value="" disabled>Select program</option>{programs.map((program) => <option key={program.id} value={program.id}>{program.code ? `${program.code} — ` : ""}{program.name}</option>)}</select></Field></div><Field label="Description"><textarea name="description" rows={3} className={inputClass} /></Field>
      <div className="grid gap-5 md:grid-cols-3"><Field label="Frequency"><select name="frequency" defaultValue={EnterpriseAuditFrequency.ANNUAL} className={inputClass}>{Object.values(EnterpriseAuditFrequency).map((value) => <option key={value} value={value}>{pretty(value)}</option>)}</select></Field><Field label="Interval"><input type="number" min="1" name="intervalValue" defaultValue="1" className={inputClass} /></Field><Field label="Timezone"><input name="timezone" defaultValue="America/Chicago" required className={inputClass} /></Field></div>
      <div className="grid gap-5 md:grid-cols-2"><Field label="Start date"><input type="datetime-local" name="startDate" required className={inputClass} /></Field><Field label="End date"><input type="datetime-local" name="endDate" className={inputClass} /></Field></div>
      <div className="grid gap-5 md:grid-cols-2"><Field label="Site"><select name="siteId" required defaultValue="" className={inputClass}><option value="" disabled>Select site</option>{sites.map((site) => <option key={site.id} value={site.id}>{site.name}</option>)}</select></Field><Field label="Department"><select name="departmentId" defaultValue="" className={inputClass}><option value="">All departments</option>{sites.flatMap((site) => site.departments.map((department) => <option key={department.id} value={department.id}>{site.name} — {department.name}</option>))}</select></Field></div>
      <div className="grid gap-5 md:grid-cols-2"><Field label="Protocol"><select name="protocolId" required defaultValue="" className={inputClass}><option value="" disabled>Select active protocol</option>{protocols.map((protocol) => <option key={protocol.id} value={protocol.id}>{protocol.name} v{protocol.version}</option>)}</select></Field><Field label="Lead auditor"><select name="leadAuditorId" required defaultValue="" className={inputClass}><option value="" disabled>Select lead auditor</option>{users.map((user) => <option key={user.id} value={user.id}>{user.name}{user.jobTitle ? ` — ${user.jobTitle}` : ""}</option>)}</select></Field></div>
      <div className="grid gap-5 md:grid-cols-2"><Field label="Generate days before occurrence"><input type="number" min="0" name="generateDaysBefore" defaultValue="30" className={inputClass} /></Field><Field label="Audit due days after occurrence"><input type="number" min="1" name="dueDaysAfter" defaultValue="14" className={inputClass} /></Field></div>
      <fieldset className="rounded-2xl border border-white/10 p-5"><legend className="px-2 text-sm font-medium">Additional audit team</legend><div className="grid gap-3 md:grid-cols-2">{users.map((user) => <label key={user.id} className="flex gap-3 text-sm"><input type="checkbox" name="teamMemberIds" value={user.id} />{user.name}{user.jobTitle ? ` — ${user.jobTitle}` : ""}</label>)}</div></fieldset>
      <div className="grid gap-3 md:grid-cols-3"><Check name="autoGenerate" label="Automatically generate audits" defaultChecked /><Check name="requireTeam" label="Require assigned team" defaultChecked /><Check name="requireLeadAuditor" label="Require lead auditor" defaultChecked /></div><div className="flex justify-end"><button className="rounded-2xl bg-cyan-300 px-6 py-3 text-sm font-semibold text-slate-950">Create Schedule</button></div></form>}
  </div>;
}
const inputClass = "mt-2 w-full rounded-2xl border border-white/10 bg-slate-950/70 px-4 py-3 text-sm outline-none focus:border-cyan-400/50"; function pretty(value: string) { return value.replaceAll("_", " "); } function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block text-sm font-medium text-slate-300">{label}{children}</label>; } function Check({ name, label, defaultChecked = false }: { name: string; label: string; defaultChecked?: boolean }) { return <label className="flex gap-3 text-sm text-slate-300"><input type="checkbox" name={name} defaultChecked={defaultChecked} />{label}</label>; }
