import { ResearchQuestionnaireForm } from "@/features/research/research-forms";
import { getCurrentUserPermissions, requirePermission } from "@/lib/permissions";
import { getCurrentUserTenant } from "@/lib/tenant";
import { listResearchQuestionnaires } from "@/modules/research/research-questionnaire.service";
import { getResearchProject } from "@/modules/research/research.service";
import { PermissionKey } from "@prisma/client";
import { ArrowLeft, ArrowRight, FileQuestion } from "lucide-react";
import Link from "next/link";
import { notFound } from "next/navigation";

export const dynamic="force-dynamic";
export default async function ResearchQuestionnairesPage({params}:{params:Promise<{id:string}>}){await requirePermission(PermissionKey.VIEW_RESEARCH);const[{id},{organizationId},permissions]=await Promise.all([params,getCurrentUserTenant(),getCurrentUserPermissions()]);const [project,questionnaires]=await Promise.all([getResearchProject(organizationId,id),listResearchQuestionnaires(organizationId,id)]);if(!project)notFound();const canDesign=permissions.includes(PermissionKey.DESIGN_RESEARCH_QUESTIONNAIRES);return <div><Link href={`/research/projects/${project.id}`} className="inline-flex items-center gap-2 text-sm text-slate-400"><ArrowLeft size={16}/>{project.reference}</Link><div className="mt-6"><p className="flex items-center gap-2 text-sm text-cyan-300"><FileQuestion size={17}/>Versioned Research Instruments</p><h1 className="mt-2 text-4xl font-bold">Questionnaire Studio</h1><p className="mt-2 max-w-3xl text-slate-400">Create governed questionnaires with stable variables, conditional questions, controlled publication and traceable responses for {project.title}.</p></div>{canDesign?<div className="mt-8"><ResearchQuestionnaireForm projectId={project.id} consentRequired={project.consentRequired}/></div>:null}<section className="mt-8 overflow-hidden rounded-3xl border border-white/10 bg-white/[.035]"><div className="border-b border-white/10 p-6"><h2 className="text-xl font-semibold">Project questionnaires</h2></div><div className="divide-y divide-white/10">{questionnaires.map(questionnaire=>{const published=questionnaire.formDefinition.versions.find(version=>version.status==="PUBLISHED");const draft=questionnaire.formDefinition.versions.find(version=>version.status==="DRAFT");return <Link key={questionnaire.id} href={`/form-studio/${questionnaire.formDefinitionId}`} className="flex flex-wrap items-center justify-between gap-5 p-5 transition hover:bg-white/[.03]"><div><div className="flex flex-wrap gap-2"><span className="rounded-full bg-cyan-400/10 px-2.5 py-1 text-xs text-cyan-200">{pretty(questionnaire.identityMode)}</span><span className="text-xs text-slate-500">{questionnaire.defaultLanguage.toUpperCase()} · {draft?`Draft v${draft.version}`:published?`Published v${published.version}`:"No version"}</span></div><h3 className="mt-2 font-semibold">{questionnaire.name}</h3><p className="mt-1 text-sm text-slate-400">{questionnaire.purpose}</p></div><div className="flex items-center gap-4 text-xs text-slate-500"><span>{questionnaire.formDefinition._count.submissions} submissions</span><ArrowRight size={18}/></div></Link>})}{!questionnaires.length?<div className="p-12 text-center text-sm text-slate-400">No questionnaires have been created for this project.</div>:null}</div></section></div>}
function pretty(value:string){return value.replaceAll("_"," ").toLowerCase().replace(/\b\w/g,letter=>letter.toUpperCase());}
