import { ResearchQuestionnaireForm } from "@/features/research/research-forms";
import { getCurrentUserPermissions,requirePermission } from "@/lib/permissions";
import { getCurrentUserTenant } from "@/lib/tenant";
import { listResearchQuestionnaires } from "@/modules/research/research-questionnaire.service";
import { getResearchProject } from "@/modules/research/research.service";
import { PermissionKey } from "@prisma/client";
import { ArrowLeft,FileQuestion } from "lucide-react";
import Link from "next/link";
import { notFound } from "next/navigation";
export const dynamic="force-dynamic";
export default async function ResearchQuestionnairesPage({params}:{params:Promise<{id:string}>}){await requirePermission(PermissionKey.VIEW_RESEARCH);const[{id},{organizationId},permissions]=await Promise.all([params,getCurrentUserTenant(),getCurrentUserPermissions()]);const[project,questionnaires]=await Promise.all([getResearchProject(organizationId,id),listResearchQuestionnaires(organizationId,id)]);if(!project)notFound();const canDesign=permissions.includes(PermissionKey.DESIGN_RESEARCH_QUESTIONNAIRES),canCollect=permissions.includes(PermissionKey.MANAGE_RESEARCH_DATASETS);return <div><Link href={`/research/projects/${project.id}`} className="inline-flex items-center gap-2 text-sm text-slate-400"><ArrowLeft size={16}/>{project.reference}</Link><div className="mt-6"><p className="flex items-center gap-2 text-sm text-cyan-300"><FileQuestion size={17}/>Versioned Research Instruments</p><h1 className="mt-2 text-4xl font-bold">Questionnaire Studio</h1><p className="mt-2 max-w-3xl text-slate-400">Design, publish and launch traceable data collection for {project.title}.</p></div>{canDesign&&<div className="mt-8"><ResearchQuestionnaireForm projectId={project.id} consentRequired={project.consentRequired}/></div>}<section className="mt-8 overflow-hidden rounded-3xl border border-white/10 bg-white/[.035]"><h2 className="border-b border-white/10 p-6 text-xl font-semibold">Project questionnaires</h2><div className="divide-y divide-white/10">{questionnaires.map(questionnaire=>{const published=questionnaire.formDefinition.versions.find(v=>v.status==="PUBLISHED"),draft=questionnaire.formDefinition.versions.find(v=>v.status==="DRAFT");return <div key={questionnaire.id} className="flex flex-wrap items-center justify-between gap-5 p-5"><div><div className="flex gap-2 text-xs"><span className="rounded-full bg-cyan-400/10 px-2.5 py-1 text-cyan-200">{pretty(questionnaire.identityMode)}</span><span className="px-2.5 py-1 text-slate-500">{draft?`Draft v${draft.version}`:published?`Published v${published.version}`:"No version"}</span></div><h3 className="mt-2 font-semibold">{questionnaire.name}</h3><p className="mt-1 text-sm text-slate-400">{questionnaire.purpose}</p></div><div className="flex flex-wrap gap-3"><Link href={`/form-studio/${questionnaire.formDefinitionId}`} className="rounded-xl border border-white/10 px-4 py-2 text-sm text-cyan-200">Design</Link>{canCollect&&<Link href={`/research/projects/${project.id}/questionnaires/${questionnaire.id}/collections`} className="rounded-xl bg-cyan-300 px-4 py-2 text-sm font-semibold text-slate-950">Data Collection</Link>}</div></div>})}{!questionnaires.length&&<div className="p-12 text-center text-sm text-slate-400">No questionnaires have been created.</div>}</div></section></div>}
function pretty(value:string){return value.replaceAll("_"," ").toLowerCase().replace(/\b\w/g,letter=>letter.toUpperCase())}
