import { getCurrentUserPermissions } from "@/lib/permissions";
import { prisma } from "@/lib/prisma";
import { getCurrentUserTenant } from "@/lib/tenant";
import { PermissionKey } from "@prisma/client";
import { FileText, Search } from "lucide-react";
import Link from "next/link";

type SearchResult = { id: string; type: string; title: string; detail: string; href: string };
const contains = (value: string) => ({ contains: value, mode: "insensitive" as const });

export default async function SearchPage({ searchParams }: { searchParams: Promise<{ q?: string }> }) {
  const [{ organizationId }, permissions, params] = await Promise.all([getCurrentUserTenant(), getCurrentUserPermissions(), searchParams]);
  const query = String(params.q || "").trim().slice(0, 100); const allowed = new Set(permissions); const results: SearchResult[] = [];
  if (query.length >= 2) {
    const [incidents, audits, observations, risks, actions, calendarTasks, contractors, permitsToWork, exposureAssessments, surveillancePrograms, documents] = await Promise.all([
      allowed.has(PermissionKey.VIEW_INCIDENT) ? prisma.incident.findMany({ where: { site: { organizationId }, OR: [{ title: contains(query) }, { description: contains(query) }, { location: contains(query) }] }, include: { site: true }, take: 12, orderBy: { updatedAt: "desc" } }) : [],
      allowed.has(PermissionKey.VIEW_AUDITS) ? prisma.enterpriseAudit.findMany({ where: { organizationId, OR: [{ reference: contains(query) }, { title: contains(query) }, { description: contains(query) }] }, take: 12, orderBy: { updatedAt: "desc" } }) : [],
      allowed.has(PermissionKey.VIEW_OBSERVATIONS) ? prisma.safetyObservation.findMany({ where: { organizationId, OR: [{ reference: contains(query) }, { title: contains(query) }, { description: contains(query) }, { location: contains(query) }] }, take: 12, orderBy: { updatedAt: "desc" } }) : [],
      allowed.has(PermissionKey.VIEW_RISKS) ? prisma.risk.findMany({ where: { organizationId, OR: [{ reference: contains(query) }, { title: contains(query) }, { description: contains(query) }, { hazardType: contains(query) }, { process: contains(query) }] }, take: 12, orderBy: { updatedAt: "desc" } }) : [],
      allowed.has(PermissionKey.CREATE_CAPA) || allowed.has(PermissionKey.UPDATE_CAPA) || allowed.has(PermissionKey.CLOSE_CAPA) ? prisma.correctiveAction.findMany({ where: { assignedTo: { organizationId }, OR: [{ title: contains(query) }, { description: contains(query) }] }, take: 12, orderBy: { updatedAt: "desc" } }) : [],
      allowed.has(PermissionKey.VIEW_COMPLIANCE) ? prisma.complianceCalendarTask.findMany({ where: { organizationId, OR: [{ title: contains(query) }, { description: contains(query) }, { regulatoryReference: contains(query) }, { category: contains(query) }] }, take: 12, orderBy: { updatedAt: "desc" } }) : [],
      allowed.has(PermissionKey.VIEW_CONTRACTORS) ? prisma.contractor.findMany({ where: { organizationId, OR: [{ name: contains(query) }, { legalName: contains(query) }, { registrationNumber: contains(query) }, { services: contains(query) }, { primaryContactName: contains(query) }] }, take: 12, orderBy: { updatedAt: "desc" } }) : [],
      allowed.has(PermissionKey.VIEW_PERMITS_TO_WORK) ? prisma.permitToWork.findMany({ where: { organizationId, OR: [{ reference: contains(query) }, { title: contains(query) }, { description: contains(query) }, { exactLocation: contains(query) }, { workOrderReference: contains(query) }] }, include: { site: true }, take: 12, orderBy: { updatedAt: "desc" } }) : [],
      allowed.has(PermissionKey.VIEW_INDUSTRIAL_HYGIENE) ? prisma.exposureAssessment.findMany({ where: { organizationId, OR: [{ reference: contains(query) }, { title: contains(query) }, { description: contains(query) }, { scope: contains(query) }, { group: { name: contains(query) } }] }, include: { site: true, group: true }, take: 12, orderBy: { updatedAt: "desc" } }) : [],
      allowed.has(PermissionKey.VIEW_OCCUPATIONAL_HEALTH) ? prisma.medicalSurveillanceProgram.findMany({ where: { organizationId, OR: [{ name: contains(query) }, { description: contains(query) }, { regulatoryBasis: contains(query) }, { protocolReference: contains(query) }, { providerName: contains(query) }] }, take: 12, orderBy: { updatedAt: "desc" } }) : [],
      allowed.has(PermissionKey.MANAGE_DOCUMENTS) ? prisma.document.findMany({ where: { organizationId, deletedAt: null, isLatest: true, OR: [{ name: contains(query) }, { originalName: contains(query) }, { description: contains(query) }] }, take: 12, orderBy: { updatedAt: "desc" } }) : [],
    ]);
    results.push(...incidents.map(item=>({id:item.id,type:"Incident",title:item.title,detail:`${item.type.replaceAll("_"," ")} · ${item.status.replaceAll("_"," ")} · ${item.site.name}`,href:`/incidents/${item.id}`})), ...audits.map(item=>({id:item.id,type:"Audit",title:`${item.reference} — ${item.title}`,detail:item.status.replaceAll("_"," "),href:`/audits/${item.id}`})), ...observations.map(item=>({id:item.id,type:"Observation",title:`${item.reference} — ${item.title}`,detail:`${item.type.replaceAll("_"," ")} · ${item.status.replaceAll("_"," ")}`,href:`/observations/${item.id}`})), ...risks.map(item=>({id:item.id,type:"Risk",title:`${item.reference} — ${item.title}`,detail:`${item.category.replaceAll("_"," ")} · ${item.status.replaceAll("_"," ")}`,href:`/risks/${item.id}`})), ...actions.map(item=>({id:item.id,type:"Corrective Action",title:item.title,detail:`${item.riskLevel} · ${item.status.replaceAll("_"," ")} · Due ${item.dueDate.toLocaleDateString()}`,href:"/capa"})), ...calendarTasks.map(item=>({id:item.id,type:"Compliance Calendar",title:item.title,detail:`${item.category.replaceAll("_"," ")} · ${item.status.replaceAll("_"," ")}`,href:"/compliance/calendar"})), ...contractors.map(item=>({id:item.id,type:"Contractor",title:item.name,detail:`${item.status.replaceAll("_"," ")} · ${item.services||"Services not recorded"}`,href:`/contractors/${item.id}`})), ...permitsToWork.map(item=>({id:item.id,type:"Permit to Work",title:`${item.reference} — ${item.title}`,detail:`${item.type.replaceAll("_"," ")} · ${item.status.replaceAll("_"," ")} · ${item.site.name}`,href:`/permits-to-work/${item.id}`})), ...exposureAssessments.map(item=>({id:item.id,type:"Industrial Hygiene",title:`${item.reference} — ${item.title}`,detail:`${item.group.name} · ${item.status.replaceAll("_"," ")} · ${item.site.name}`,href:`/industrial-hygiene/${item.id}`})), ...surveillancePrograms.map(item=>({id:item.id,type:"Occupational Health",title:item.name,detail:`Administrative surveillance program · ${item.status.replaceAll("_"," ")}`,href:`/occupational-health/${item.id}`})), ...documents.map(item=>({id:item.id,type:"Document",title:item.name,detail:`${item.category.replaceAll("_"," ")} · Version ${item.version}`,href:"/documents"})));
  }
  const grouped = [...new Set(results.map(result=>result.type))];
  return <div className="mx-auto max-w-5xl"><p className="flex items-center gap-2 text-sm text-cyan-300"><Search size={16}/>Tenant-wide discovery</p><h1 className="mt-2 text-4xl font-bold">Search Senzilytics</h1><form action="/search" className="mt-7 flex gap-3 rounded-2xl border border-white/10 bg-white/5 p-3"><Search className="ml-2 self-center text-slate-500" size={20}/><input type="search" name="q" required minLength={2} maxLength={100} defaultValue={query} autoFocus placeholder="Search references, titles, descriptions, locations..." className="min-w-0 flex-1 bg-transparent px-2 text-white outline-none placeholder:text-slate-600"/><button className="rounded-xl bg-cyan-300 px-5 py-3 font-semibold text-slate-950">Search</button></form>
    {query.length < 2 ? <Empty text="Enter at least two characters to search records available to your role."/> : results.length === 0 ? <Empty text={`No accessible records matched “${query}”.`}/> : <div className="mt-10 space-y-8">{grouped.map(group=><section key={group}><div className="flex items-center justify-between"><h2 className="text-lg font-semibold">{group}</h2><span className="text-xs text-slate-500">{results.filter(x=>x.type===group).length} result(s)</span></div><div className="mt-3 space-y-3">{results.filter(x=>x.type===group).map(result=><Link key={`${result.type}-${result.id}`} href={result.href} className="flex items-center gap-4 rounded-2xl border border-white/10 bg-white/[.035] p-5 transition hover:border-cyan-400/30 hover:bg-cyan-400/[.04]"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-cyan-300/10 text-cyan-300"><FileText size={18}/></span><span className="min-w-0"><strong className="block truncate text-sm">{result.title}</strong><span className="mt-1 block text-xs text-slate-500">{result.detail}</span></span><span className="ml-auto text-cyan-300">→</span></Link>)}</div></section>)}</div>}
  </div>;
}
function Empty({text}:{text:string}){return <p className="mt-10 rounded-3xl border border-dashed border-white/10 p-10 text-center text-slate-500">{text}</p>}
