import { ResearchClientForm } from "@/features/research/research-forms";
import { requirePermission } from "@/lib/permissions";
import { getCurrentUserTenant } from "@/lib/tenant";
import { listResearchClients } from "@/modules/research/research.service";
import { PermissionKey } from "@prisma/client";
import { Building2, DatabaseZap } from "lucide-react";

export const dynamic="force-dynamic";
export default async function ResearchClientsPage(){await requirePermission(PermissionKey.MANAGE_RESEARCH_CLIENTS);const {organizationId}=await getCurrentUserTenant();const clients=await listResearchClients(organizationId);return <div><div><p className="flex items-center gap-2 text-sm text-cyan-300"><Building2 size={17}/>Commissioned Research Governance</p><h1 className="mt-2 text-4xl font-bold">Research Clients & Data Owners</h1><p className="mt-2 max-w-3xl text-slate-400">Identify the contracting organization, legal data owner, approved contacts, classification and retention expectations before a commissioned project is opened.</p></div><div className="mt-8"><ResearchClientForm/></div><section className="mt-8 overflow-hidden rounded-3xl border border-white/10 bg-white/[.035]"><div className="flex items-center justify-between border-b border-white/10 p-6"><div><h2 className="text-xl font-semibold">Controlled client register</h2><p className="mt-1 text-sm text-slate-500">Client identity is always subordinate to tenant isolation.</p></div><DatabaseZap size={19} className="text-cyan-300"/></div><div className="divide-y divide-white/10">{clients.map(client=><div key={client.id} className="grid gap-4 p-5 md:grid-cols-[1.3fr_1fr_1fr_auto] md:items-center"><div><h3 className="font-semibold">{client.name}</h3><p className="mt-1 text-xs text-slate-500">{client.code??"No code"} · {client.industry??"Industry not recorded"}</p></div><div className="text-sm text-slate-300"><span className="block text-xs text-slate-500">Legal data owner</span>{client.dataOwnerName??"Not specified"}</div><div className="text-sm text-slate-300"><span className="block text-xs text-slate-500">Classification</span>{pretty(client.dataClassification)}</div><div className="text-right text-sm"><span className="rounded-full bg-emerald-400/10 px-2.5 py-1 text-xs text-emerald-200">{pretty(client.status)}</span><p className="mt-2 text-xs text-slate-500">{client._count.projects} projects</p></div></div>)}{!clients.length?<div className="p-12 text-center text-sm text-slate-400">No research clients have been registered.</div>:null}</div></section></div>}
function pretty(value:string){return value.replaceAll("_"," ").toLowerCase().replace(/\b\w/g,letter=>letter.toUpperCase());}
