import { getCurrentUserPermissions, hasPermission, requirePermission } from "@/lib/permissions";
import { getCurrentUserTenant } from "@/lib/tenant";
import { getUnifiedCalendarItems, type UnifiedCalendarSource } from "@/modules/compliance/unified-calendar.service";
import { PermissionKey } from "@prisma/client";
import { BarChart3, CalendarDays, Plus } from "lucide-react";
import Link from "next/link";

const sourceLabels:Record<UnifiedCalendarSource,string>={COMPLIANCE_CALENDAR:"Calendar Tasks",COMPLIANCE_OBLIGATION:"Obligations",OBSERVATION:"Observations",AUDIT:"Audits",AUDIT_FINDING:"Audit Findings",INSPECTION:"Inspections",CAPA:"Corrective Actions",TRAINING:"Training",PERMIT:"Regulatory Permits",CONTRACTOR:"Contractor Credentials",PERMIT_TO_WORK:"Permits to Work",RISK_REVIEW:"Risk Reviews",MOC:"MOC Tasks",WORKFLOW:"Workflow Tasks"};
export default async function ComplianceCalendarPage({searchParams}:{searchParams:Promise<{month?:string;scope?:string;source?:string}>}){
  await requirePermission(PermissionKey.VIEW_COMPLIANCE);
  const[{organizationId,user},canManage,permissions,query]=await Promise.all([getCurrentUserTenant(),hasPermission(PermissionKey.MANAGE_COMPLIANCE),getCurrentUserPermissions(),searchParams]);
  const selected=/^\d{4}-\d{2}$/.test(query.month||"")?query.month!:new Date().toISOString().slice(0,7),start=new Date(`${selected}-01T00:00:00.000Z`),end=new Date(start);end.setUTCMonth(end.getUTCMonth()+1);
  const allItems=await getUnifiedCalendarItems({organizationId,userId:user.id,userRole:user.role,permissions,start,end,mineOnly:query.scope==="mine"});
  const selectedSource=Object.keys(sourceLabels).includes(query.source||"")?query.source as UnifiedCalendarSource:null,items=selectedSource?allItems.filter(entry=>entry.source===selectedSource):allItems;
  const days=Array.from({length:new Date(start.getUTCFullYear(),start.getUTCMonth()+1,0).getDate()},(_,index)=>index+1),previous=new Date(start),next=new Date(start);previous.setUTCMonth(previous.getUTCMonth()-1);next.setUTCMonth(next.getUTCMonth()+1);
  const suffix=(month=selected)=>`?month=${month}${query.scope==="mine"?"&scope=mine":""}${selectedSource?`&source=${selectedSource}`:""}`;
  return <div><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="flex items-center gap-2 text-sm text-cyan-300"><CalendarDays size={17}/>Unified Operational Assurance</p><h1 className="mt-2 text-4xl font-bold">Compliance Calendar</h1><p className="mt-2 max-w-3xl text-slate-400">Compliance obligations and assigned work from audits, inspections, CAPA, training, contractors, permits to work, risks, MOC and workflows—without duplicating source records.</p></div><div className="flex flex-wrap gap-3"><Link href="/compliance/calendar/analytics" className="inline-flex items-center gap-2 rounded-xl border border-white/10 px-4 py-2"><BarChart3 size={16}/>Analytics</Link>{canManage&&<Link href="/compliance/calendar/new" className="inline-flex items-center gap-2 rounded-xl bg-cyan-300 px-4 py-2 font-semibold text-slate-950"><Plus size={16}/>New Recurring Task</Link>}</div></div>
    <div className="mt-7 flex flex-wrap items-center justify-between gap-4 rounded-2xl border border-white/10 bg-white/5 p-4"><div className="flex gap-2"><Link href={`?month=${selected}${selectedSource?`&source=${selectedSource}`:""}`} className={`rounded-lg px-3 py-2 text-sm ${query.scope!=="mine"?"bg-cyan-300 text-slate-950":"bg-white/5"}`}>Organization</Link><Link href={`?month=${selected}&scope=mine${selectedSource?`&source=${selectedSource}`:""}`} className={`rounded-lg px-3 py-2 text-sm ${query.scope==="mine"?"bg-cyan-300 text-slate-950":"bg-white/5"}`}>My Calendar</Link></div><form className="flex items-center gap-2"><input type="hidden" name="month" value={selected}/>{query.scope==="mine"&&<input type="hidden" name="scope" value="mine"/>}<label className="text-xs text-slate-500">Source</label><select name="source" defaultValue={selectedSource??""} className="rounded-xl border border-white/10 bg-slate-950 px-3 py-2 text-sm"><option value="">All modules</option>{Object.entries(sourceLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><button className="rounded-xl border border-white/10 px-3 py-2 text-sm">Apply</button></form><div className="flex items-center gap-3 text-sm"><Link href={suffix(previous.toISOString().slice(0,7))}>← Previous</Link><strong>{start.toLocaleDateString("en-US",{month:"long",year:"numeric",timeZone:"UTC"})}</strong><Link href={suffix(next.toISOString().slice(0,7))}>Next →</Link></div></div>
    <div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-7">{days.map(day=>{const dayItems=items.filter(entry=>entry.date.getUTCDate()===day);return <section key={day} className="min-h-40 rounded-2xl border border-white/10 bg-white/[.04] p-3"><p className="text-sm font-semibold text-slate-400">{day}</p><div className="mt-2 space-y-2">{dayItems.map(entry=><Link key={entry.id} href={entry.href} className={`block rounded-xl border-l-2 bg-slate-950/70 p-3 text-xs transition hover:bg-slate-900 ${entry.overdue?"border-red-400":entry.completed?"border-emerald-400":"border-cyan-400"}`}><p className="text-[10px] font-semibold uppercase tracking-wide text-cyan-300">{entry.sourceLabel}</p><p className="mt-1 line-clamp-2 font-medium text-white">{entry.title}</p><p className={`mt-1 ${entry.overdue?"text-red-300":entry.completed?"text-emerald-300":"text-slate-400"}`}>{entry.overdue?"OVERDUE":entry.status.replaceAll("_"," ")}</p><p className="mt-1 truncate text-slate-500">{entry.assignee}{entry.site?` · ${entry.site}`:""}</p></Link>)}</div></section>})}</div>
    {!items.length&&<p className="mt-5 rounded-2xl border border-dashed border-white/10 p-8 text-center text-slate-500">No accessible calendar items match this month and filter.</p>}
  </div>;
}
