import { requirePermission } from "@/lib/permissions";
import { getCurrentUserTenant } from "@/lib/tenant";
import { getBehaviorSafetyDashboardService } from "@/modules/behavior-safety/behavior-safety.service";
import { PermissionKey } from "@prisma/client";
import { ArrowLeft, BarChart3 } from "lucide-react";
import Link from "next/link";

export default async function BehaviorSafetyDashboardPage() {
  await requirePermission(PermissionKey.VIEW_BEHAVIOR_SAFETY); const { organizationId } = await getCurrentUserTenant(); const { sessions, hotspots, metrics } = await getBehaviorSafetyDashboardService(organizationId);
  const monthRows = Array.from({ length: 6 }, (_, index) => { const date = new Date(); date.setUTCDate(1); date.setUTCHours(0, 0, 0, 0); date.setUTCMonth(date.getUTCMonth() - (5 - index)); const next = new Date(date); next.setUTCMonth(next.getUTCMonth() + 1); const rows = sessions.filter(session => session.observedAt >= date && session.observedAt < next); return { label: date.toLocaleDateString("en-US", { month: "short", timeZone: "UTC" }), sessions: rows.length, safe: rows.reduce((sum, row) => sum + row.safeCount, 0), atRisk: rows.reduce((sum, row) => sum + row.atRiskCount, 0) }; });
  const maxSessions = Math.max(1, ...monthRows.map(row => row.sessions));
  return <div><Link href="/behavior-safety" className="inline-flex items-center gap-2 text-sm text-slate-400"><ArrowLeft size={16} />Behavior-Based Safety</Link><p className="mt-6 flex items-center gap-2 text-sm text-cyan-300"><BarChart3 size={17} />Leading indicators</p><h1 className="mt-2 text-4xl font-bold">Behavior-Safety Analytics</h1><p className="mt-2 max-w-3xl text-slate-400">Monitor engagement, safe-behavior reinforcement, coaching targets, critical exposure, and recognition without ranking or penalizing individual workers.</p><div className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{Object.entries(metrics).map(([label, value]) => <div key={label} className="rounded-2xl border border-white/10 bg-white/5 p-5"><p className="text-xs uppercase tracking-wide text-slate-500">{label.replace(/([A-Z])/g, " $1")}</p><p className="mt-2 text-3xl font-bold">{value}{["targetAchievement", "safeRate", "participationRate"].includes(label) ? "%" : ""}</p></div>)}</div><div className="mt-8 grid gap-6 xl:grid-cols-2"><section className="rounded-3xl border border-white/10 bg-white/5 p-6"><h2 className="text-xl font-semibold">Six-month coaching trend</h2><div className="mt-6 grid h-64 grid-cols-6 items-end gap-3">{monthRows.map(row => <div key={row.label} className="flex h-full flex-col justify-end text-center"><p className="mb-2 text-xs text-slate-400">{row.sessions}</p><div className="mx-auto w-full max-w-12 rounded-t-lg bg-cyan-300/80" style={{ height: `${Math.max(4, row.sessions / maxSessions * 180)}px` }} /><p className="mt-2 text-xs text-slate-500">{row.label}</p></div>)}</div><div className="mt-4 flex gap-5 text-xs text-slate-500"><span>{monthRows.reduce((sum, row) => sum + row.safe, 0)} safe observations</span><span>{monthRows.reduce((sum, row) => sum + row.atRisk, 0)} at-risk observations</span></div></section><section className="rounded-3xl border border-white/10 bg-white/5 p-6"><h2 className="text-xl font-semibold">At-risk behavior hotspots</h2><div className="mt-5 space-y-4">{hotspots.filter(row => row.atRisk > 0).slice(0, 10).map(row => <div key={`${row.category}-${row.title}`}><div className="flex justify-between gap-4 text-sm"><span>{row.title}<small className="ml-2 text-slate-500">{row.category.replaceAll("_", " ")}</small></span><span className="text-amber-300">{row.atRisk}/{row.total}</span></div><div className="mt-2 h-2 rounded-full bg-white/10"><div className="h-2 rounded-full bg-amber-300" style={{ width: `${Math.max(3, row.atRisk / Math.max(row.total, 1) * 100)}%` }} /></div></div>)}{!hotspots.some(row => row.atRisk > 0) && <p className="text-sm text-emerald-300">No at-risk behavior hotspots in the reporting period.</p>}</div></section></div></div>;
}
