import { requirePermission } from "@/lib/permissions";
import { getCurrentUserTenant } from "@/lib/tenant";
import { findTenantAuditSchedules } from "@/modules/audit/audit-schedule.repository";
import { EnterpriseAuditScheduleStatus, PermissionKey } from "@prisma/client";
import { ArrowLeft, CalendarClock, Plus } from "lucide-react";
import Link from "next/link";

export default async function AuditSchedulesPage() {
  await requirePermission(PermissionKey.VIEW_AUDITS); const { organizationId } = await getCurrentUserTenant(); const schedules = await findTenantAuditSchedules(organizationId);
  const active = schedules.filter((schedule) => schedule.status === EnterpriseAuditScheduleStatus.ACTIVE).length;
  return <div><Link href="/audits" className="inline-flex items-center gap-2 text-sm text-slate-400 hover:text-white"><ArrowLeft size={16} /> Back to audits</Link><div className="mt-6 flex flex-wrap items-start justify-between gap-5"><div><p className="flex items-center gap-2 text-sm text-cyan-300"><CalendarClock size={16} /> Audit Planning</p><h1 className="mt-2 text-4xl font-bold">Audit Schedules</h1><p className="mt-2 max-w-3xl text-slate-400">Control recurring audit generation, lead ownership, team composition, protocols, and due-date rules.</p></div><Link href="/audits/schedules/new" className="inline-flex items-center gap-2 rounded-2xl bg-cyan-300 px-5 py-3 text-sm font-semibold text-slate-950"><Plus size={17} /> Create Schedule</Link></div>
    <div className="mt-8 grid gap-4 md:grid-cols-3"><Metric label="Active schedules" value={active} /><Metric label="Generated audits" value={schedules.reduce((sum, schedule) => sum + schedule._count.enterpriseAudits, 0)} /><Metric label="Assigned team members" value={schedules.reduce((sum, schedule) => sum + schedule._count.teamMembers, 0)} /></div>
    <div className="mt-8 grid gap-5">{schedules.length === 0 ? <p className="rounded-3xl border border-dashed border-white/15 p-12 text-center text-slate-500">No audit schedules yet.</p> : schedules.map((schedule) => <Link key={schedule.id} href={`/audits/schedules/${schedule.id}`} className="rounded-3xl border border-white/10 bg-white/5 p-6 transition hover:border-cyan-400/30"><div className="flex flex-wrap justify-between gap-4"><div><p className="text-xs text-cyan-300">{schedule.program.code || "PROGRAM"} · {pretty(schedule.frequency)}</p><h2 className="mt-2 text-xl font-semibold">{schedule.name}</h2><p className="mt-2 text-sm text-slate-400">{schedule.description || schedule.program.name}</p></div><Badge value={schedule.status} /></div><div className="mt-6 grid gap-4 md:grid-cols-4"><Info label="Site" value={schedule.site.name} /><Info label="Lead auditor" value={schedule.leadAuditor?.name || "Not assigned"} /><Info label="Next generation" value={formatDate(schedule.nextRunAt)} /><Info label="Generated audits" value={String(schedule._count.enterpriseAudits)} /></div></Link>)}</div>
  </div>;
}
function pretty(value: string) { return value.replaceAll("_", " "); } function formatDate(value: Date | null) { return value ? value.toLocaleDateString() : "Not scheduled"; } function Badge({ value }: { value: string }) { return <span className="h-fit rounded-full border border-cyan-400/30 bg-cyan-400/10 px-3 py-1 text-xs text-cyan-200">{pretty(value)}</span>; } function Metric({ label, value }: { label: string; value: number }) { return <div className="rounded-3xl border border-white/10 bg-white/5 p-5"><p className="text-sm text-slate-400">{label}</p><p className="mt-3 text-3xl font-bold">{value}</p></div>; } function Info({ label, value }: { label: string; value: string }) { return <div className="rounded-2xl bg-slate-950/40 p-4"><p className="text-xs uppercase text-slate-500">{label}</p><p className="mt-2 text-sm">{value}</p></div>; }
