"use client";

import { initialFormActionState, type FormActionState } from "@/core/actions/action-state";
import {
  changeAssetStatus,
  changeAssetMaintenanceStatus,
  completeAssetMaintenance,
  createAsset,
  createAssetDefect,
  createAssetDefectCapa,
  recordAssetInspection,
  scheduleAssetMaintenance,
  updateAssetDefect,
} from "@/features/assets/actions";
import { RuntimeFormFields } from "@/features/forms/runtime-form-fields";
import {
  AssetDefectStatus,
  AssetInspectionResult,
  AssetMaintenanceType,
  AssetMaintenanceStatus,
  AssetStatus,
  AssetType,
  RiskLevel,
} from "@prisma/client";
import { useActionState, type ReactNode } from "react";

type Option = { id: string; name: string };
type Forms = Parameters<typeof RuntimeFormFields>[0]["forms"];
const input = "mt-2 w-full rounded-xl border border-white/10 bg-slate-950/60 px-3 py-2 text-sm text-white outline-none focus:border-cyan-300/60";
const button = "mt-5 rounded-xl bg-cyan-300 px-5 py-3 font-semibold text-slate-950 disabled:opacity-50";
const card = "rounded-3xl border border-white/10 bg-white/5 p-6";

function Feedback({ state }: { state: FormActionState }) { if (state.status === "IDLE") return null; return <p role={state.status === "ERROR" ? "alert" : "status"} className={`mt-4 rounded-xl border p-3 text-sm ${state.status === "ERROR" ? "border-red-400/20 bg-red-400/10 text-red-200" : "border-emerald-400/20 bg-emerald-400/10 text-emerald-200"}`}>{state.message}</p>; }
function Field({ name, label, type = "text", required, defaultValue }: { name: string; label: string; type?: string; required?: boolean; defaultValue?: string | number }) { return <label className="text-sm">{label}{required && <span className="text-red-300"> *</span>}<input name={name} type={type} required={required} defaultValue={defaultValue} className={input} /></label>; }
function Area({ name, label, required }: { name: string; label: string; required?: boolean }) { return <label className="mt-4 block text-sm">{label}{required && <span className="text-red-300"> *</span>}<textarea name={name} required={required} rows={3} className={input} /></label>; }
function Select({ name, label, values, required, empty = "Select" }: { name: string; label: string; values: readonly string[]; required?: boolean; empty?: string }) { return <label className="text-sm">{label}{required && <span className="text-red-300"> *</span>}<select name={name} required={required} className={input}>{!required && <option value="">{empty}</option>}{values.map(value => <option key={value} value={value}>{value.replaceAll("_", " ")}</option>)}</select></label>; }
function UserSelect({ name, label, users, required }: { name: string; label: string; users: Option[]; required?: boolean }) { return <label className="text-sm">{label}{required && <span className="text-red-300"> *</span>}<select name={name} required={required} className={input}><option value="">{required ? "Select" : "Unassigned"}</option>{users.map(user => <option key={user.id} value={user.id}>{user.name}</option>)}</select></label>; }
function ManagedForm({ action, title, children, submitLabel }: { action: (state: FormActionState, data: FormData) => Promise<FormActionState>; title: string; children: ReactNode; submitLabel: string }) { const [state, formAction, pending] = useActionState(action, initialFormActionState); return <form action={formAction} className={card}><h2 className="text-xl font-semibold">{title}</h2>{children}<button disabled={pending} className={button}>{pending ? "Saving…" : submitLabel}</button><Feedback state={state} /></form>; }

export function AssetCreateForm({ sites, departments, users }: { sites: Option[]; departments: Array<Option & { siteId: string; siteName: string }>; users: Option[] }) {
  const [state, action, pending] = useActionState(createAsset, initialFormActionState);
  return <form action={action} className="mt-8 space-y-6 rounded-3xl border border-white/10 bg-white/5 p-7"><div className="grid gap-4 md:grid-cols-3"><Field name="reference" label="Asset reference" required /><Field name="name" label="Asset name" required /><Select name="type" label="Asset type" values={Object.values(AssetType)} required /><Select name="criticality" label="Criticality" values={Object.values(RiskLevel)} required /><label className="text-sm">Site <span className="text-red-300">*</span><select name="siteId" required className={input}><option value="">Select</option>{sites.map(site => <option key={site.id} value={site.id}>{site.name}</option>)}</select></label><label className="text-sm">Department<select name="departmentId" className={input}><option value="">None</option>{departments.map(department => <option key={department.id} value={department.id}>{department.siteName} — {department.name}</option>)}</select></label><UserSelect name="ownerId" label="Asset owner" users={users} /><Field name="location" label="Physical location" /><Field name="manufacturer" label="Manufacturer" /><Field name="modelNumber" label="Model number" /><Field name="serialNumber" label="Serial number" /><Field name="commissionedAt" label="Commissioned date" type="date" /><Field name="inspectionIntervalDays" label="Inspection interval (days)" type="number" defaultValue={30} required /><Field name="maintenanceIntervalDays" label="Maintenance interval (days)" type="number" defaultValue={90} required /></div><Area name="description" label="Description" /><div className="flex flex-wrap gap-6"><label className="flex items-center gap-2 text-sm"><input name="isSafetyCritical" type="checkbox" />Safety-critical asset</label><label className="flex items-center gap-2 text-sm"><input name="permitRequired" type="checkbox" />Permit required for work</label></div><Feedback state={state} /><button disabled={pending} className={button}>{pending ? "Registering…" : "Register Asset"}</button></form>;
}

export function AssetStatusForm({ assetId, currentStatus }: { assetId: string; currentStatus: AssetStatus }) { return <ManagedForm action={changeAssetStatus} title="Asset lifecycle" submitLabel="Change Status"><input type="hidden" name="assetId" value={assetId} /><p className="mt-2 text-sm text-slate-400">Current: {currentStatus.replaceAll("_", " ")}</p><div className="mt-4 grid gap-4 sm:grid-cols-2"><Select name="status" label="New status" values={Object.values(AssetStatus).filter(value => value !== currentStatus)} required /><Field name="reason" label="Reason" required /></div></ManagedForm>; }

export function AssetInspectionForm({ assetId, forms }: { assetId: string; forms: Forms }) { return <ManagedForm action={recordAssetInspection} title="Record safety inspection" submitLabel="Record Inspection"><input type="hidden" name="assetId" value={assetId} /><div className="mt-4 grid gap-4 md:grid-cols-3"><Field name="inspectedAt" label="Inspected at" type="datetime-local" required /><Select name="result" label="Result" values={Object.values(AssetInspectionResult)} required /><Field name="conditionScore" label="Condition score (1–5)" type="number" /><Field name="evidenceReference" label="Evidence reference" /></div><Area name="observations" label="Observations / defect description" /><Area name="immediateAction" label="Immediate action or isolation" /><div className="mt-5"><RuntimeFormFields forms={forms} /></div></ManagedForm>; }

export function AssetDefectForm({ assetId, users }: { assetId: string; users: Option[] }) { return <ManagedForm action={createAssetDefect} title="Report a defect" submitLabel="Report Defect"><input type="hidden" name="assetId" value={assetId} /><div className="mt-4 grid gap-4 md:grid-cols-2"><Field name="title" label="Defect title" required /><Select name="severity" label="Severity" values={Object.values(RiskLevel)} required /><UserSelect name="ownerId" label="Defect owner" users={users} /><Field name="dueDate" label="Due date" type="date" /></div><Area name="description" label="Description" required /><Area name="immediateControls" label="Immediate controls" /></ManagedForm>; }

export function AssetDefectStatusForm({ assetId, defectId, status }: { assetId: string; defectId: string; status: AssetDefectStatus }) { return <ManagedForm action={updateAssetDefect} title="Update defect" submitLabel="Update Defect"><input type="hidden" name="assetId" value={assetId} /><input type="hidden" name="defectId" value={defectId} /><p className="mt-2 text-sm text-slate-400">Current: {status.replaceAll("_", " ")}</p><div className="mt-4 grid gap-4 sm:grid-cols-2"><Select name="status" label="New status" values={Object.values(AssetDefectStatus).filter(value => value !== status)} required /><Field name="repairPlan" label="Repair plan" /><Field name="verificationEvidence" label="Verification evidence" /></div></ManagedForm>; }

export function AssetMaintenanceForm({ assetId, users, defects }: { assetId: string; users: Option[]; defects: Array<Option & { reference: string }> }) { return <ManagedForm action={scheduleAssetMaintenance} title="Schedule maintenance" submitLabel="Schedule Work"><input type="hidden" name="assetId" value={assetId} /><div className="mt-4 grid gap-4 md:grid-cols-3"><Select name="type" label="Maintenance type" values={Object.values(AssetMaintenanceType)} required /><Field name="title" label="Work title" required /><label className="text-sm">Related defect<select name="defectId" className={input}><option value="">None</option>{defects.map(defect => <option key={defect.id} value={defect.id}>{defect.reference} — {defect.name}</option>)}</select></label><Field name="scheduledAt" label="Scheduled date" type="date" required /><Field name="dueAt" label="Due date" type="date" required /><UserSelect name="technicianId" label="Assigned technician" users={users} /><Field name="serviceProvider" label="Service provider" /><Field name="workOrderReference" label="Work-order reference" /></div></ManagedForm>; }

export function CompleteMaintenanceForm({ assetId, recordId, title }: { assetId: string; recordId: string; title: string }) { return <ManagedForm action={completeAssetMaintenance} title={`Complete: ${title}`} submitLabel="Complete Work"><input type="hidden" name="assetId" value={assetId} /><input type="hidden" name="recordId" value={recordId} /><div className="mt-4 grid gap-4 sm:grid-cols-2"><Field name="completedAt" label="Completed at" type="datetime-local" required /><Field name="evidenceReference" label="Evidence reference" required /><Field name="downtimeHours" label="Downtime hours" type="number" /></div><Area name="workSummary" label="Work summary" required /></ManagedForm>; }

export function MaintenanceStatusForm({ assetId, recordId, status }: { assetId: string; recordId: string; status: AssetMaintenanceStatus }) { return <ManagedForm action={changeAssetMaintenanceStatus} title="Maintenance lifecycle" submitLabel="Update Work Status"><input type="hidden" name="assetId" value={assetId} /><input type="hidden" name="recordId" value={recordId} /><p className="mt-2 text-sm text-slate-400">Current: {status.replaceAll("_", " ")}</p><div className="mt-4 grid gap-4 sm:grid-cols-2"><Select name="status" label="New status" values={[AssetMaintenanceStatus.IN_PROGRESS, AssetMaintenanceStatus.CANCELLED]} required /><Field name="reason" label="Reason / work note" required /></div></ManagedForm>; }

export function AssetDefectCapaForm({ assetId, defectId, reference, users }: { assetId: string; defectId: string; reference: string; users: Option[] }) { return <ManagedForm action={createAssetDefectCapa} title="Link corrective action" submitLabel="Create CAPA"><input type="hidden" name="assetId" value={assetId} /><input type="hidden" name="defectId" value={defectId} /><div className="mt-4 grid gap-4 sm:grid-cols-2"><Field name="title" label="Corrective-action title" defaultValue={`${reference} corrective action`} required /><UserSelect name="assignedToId" label="Assigned owner" users={users} required /><Field name="dueDate" label="Due date" type="date" required /></div><Area name="description" label="Description" /></ManagedForm>; }
