import { CriticalControlCreateForm } from "@/features/assurance/sif-forms";
import { getCurrentUserPermissions, requirePermission } from "@/lib/permissions";
import { prisma } from "@/lib/prisma";
import { getCurrentUserTenant } from "@/lib/tenant";
import { CriticalControlVerificationResult, PermissionKey } from "@prisma/client";
import { ArrowLeft, Plus, ShieldCheck } from "lucide-react";
import Link from "next/link";

export default async function CriticalControlLibraryPage(){
  await requirePermission(PermissionKey.VIEW_SIF_INTELLIGENCE);const[{organizationId},permissions]=await Promise.all([getCurrentUserTenant(),getCurrentUserPermissions()]);const canManage=permissions.includes(PermissionKey.MANAGE_CRITICAL_CONTROLS),now=new Date();
  const[controls,sites,departments,users]=await Promise.all([prisma.criticalControlStandard.findMany({where:{organizationId},include:{site:true,department:true,owner:true,verifications:{orderBy:{verifiedAt:"desc"},take:1}},orderBy:{name:"asc"}}),prisma.site.findMany({where:{organizationId},select:{id:true,name:true},orderBy:{name:"asc"}}),prisma.department.findMany({where:{site:{organizationId}},include:{site:true},orderBy:{name:"asc"}}),prisma.user.findMany({where:{organizationId,isActive:true},select:{id:true,name:true},orderBy:{name:"asc"}})]);
  const active=controls.filter(x=>x.isActive),effective=active.filter(x=>x.verifications[0]?.result===CriticalControlVerificationResult.EFFECTIVE&&x.nextVerificationDueAt>=now).length,failed=active.filter(x=>x.verifications[0]?.result===CriticalControlVerificationResult.FAILED||x.verifications[0]?.result===CriticalControlVerificationResult.DEGRADED).length,overdue=active.filter(x=>x.nextVerificationDueAt<now).length;
  return <div><Link href="/assurance/sif" className="inline-flex items-center gap-2 text-sm text-slate-400"><ArrowLeft size={16}/>SIF Intelligence</Link><div className="mt-6"><p className="flex items-center gap-2 text-sm text-cyan-300"><ShieldCheck size={17}/>Control Performance Standards</p><h1 className="mt-2 text-4xl font-bold">Critical Control Library</h1><p className="mt-2 max-w-3xl text-slate-400">Define the controls that prevent high-consequence events, assign ownership, and maintain field-verification evidence.</p></div><div className="mt-7 grid gap-4 sm:grid-cols-4"><Metric label="Active controls" value={active.length}/><Metric label="Currently effective" value={effective}/><Metric label="Degraded / failed" value={failed} danger={failed>0}/><Metric label="Verification overdue" value={overdue} danger={overdue>0}/></div>
    <section className="mt-8 rounded-3xl border border-white/10 bg-white/5 p-6"><h2 className="text-xl font-semibold">Governed control standards</h2><div className="mt-5 grid gap-4 lg:grid-cols-2">{controls.map(control=>{const latest=control.verifications[0];return <Link href={`/assurance/sif/controls/${control.id}`} key={control.id} className="rounded-2xl border border-white/10 bg-slate-950/40 p-5 transition hover:border-cyan-400/30"><div className="flex justify-between gap-3"><div><p className="text-xs font-semibold uppercase text-cyan-300">{control.code} · {control.category.replaceAll("_"," ")}</p><h3 className="mt-1 font-semibold">{control.name}</h3></div><span className={`h-fit rounded-full px-3 py-1 text-xs ${latest?.result===CriticalControlVerificationResult.FAILED?"bg-red-400/15 text-red-300":latest?.result===CriticalControlVerificationResult.DEGRADED?"bg-amber-400/15 text-amber-300":latest?.result===CriticalControlVerificationResult.EFFECTIVE?"bg-emerald-400/15 text-emerald-300":"bg-white/5 text-slate-400"}`}>{latest?.result.replaceAll("_"," ")||"NOT VERIFIED"}</span></div><p className="mt-3 text-sm text-slate-400 line-clamp-2">{control.performanceStandard}</p><p className={`mt-4 text-xs ${control.nextVerificationDueAt<now?"text-red-300":"text-slate-500"}`}>Next verification {control.nextVerificationDueAt.toLocaleDateString()} · {control.site?.name||"Organization-wide"} · {control.owner?.name||"Unassigned"}</p></Link>})}{!controls.length&&<p className="text-sm text-slate-500">No critical control standards have been defined.</p>}</div></section>
    {canManage&&<section className="mt-8"><div className="mb-4 flex items-center gap-2 text-cyan-300"><Plus size={17}/><span className="text-sm">Control administration</span></div><CriticalControlCreateForm sites={sites} departments={departments} users={users}/></section>}
  </div>;
}
function Metric({label,value,danger=false}:{label:string;value:number;danger?:boolean}){return <div className="rounded-2xl border border-white/10 bg-white/5 p-5"><p className="text-xs uppercase text-slate-500">{label}</p><p className={`mt-2 text-3xl font-bold ${danger?"text-red-300":""}`}>{value}</p></div>}
