import { EntityCustomFormSubmissions } from "@/features/forms/entity-custom-form-submissions";
import { RuntimeFormCompletion } from "@/features/forms/runtime-form-completion";
import { completePermitForms } from "@/features/permits-to-work/actions";
import { PermitControlForm, PermitGasTestForm, PermitTransitionForm, PermitWorkerForm } from "@/features/permits-to-work/permit-management-forms";
import { getCurrentUserPermissions, requirePermission } from "@/lib/permissions";
import { prisma } from "@/lib/prisma";
import { hasSubscriptionFeature } from "@/lib/subscription";
import { getCurrentUserTenant } from "@/lib/tenant";
import { getPublishedRuntimeForms } from "@/modules/forms/runtime-form.service";
import { ConfigurableFormModule, DocumentEntityType, PermissionKey, PermitToWorkStatus } from "@prisma/client";
import { ArrowLeft, Clock3, ShieldCheck, Users } from "lucide-react";
import Link from "next/link";
import { notFound } from "next/navigation";

export default async function PermitToWorkDetailPage({ params }: { params: Promise<{ id: string }> }) {
  await requirePermission(PermissionKey.VIEW_PERMITS_TO_WORK); const [{ id }, { organizationId, user }, permissions] = await Promise.all([params, getCurrentUserTenant(), getCurrentUserPermissions()]); const canManage = permissions.includes(PermissionKey.MANAGE_PERMITS_TO_WORK);
  const [permit, forms, captured, uploadEnabled] = await Promise.all([
    prisma.permitToWork.findFirst({ where: { id, organizationId }, include: { site: true, department: true, contractor: { include: { workers: { orderBy: { lastName: "asc" } } } }, requestedBy: true, issuedBy: true, approvedBy: true, closedBy: true, controls: { include: { verifiedBy: true }, orderBy: { createdAt: "asc" } }, gasTests: { include: { performedBy: true }, orderBy: { testedAt: "desc" } }, workers: { include: { worker: true }, orderBy: { createdAt: "asc" } }, history: { include: { actor: true }, orderBy: { createdAt: "desc" } } } }),
    getPublishedRuntimeForms(organizationId, ConfigurableFormModule.PERMIT_TO_WORK),
    prisma.configurableFormSubmission.findMany({ where: { organizationId, entityType: ConfigurableFormModule.PERMIT_TO_WORK, entityId: id }, select: { definitionId: true } }),
    hasSubscriptionFeature(organizationId, "DOCUMENT_UPLOAD"),
  ]);
  if (!permit) notFound(); const capturedIds = new Set(captured.map(item => item.definitionId)); const missingForms = forms.filter(form => !capturedIds.has(form.id)); const assignedIds = new Set(permit.workers.map(item => item.workerId)); const availableWorkers = permit.contractor?.workers.filter(worker => !assignedIds.has(worker.id)) ?? []; const canVerify = canManage && ([PermitToWorkStatus.APPROVED, PermitToWorkStatus.SUSPENDED] as PermitToWorkStatus[]).includes(permit.status); const canGasTest = canManage && ([PermitToWorkStatus.APPROVED, PermitToWorkStatus.ACTIVE, PermitToWorkStatus.SUSPENDED] as PermitToWorkStatus[]).includes(permit.status);
  return <div><Link href="/permits-to-work" className="inline-flex items-center gap-2 text-sm text-slate-400 hover:text-white"><ArrowLeft size={16}/>Back to permits</Link>
    <div className="mt-6 flex flex-wrap items-start justify-between gap-5"><div><p className="flex items-center gap-2 text-sm text-cyan-300"><ShieldCheck size={17}/>{permit.reference} · {permit.type.replaceAll("_", " ")}</p><h1 className="mt-2 text-4xl font-bold">{permit.title}</h1><p className="mt-3 max-w-4xl whitespace-pre-wrap text-slate-400">{permit.description || "No additional work description."}</p></div><span className="rounded-full border border-cyan-400/20 bg-cyan-400/10 px-4 py-2 text-sm text-cyan-200">{permit.status.replaceAll("_", " ")}</span></div>
    <div className="mt-7 grid gap-4 sm:grid-cols-4"><Metric label="Site" value={permit.site.name}/><Metric label="Location" value={permit.exactLocation}/><Metric label="Start" value={permit.plannedStartAt.toLocaleString()}/><Metric label="End" value={permit.plannedEndAt.toLocaleString()} warning={permit.plannedEndAt < new Date() && !([PermitToWorkStatus.CLOSED, PermitToWorkStatus.CANCELLED] as PermitToWorkStatus[]).includes(permit.status)}/></div>
    {canManage && <RuntimeFormCompletion action={completePermitForms} entityId={permit.id} entityIdName="permitId" forms={missingForms} submitLabel="Save Permit Forms"/>}
    <EntityCustomFormSubmissions organizationId={organizationId} userId={user.id} module={ConfigurableFormModule.PERMIT_TO_WORK} entityType={DocumentEntityType.PERMIT_TO_WORK} entityId={permit.id} canUpload={canManage && uploadEnabled} className="mt-8 space-y-6"/>
    <div className="mt-8 grid gap-6 lg:grid-cols-2"><section className="rounded-3xl border border-white/10 bg-white/5 p-6"><h2 className="text-xl font-semibold">Work definition</h2><dl className="mt-5 grid gap-4 sm:grid-cols-2"><Detail label="Department" value={permit.department?.name}/><Detail label="Contractor" value={permit.contractor?.name || "Internal work"}/><Detail label="Responsible person" value={permit.responsiblePerson}/><Detail label="Work order" value={permit.workOrderReference}/><Detail label="Requested by" value={permit.requestedBy.name}/><Detail label="Approved by" value={permit.approvedBy?.name}/><Detail label="Issued by" value={permit.issuedBy?.name}/><Detail label="Closed by" value={permit.closedBy?.name}/></dl><Text label="Hazards" value={permit.hazardsSummary}/><Text label="Control strategy" value={permit.controlsSummary}/><Text label="Required PPE" value={permit.requiredPpe}/><Text label="Isolation details" value={permit.isolationDetails}/><Text label="Emergency plan" value={permit.emergencyPlan}/>{permit.closeoutNotes && <Text label="Closeout" value={permit.closeoutNotes}/>}</section>{canManage ? <PermitTransitionForm permitId={permit.id} currentStatus={permit.status}/> : <section className="h-fit rounded-3xl border border-white/10 bg-white/5 p-6"><h2 className="text-xl font-semibold">Lifecycle access</h2><p className="mt-2 text-sm text-slate-400">You can review this permit. An authorized permit manager must make lifecycle decisions.</p></section>}</div>
    <section className="mt-6 rounded-3xl border border-white/10 bg-white/5 p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-semibold">Critical controls</h2><p className="mt-1 text-sm text-slate-400">Every required control must be verified before work can begin.</p></div><span className="text-sm text-cyan-300">{permit.controls.filter(item => item.isVerified).length}/{permit.controls.length} verified</span></div><div className="mt-5 space-y-3">{permit.controls.map(control => <div key={control.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl bg-slate-950/50 p-4"><span><span className="font-medium">{control.description}</span><span className="mt-1 block text-xs text-slate-500">{control.isRequired ? "Required" : "Advisory"}{control.verifiedBy ? ` · Verified by ${control.verifiedBy.name} ${control.verifiedAt?.toLocaleString()}` : ""}</span></span>{canVerify ? <PermitControlForm permitId={permit.id} controlId={control.id} verified={control.isVerified}/> : <span className={`text-xs ${control.isVerified ? "text-emerald-300" : "text-slate-500"}`}>{control.isVerified ? "VERIFIED" : "NOT VERIFIED"}</span>}</div>)}</div></section>
    <div className="mt-6 grid gap-6 lg:grid-cols-2"><section className="rounded-3xl border border-white/10 bg-white/5 p-6"><h2 className="flex items-center gap-2 text-xl font-semibold"><ShieldCheck size={20} className="text-cyan-300"/>Atmospheric testing</h2><p className="mt-2 text-sm text-slate-400">{permit.gasTestingRequired ? "A passing test is required for activation." : "Testing is not mandatory for this permit, but readings may be recorded."}</p><div className="mt-4 space-y-3">{permit.gasTests.map(test => <div key={test.id} className="rounded-xl bg-slate-950/50 p-4"><div className="flex justify-between"><strong className={test.result === "PASS" ? "text-emerald-300" : "text-red-300"}>{test.result}</strong><span className="text-xs text-slate-500">{test.testedAt.toLocaleString()}</span></div><p className="mt-2 text-sm text-slate-300">O₂ {test.oxygenPercent ?? "—"}% · LEL {test.lelPercent ?? "—"}% · H₂S {test.h2sPpm ?? "—"} ppm · CO {test.coPpm ?? "—"} ppm</p><p className="mt-1 text-xs text-slate-500">By {test.performedBy.name}{test.notes ? ` · ${test.notes}` : ""}</p></div>)}{!permit.gasTests.length && <p className="text-sm text-slate-500">No gas tests recorded.</p>}</div></section>{canGasTest && <PermitGasTestForm permitId={permit.id}/>}</div>
    <div className="mt-6 grid gap-6 lg:grid-cols-2"><section className="rounded-3xl border border-white/10 bg-white/5 p-6"><h2 className="flex items-center gap-2 text-xl font-semibold"><Users size={20} className="text-cyan-300"/>Authorized work crew</h2><div className="mt-4 space-y-3">{permit.workers.map(({ worker, role }) => <div key={worker.id} className="rounded-xl bg-slate-950/50 p-4"><p className="font-medium">{worker.firstName} {worker.lastName}</p><p className="mt-1 text-xs text-slate-500">{role || worker.jobTitle || "Worker"} · {worker.status} · Induction expires {worker.inductionExpiresAt?.toLocaleDateString() || "not set"}</p></div>)}{!permit.workers.length && <p className="text-sm text-slate-500">No contractor workers assigned.</p>}</div></section>{canManage && permit.contractor && <PermitWorkerForm permitId={permit.id} workers={availableWorkers}/>}</div>
    <section className="mt-6 rounded-3xl border border-white/10 bg-white/5 p-6"><h2 className="flex items-center gap-2 text-xl font-semibold"><Clock3 size={20} className="text-cyan-300"/>Decision history</h2><div className="mt-5 space-y-4">{permit.history.map(event => <div key={event.id} className="border-l border-cyan-400/30 pl-4"><p className="font-medium">{event.fromStatus ? `${event.fromStatus.replaceAll("_", " ")} → ` : ""}{event.toStatus.replaceAll("_", " ")}</p><p className="mt-1 text-xs text-slate-500">{event.actor.name} · {event.createdAt.toLocaleString()}</p>{event.comments && <p className="mt-2 text-sm text-slate-400">{event.comments}</p>}</div>)}</div></section>
  </div>;
}
function Metric({ label, value, warning = false }: { label: string; value: string; warning?: boolean }) { return <div className="rounded-2xl border border-white/10 bg-white/5 p-4"><p className="text-xs uppercase tracking-wide text-slate-500">{label}</p><p className={`mt-2 text-sm font-semibold ${warning ? "text-red-300" : "text-white"}`}>{value}</p></div>; }
function Detail({ label, value }: { label: string; value: string | null | undefined }) { return <div><dt className="text-xs uppercase tracking-wide text-slate-500">{label}</dt><dd className="mt-1 text-slate-200">{value || "Not recorded"}</dd></div>; }
function Text({ label, value }: { label: string; value: string | null | undefined }) { if (!value) return null; return <div className="mt-5"><p className="text-xs uppercase tracking-wide text-slate-500">{label}</p><p className="mt-2 whitespace-pre-wrap rounded-xl bg-slate-950/50 p-4 text-sm text-slate-300">{value}</p></div>; }
