"use client";

import { initialFormActionState } from "@/core/actions/action-state";
import { approveCertificationManagementReview, completeCertificationManagementReview, createCertificationReviewCapa, scheduleCertificationManagementReview } from "@/features/assurance/certification.actions";
import { RuntimeFormFields } from "@/features/forms/runtime-form-fields";
import { ManagementSystemConclusion, RiskLevel } from "@prisma/client";
import { useActionState } from "react";

const input="mt-2 w-full rounded-xl border border-white/10 bg-slate-950/70 px-4 py-3";
const today=()=>new Date().toISOString().slice(0,10);
function Feedback({state}:{state:{status:string;message:string|null}}){return state.message?<p role={state.status==="ERROR"?"alert":"status"} className={`mt-4 rounded-xl border p-3 text-sm ${state.status==="ERROR"?"border-red-400/20 bg-red-400/10 text-red-300":"border-emerald-400/20 bg-emerald-400/10 text-emerald-200"}`}>{state.message}</p>:null}
function Field({name,label,type="text",required=false,defaultValue}:{name:string;label:string;type?:string;required?:boolean;defaultValue?:string}){return <label className="text-sm">{label}<input name={name} type={type} required={required} defaultValue={defaultValue} className={input}/></label>}
function Textarea({name,label,required=false,defaultValue,rows=3}:{name:string;label:string;required?:boolean;defaultValue?:string;rows?:number}){return <label className="block text-sm">{label}<textarea name={name} required={required} defaultValue={defaultValue} rows={rows} className={input}/></label>}
type Users={id:string;name:string}[];type RuntimeForms=Parameters<typeof RuntimeFormFields>[0]["forms"];

export function ScheduleManagementReviewForm({programId,programName,users}:{programId:string;programName:string;users:Users}){const[state,action,pending]=useActionState(scheduleCertificationManagementReview,initialFormActionState);const year=new Date().getFullYear();return <form action={action} className="rounded-3xl border border-white/10 bg-white/5 p-6"><input type="hidden" name="programId" value={programId}/><h2 className="text-xl font-semibold">Schedule management review</h2><p className="mt-1 text-sm text-slate-400">Create a governed leadership review for {programName}.</p><div className="mt-5 grid gap-4 md:grid-cols-2"><Field name="title" label="Review title" required defaultValue={`${programName} Management Review`}/><label className="text-sm">Chair<select name="chairId" required className={input}><option value="">Select chair</option>{users.map(user=><option key={user.id} value={user.id}>{user.name}</option>)}</select></label><Field name="periodStart" label="Review period start" type="date" required defaultValue={`${year}-01-01`}/><Field name="periodEnd" label="Review period end" type="date" required defaultValue={today()}/><Field name="scheduledAt" label="Meeting date" type="date" required/></div><div className="mt-4"><Textarea name="attendees" label="Expected attendees" rows={2}/></div><button disabled={pending} className="mt-5 rounded-xl bg-cyan-300 px-5 py-3 font-semibold text-slate-950 disabled:opacity-50">{pending?"Scheduling…":"Schedule Review"}</button><Feedback state={state}/></form>}

export function CompleteManagementReviewForm({reviewId,programId,forms,defaults}:{reviewId:string;programId:string;forms:RuntimeForms;defaults:{audit:string;compliance:string;objectives:string;risks:string}}){const[state,action,pending]=useActionState(completeCertificationManagementReview,initialFormActionState);return <form action={action} className="rounded-3xl border border-white/10 bg-white/5 p-6"><input type="hidden" name="reviewId" value={reviewId}/><input type="hidden" name="programId" value={programId}/><h2 className="text-xl font-semibold">Record required management-review inputs</h2><p className="mt-1 text-sm text-slate-400">Confirm evidence, leadership outputs, resources, and continual-improvement decisions.</p><div className="mt-5 space-y-4"><Textarea name="attendees" label="Actual attendees" required/><Textarea name="auditResultsSummary" label="Audit results and trends" required defaultValue={defaults.audit}/><Textarea name="complianceStatusSummary" label="Compliance obligations and evaluation status" required defaultValue={defaults.compliance}/><Textarea name="objectivesPerformance" label="Objectives and performance" required defaultValue={defaults.objectives}/><Textarea name="stakeholderFeedback" label="Worker, customer, regulator, or stakeholder feedback"/><Textarea name="changesInContext" label="Changes in internal/external context and interested-party needs"/><Textarea name="risksAndOpportunities" label="Risks and opportunities" required defaultValue={defaults.risks}/><Textarea name="resourceAdequacy" label="Resource adequacy" required/><Textarea name="decisions" label="Leadership decisions and required changes" required/><Textarea name="improvementOpportunities" label="Continual-improvement opportunities" required/></div><div className="mt-4 grid gap-4 md:grid-cols-2"><label className="text-sm">Management-system conclusion<select name="conclusion" className={input}>{Object.values(ManagementSystemConclusion).map(value=><option key={value} value={value}>{value.replaceAll("_"," ")}</option>)}</select></label><Field name="nextReviewAt" label="Next management-review date" type="date" required/></div><div className="mt-5"><RuntimeFormFields forms={forms}/></div><button disabled={pending} className="mt-5 rounded-xl bg-cyan-300 px-5 py-3 font-semibold text-slate-950 disabled:opacity-50">{pending?"Completing…":"Complete Review"}</button><Feedback state={state}/></form>}

export function ApproveManagementReviewForm({reviewId,programId}:{reviewId:string;programId:string}){const[state,action,pending]=useActionState(approveCertificationManagementReview,initialFormActionState);return <form action={action} className="rounded-2xl border border-emerald-400/20 bg-emerald-400/[.05] p-5"><input type="hidden" name="reviewId" value={reviewId}/><input type="hidden" name="programId" value={programId}/><h2 className="font-semibold">Leadership approval</h2><p className="mt-1 text-sm text-slate-400">Approval confirms the recorded inputs and decisions; it does not confer certification.</p><button disabled={pending} className="mt-4 rounded-xl bg-emerald-300 px-5 py-3 font-semibold text-slate-950 disabled:opacity-50">{pending?"Approving…":"Approve Management Review"}</button><Feedback state={state}/></form>}

export function CertificationReviewCapaForm({reviewId,reference,users}:{reviewId:string;reference:string;users:Users}){const[state,action,pending]=useActionState(createCertificationReviewCapa,initialFormActionState);return <form action={action} className="rounded-3xl border border-amber-400/20 bg-amber-400/[.04] p-6"><input type="hidden" name="reviewId" value={reviewId}/><h2 className="text-xl font-semibold">Create action from review decision</h2><div className="mt-5 grid gap-4 md:grid-cols-2"><Field name="agendaTopic" label="Agenda topic"/><Field name="title" label="Corrective-action title" required defaultValue={`${reference} management-review action`}/><label className="text-sm">Owner<select name="assignedToId" required className={input}><option value="">Select owner</option>{users.map(user=><option key={user.id} value={user.id}>{user.name}</option>)}</select></label><label className="text-sm">Risk level<select name="riskLevel" className={input}>{Object.values(RiskLevel).map(value=><option key={value} value={value}>{value}</option>)}</select></label><Field name="dueDate" label="Due date" type="date" required/></div><div className="mt-4 space-y-4"><Textarea name="decision" label="Decision requiring action" required/><Textarea name="description" label="Action description"/></div><button disabled={pending} className="mt-5 rounded-xl bg-amber-300 px-5 py-3 font-semibold text-slate-950 disabled:opacity-50">{pending?"Creating…":"Create Linked CAPA"}</button><Feedback state={state}/></form>}
