"use client";

import { initialFormActionState } from "@/core/actions/action-state";
import { RuntimeFormFields } from "@/features/forms/runtime-form-fields";
import { createCriticalControl, createCriticalControlCapa, recordCriticalControlVerification, reviewSifSignal } from "@/features/assurance/sif.actions";
import type { SifCandidate } from "@/modules/assurance/sif-intelligence.service";
import { CriticalControlVerificationResult, RiskLevel, SifExposureCategory, SifSignalClassification } from "@prisma/client";
import { useActionState } from "react";

const input="mt-2 w-full rounded-xl border border-white/10 bg-slate-950/70 px-4 py-3";
function Feedback({state}:{state:{status:string;message:string|null}}){return state.message?<p role={state.status==="ERROR"?"alert":"status"} className={`mt-4 rounded-xl border p-3 text-sm ${state.status==="ERROR"?"border-red-400/20 bg-red-400/10 text-red-300":"border-emerald-400/20 bg-emerald-400/10 text-emerald-200"}`}>{state.message}</p>:null}
function Field({name,label,type="text",required=false,defaultValue}:{name:string;label:string;type?:string;required?:boolean;defaultValue?:string}){return <label className="text-sm">{label}<input name={name} type={type} required={required} defaultValue={defaultValue} className={input}/></label>}
type Sites={id:string;name:string}[];type Departments={id:string;name:string;site:{name:string}}[];type Users={id:string;name:string}[];

export function CriticalControlCreateForm({sites,departments,users}:{sites:Sites;departments:Departments;users:Users}){const[state,action,pending]=useActionState(createCriticalControl,initialFormActionState);return <form action={action} className="rounded-3xl border border-white/10 bg-white/5 p-6"><h2 className="text-xl font-semibold">Create critical control standard</h2><div className="mt-5 grid gap-4 md:grid-cols-2"><Field name="code" label="Control code" required/><Field name="name" label="Control name" required/><label className="text-sm">SIF exposure category<select name="category" className={input}>{Object.values(SifExposureCategory).map(value=><option key={value} value={value}>{value.replaceAll("_"," ")}</option>)}</select></label><Field name="verificationFrequencyDays" label="Verification frequency (days)" type="number" required defaultValue="30"/><label className="text-sm">Site scope<select name="siteId" className={input}><option value="">Organization-wide</option>{sites.map(site=><option key={site.id} value={site.id}>{site.name}</option>)}</select></label><label className="text-sm">Department scope<select name="departmentId" className={input}><option value="">All departments</option>{departments.map(department=><option key={department.id} value={department.id}>{department.site.name} — {department.name}</option>)}</select></label><label className="text-sm">Control owner<select name="ownerId" className={input}><option value="">Unassigned</option>{users.map(user=><option key={user.id} value={user.id}>{user.name}</option>)}</select></label></div><label className="mt-4 block text-sm">Description<textarea name="description" rows={2} className={input}/></label><label className="mt-4 block text-sm">Performance standard<textarea name="performanceStandard" required rows={3} className={input}/></label><label className="mt-4 block text-sm">Verification question / prompt<textarea name="verificationPrompt" required rows={3} className={input}/></label><button disabled={pending} className="mt-5 rounded-xl bg-cyan-300 px-5 py-3 font-semibold text-slate-950 disabled:opacity-50">{pending?"Creating…":"Create Critical Control"}</button><Feedback state={state}/></form>}

type RuntimeForms=Parameters<typeof RuntimeFormFields>[0]["forms"];
export function CriticalControlVerificationForm({controlId,forms}:{controlId:string;forms:RuntimeForms}){const[state,action,pending]=useActionState(recordCriticalControlVerification,initialFormActionState);return <form action={action} className="rounded-3xl border border-white/10 bg-white/5 p-6"><input type="hidden" name="controlId" value={controlId}/><h2 className="text-xl font-semibold">Record field verification</h2><div className="mt-5 grid gap-4 md:grid-cols-2"><Field name="verifiedAt" label="Verification date" type="date" required/><label className="text-sm">Result<select name="result" className={input}>{Object.values(CriticalControlVerificationResult).map(value=><option key={value} value={value}>{value.replaceAll("_"," ")}</option>)}</select></label><Field name="evidenceReference" label="Evidence reference"/></div><label className="mt-4 block text-sm">Findings<textarea name="findings" rows={3} className={input}/></label><label className="mt-4 block text-sm">Immediate action taken<textarea name="immediateAction" rows={3} className={input}/></label><div className="mt-5"><RuntimeFormFields forms={forms}/></div><button disabled={pending} className="mt-5 rounded-xl bg-cyan-300 px-5 py-3 font-semibold text-slate-950 disabled:opacity-50">{pending?"Recording…":"Record Verification"}</button><Feedback state={state}/></form>}

export function SifSignalReviewForm({signal}:{signal:SifCandidate}){const[state,action,pending]=useActionState(reviewSifSignal,initialFormActionState);return <form action={action} className="mt-4 rounded-xl border border-white/10 bg-slate-950/50 p-4"><input type="hidden" name="sourceType" value={signal.sourceType}/><input type="hidden" name="sourceId" value={signal.sourceId}/><div className="grid gap-3 md:grid-cols-3"><label className="text-xs">Classification<select name="classification" defaultValue={signal.review?.classification??SifSignalClassification.PRECURSOR} className={input}>{Object.values(SifSignalClassification).map(value=><option key={value} value={value}>{value.replaceAll("_"," ")}</option>)}</select></label><label className="text-xs">Exposure category<select name="exposureCategory" defaultValue={signal.category} className={input}>{Object.values(SifExposureCategory).map(value=><option key={value} value={value}>{value.replaceAll("_"," ")}</option>)}</select></label><label className="text-xs">Potential severity<select name="potentialSeverity" defaultValue={signal.riskLevel} className={input}>{Object.values(RiskLevel).map(value=><option key={value} value={value}>{value}</option>)}</select></label></div><label className="mt-3 block text-xs">Decision rationale<textarea name="rationale" required defaultValue={signal.review?.rationale??""} rows={2} className={input}/></label><label className="mt-3 block text-xs">Critical-control failure notes<textarea name="controlFailureNotes" defaultValue={signal.review?.controlFailureNotes??""} rows={2} className={input}/></label><button disabled={pending} className="mt-3 rounded-lg border border-cyan-400/20 px-3 py-2 text-xs text-cyan-300">{pending?"Saving…":"Save Review"}</button><Feedback state={state}/></form>}

export function CriticalControlCapaForm({verificationId,controlId,controlName,users}:{verificationId:string;controlId:string;controlName:string;users:Users}){const[state,action,pending]=useActionState(createCriticalControlCapa,initialFormActionState);return <form action={action} className="rounded-3xl border border-red-400/15 bg-red-400/[.04] p-6"><input type="hidden" name="verificationId" value={verificationId}/><input type="hidden" name="controlId" value={controlId}/><h2 className="text-xl font-semibold">Convert deficiency to CAPA</h2><div className="mt-4 grid gap-4 md:grid-cols-2"><Field name="title" label="Corrective-action title" required defaultValue={`Restore critical control: ${controlName}`}/><label className="text-sm">Owner<select name="assignedToId" required className={input}><option value="">Select owner</option>{users.map(user=><option key={user.id} value={user.id}>{user.name}</option>)}</select></label><Field name="dueDate" label="Due date" type="date" required/></div><label className="mt-4 block text-sm">Description<textarea name="description" rows={3} className={input}/></label><button disabled={pending} className="mt-5 rounded-xl bg-red-300 px-5 py-3 font-semibold text-slate-950 disabled:opacity-50">{pending?"Creating…":"Create Linked CAPA"}</button><Feedback state={state}/></form>}
