import { requirePermission } from "@/lib/permissions";
import { getCurrentUserTenant } from "@/lib/tenant";
import { findTenantAuditProgramById } from "@/modules/audit/audit-governance.repository";
import { EnterpriseAuditProgramStatus, PermissionKey } from "@prisma/client";
import { ArrowLeft, Building2, CalendarClock, Target } from "lucide-react";
import Link from "next/link";
import { notFound } from "next/navigation";

export default async function AuditProgramDetailPage({ params }: { params: Promise<{ id: string }> }) {
  await requirePermission(PermissionKey.VIEW_AUDITS); const [{ id }, { organizationId }] = await Promise.all([params, getCurrentUserTenant()]); const program = await findTenantAuditProgramById(id, organizationId); if (!program) notFound();
  return <div><Link href="/audits/programs" className="inline-flex items-center gap-2 text-sm text-slate-400 hover:text-white"><ArrowLeft size={16} /> Back to programs</Link><div className="mt-6 flex flex-wrap items-start justify-between gap-5"><div><p className="text-sm text-cyan-300">{program.code || "NO CODE"} · {pretty(program.status)}</p><h1 className="mt-2 text-4xl font-bold">{program.name}</h1><p className="mt-2 max-w-3xl text-slate-400">{program.description || "No description provided."}</p></div>{program.status === EnterpriseAuditProgramStatus.DRAFT && <AuditActionForm action={activateAuditProgramWithFeedback}><input type="hidden" name="programId" value={program.id} /><button className="rounded-2xl bg-emerald-400 px-5 py-3 text-sm font-semibold text-slate-950">Activate Program</button></AuditActionForm>}</div>
    <div className="mt-8 grid gap-6 lg:grid-cols-2"><Panel title="Program definition" icon={<Target size={18} />}><Info label="Frequency" value={pretty(program.frequency)} /><Info label="Risk priority" value={pretty(program.riskPriority)} /><Info label="Owner" value={program.owner?.name || "Not assigned"} /><Info label="Standard" value={[program.standardName, program.standardVersion].filter(Boolean).join(" ") || "Not defined"} /><Text label="Objectives" value={program.objectives} /><Text label="Scope" value={program.scope} /></Panel><Panel title="Organizational scope" icon={<Building2 size={18} />}><p className="text-xs uppercase text-slate-500">Sites</p><div className="mt-3 flex flex-wrap gap-2">{program.sites.length ? program.sites.map(({ site }) => <Tag key={site.id} value={site.name} />) : <span className="text-sm text-slate-500">No sites selected</span>}</div><p className="mt-6 text-xs uppercase text-slate-500">Departments</p><div className="mt-3 flex flex-wrap gap-2">{program.departments.length ? program.departments.map(({ department }) => <Tag key={department.id} value={`${department.site.name} — ${department.name}`} />) : <span className="text-sm text-slate-500">No departments selected</span>}</div></Panel><Panel title="Schedules" icon={<CalendarClock size={18} />}>{program.schedules.length ? program.schedules.map((schedule) => <Row key={schedule.id} title={schedule.name} detail={`${pretty(schedule.frequency)} · ${pretty(schedule.status)}`} />) : <Empty value="No schedules configured." />}</Panel><Panel title="Recent audits" icon={<Target size={18} />}>{program.enterpriseAudits.length ? program.enterpriseAudits.map((audit) => <Link key={audit.id} href={`/audits/${audit.id}`}><Row title={`${audit.reference} — ${audit.title}`} detail={pretty(audit.status)} /></Link>) : <Empty value="No audits generated or linked." />}</Panel></div>
  </div>;
}
function pretty(value: string) { return value.replaceAll("_", " "); } function Panel({ title, icon, children }: { title: string; icon: React.ReactNode; children: React.ReactNode }) { return <section className="rounded-3xl border border-white/10 bg-white/5 p-6"><h2 className="mb-5 flex gap-2 text-lg font-semibold text-white"><span className="text-cyan-300">{icon}</span>{title}</h2><div className="space-y-4">{children}</div></section>; } function Info({ label, value }: { label: string; value: string }) { return <div className="flex justify-between gap-4 border-b border-white/5 pb-3 text-sm"><span className="text-slate-500">{label}</span><span>{value}</span></div>; } function Text({ label, value }: { label: string; value: string | null }) { return <div><p className="text-xs uppercase text-slate-500">{label}</p><p className="mt-2 text-sm leading-6 text-slate-300">{value || "Not provided."}</p></div>; } function Tag({ value }: { value: string }) { return <span className="rounded-full bg-cyan-400/10 px-3 py-1 text-xs text-cyan-200">{value}</span>; } function Row({ title, detail }: { title: string; detail: string }) { return <div className="rounded-2xl bg-slate-950/40 p-4"><p className="text-sm font-medium">{title}</p><p className="mt-1 text-xs text-slate-500">{detail}</p></div>; } function Empty({ value }: { value: string }) { return <p className="rounded-2xl border border-dashed border-white/10 p-5 text-sm text-slate-500">{value}</p>; }
import { AuditActionForm } from "@/features/audits/audit-action-form";
import { activateAuditProgramWithFeedback } from "@/features/audits/governance.actions";
