import { activateAuditProtocol, addAuditProtocolQuestion, addAuditProtocolSection, removeAuditProtocolQuestion, removeAuditProtocolSection, reviseAuditProtocol } from "@/features/audits/governance.actions";
import { requirePermission } from "@/lib/permissions";
import { getCurrentUserTenant } from "@/lib/tenant";
import { findTenantAuditProtocolById } from "@/modules/audit/audit-governance.repository";
import { EnterpriseAuditFindingTrigger, EnterpriseAuditProtocolStatus, EnterpriseAuditQuestionResponseType, EnterpriseAuditSeverity, PermissionKey } from "@prisma/client";
import { ArrowLeft, Plus } from "lucide-react";
import Link from "next/link";
import { notFound } from "next/navigation";

export default async function AuditProtocolDetailPage({ params }: { params: Promise<{ id: string }> }) {
  await requirePermission(PermissionKey.VIEW_AUDITS); const [{ id }, { organizationId }] = await Promise.all([params, getCurrentUserTenant()]); const protocol = await findTenantAuditProtocolById(id, organizationId); if (!protocol) notFound(); const editable = protocol.status === EnterpriseAuditProtocolStatus.DRAFT;
  return <div><Link href="/audits/protocols" className="inline-flex items-center gap-2 text-sm text-slate-400 hover:text-white"><ArrowLeft size={16} /> Back to protocols</Link><div className="mt-6 flex flex-wrap items-start justify-between gap-5"><div><p className="text-sm text-cyan-300">{protocol.code || "NO CODE"} · VERSION {protocol.version}</p><h1 className="mt-2 text-4xl font-bold">{protocol.name}</h1><p className="mt-2 max-w-3xl text-slate-400">{protocol.description || "No description provided."}</p></div><div className="flex items-center gap-3"><Badge value={protocol.status} />{editable && <form action={activateAuditProtocol}><input type="hidden" name="protocolId" value={protocol.id} /><button className="rounded-2xl bg-emerald-400 px-4 py-2 text-sm font-semibold text-slate-950">Activate Protocol</button></form>}{!editable && <form action={reviseAuditProtocol}><input type="hidden" name="protocolId" value={protocol.id} /><button className="rounded-2xl border border-cyan-400/30 px-4 py-2 text-sm font-semibold text-cyan-200">Create Revision</button></form>}</div></div>
    <div className="mt-8 grid gap-4 md:grid-cols-4"><Info label="Standard" value={[protocol.standardName, protocol.standardVersion].filter(Boolean).join(" ") || "Not defined"} /><Info label="Sections" value={String(protocol.sections.length)} /><Info label="Questions" value={String(protocol.sections.reduce((total, section) => total + section.questions.length, 0))} /><Info label="Audit usage" value={String(protocol._count.enterpriseAudits)} /></div>
    <div className="mt-8 space-y-6">{protocol.sections.length === 0 ? <p className="rounded-3xl border border-dashed border-white/15 p-10 text-center text-slate-500">Add the first controlled section below.</p> : protocol.sections.map((section) => <section key={section.id} className="rounded-3xl border border-white/10 bg-white/5 p-6"><div className="flex justify-between gap-4"><div><p className="text-xs text-cyan-300">SECTION {section.sequence} · WEIGHT {section.weight}</p><h2 className="mt-2 text-xl font-semibold">{section.title}</h2><p className="mt-2 text-sm text-slate-400">{section.description || section.guidance || "No section guidance."}</p></div><div className="text-right"><span className="text-xs text-slate-500">{section.questions.length} questions</span>{editable && <form action={removeAuditProtocolSection} className="mt-2"><input type="hidden" name="protocolId" value={protocol.id} /><input type="hidden" name="sectionId" value={section.id} /><button className="text-xs text-red-300">Remove section</button></form>}</div></div><div className="mt-5 space-y-3">{section.questions.map((question) => <div key={question.id} className="rounded-2xl bg-slate-950/50 p-4"><div className="flex flex-wrap justify-between gap-3"><p className="font-medium">{question.sequence}. {question.questionText}</p><div className="flex gap-3"><span className="text-xs text-cyan-300">{pretty(question.responseType)}</span>{editable && <form action={removeAuditProtocolQuestion}><input type="hidden" name="protocolId" value={protocol.id} /><input type="hidden" name="questionId" value={question.id} /><button className="text-xs text-red-300">Remove</button></form>}</div></div><p className="mt-2 text-xs text-slate-500">Finding trigger: {pretty(question.findingTrigger)}{question.defaultSeverity ? ` · ${pretty(question.defaultSeverity)}` : ""}{question.requireEvidence ? " · Evidence required" : ""}{question.requirePhoto ? " · Photo required" : ""}</p>{question.options.length > 0 && <div className="mt-3 flex flex-wrap gap-2">{question.options.map((option) => <span key={option.id} className="rounded-full bg-white/5 px-3 py-1 text-xs text-slate-300">{option.label}</span>)}</div>}</div>)}</div>{editable && <details className="mt-5 rounded-2xl border border-white/10 p-4"><summary className="cursor-pointer text-sm font-medium text-cyan-300">Add question to this section</summary><QuestionForm protocolId={protocol.id} sectionId={section.id} /></details>}</section>)}</div>
    {editable && <section className="mt-8 rounded-3xl border border-cyan-400/20 bg-cyan-400/[0.04] p-6"><h2 className="flex items-center gap-2 text-lg font-semibold"><Plus size={18} className="text-cyan-300" /> Add Protocol Section</h2><form action={addAuditProtocolSection} className="mt-5 grid gap-4 md:grid-cols-2"><input type="hidden" name="protocolId" value={protocol.id} /><Field label="Section title"><input name="title" required className={inputClass} /></Field><Field label="Standard reference"><input name="standardRef" className={inputClass} /></Field><Field label="Description"><textarea name="description" rows={3} className={inputClass} /></Field><Field label="Auditor guidance"><textarea name="guidance" rows={3} className={inputClass} /></Field><Field label="Weight"><input type="number" min="1" name="weight" defaultValue="1" className={inputClass} /></Field><div className="flex items-end justify-end"><button className="rounded-2xl bg-cyan-300 px-5 py-3 text-sm font-semibold text-slate-950">Add Section</button></div></form></section>}
  </div>;
}

function QuestionForm({ protocolId, sectionId }: { protocolId: string; sectionId: string }) { return <form action={addAuditProtocolQuestion} className="mt-5 space-y-5"><input type="hidden" name="protocolId" value={protocolId} /><input type="hidden" name="sectionId" value={sectionId} /><Field label="Question"><textarea name="questionText" required rows={3} className={inputClass} /></Field><div className="grid gap-4 md:grid-cols-3"><Field label="Response type"><select name="responseType" defaultValue={EnterpriseAuditQuestionResponseType.PASS_FAIL} className={inputClass}>{Object.values(EnterpriseAuditQuestionResponseType).map((value) => <option key={value} value={value}>{pretty(value)}</option>)}</select></Field><Field label="Finding trigger"><select name="findingTrigger" defaultValue={EnterpriseAuditFindingTrigger.MANUAL_REVIEW} className={inputClass}>{Object.values(EnterpriseAuditFindingTrigger).map((value) => <option key={value} value={value}>{pretty(value)}</option>)}</select></Field><Field label="Default severity"><select name="defaultSeverity" defaultValue="" className={inputClass}><option value="">Not set</option>{Object.values(EnterpriseAuditSeverity).map((value) => <option key={value} value={value}>{pretty(value)}</option>)}</select></Field></div><div className="grid gap-4 md:grid-cols-3"><Field label="Standard clause"><input name="standardClause" className={inputClass} /></Field><Field label="Regulatory reference"><input name="regulatoryRef" className={inputClass} /></Field><Field label="Weight"><input type="number" min="1" name="weight" defaultValue="1" className={inputClass} /></Field></div><Field label="Guidance"><textarea name="guidance" rows={3} className={inputClass} /></Field><Field label="Options (one per line)"><textarea name="optionLabels" rows={4} className={inputClass} placeholder="Required only for multiple-choice questions" /></Field><div className="grid gap-3 md:grid-cols-3"><Check name="allowNotApplicable" label="Allow N/A" defaultChecked /><Check name="requireComment" label="Require comment" /><Check name="requireEvidence" label="Require evidence" /><Check name="requirePhoto" label="Require photo" /><Check name="automaticallyCreateFinding" label="Auto-create finding" /><Check name="automaticallySuggestCapa" label="Suggest CAPA" /><Check name="automaticallySuggestRisk" label="Suggest risk review" /></div><div className="flex justify-end"><button className="rounded-2xl bg-cyan-300 px-5 py-3 text-sm font-semibold text-slate-950">Add Question</button></div></form>; }
const inputClass = "mt-2 w-full rounded-2xl border border-white/10 bg-slate-950/70 px-4 py-3 text-sm outline-none focus:border-cyan-400/50"; function pretty(value: string) { return value.replaceAll("_", " "); } function Badge({ value }: { value: string }) { return <span className="rounded-full border border-cyan-400/30 bg-cyan-400/10 px-3 py-1 text-xs text-cyan-200">{pretty(value)}</span>; } function Info({ label, value }: { label: string; value: string }) { return <div className="rounded-2xl bg-slate-950/40 p-4"><p className="text-xs uppercase text-slate-500">{label}</p><p className="mt-2 text-sm">{value}</p></div>; } function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block text-sm font-medium text-slate-300">{label}{children}</label>; } function Check({ name, label, defaultChecked = false }: { name: string; label: string; defaultChecked?: boolean }) { return <label className="flex items-center gap-2 text-sm text-slate-300"><input type="checkbox" name={name} defaultChecked={defaultChecked} />{label}</label>; }
